'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BadgeCheck, CreditCard, DollarSign, LifeBuoy, RefreshCw, Search, ShieldAlert, Trophy, Users, WalletCards } from 'lucide-react';
import { OryonBadge, OryonButton, OryonCard, OryonDataGrid, OryonEmptyState, OryonEntityHeader, OryonInput, OryonPanel, OryonStatus } from '@/components/oryon-ui';

type Resource = 'sportsbook' | 'players' | 'payments' | 'risk' | 'responsible-gaming' | 'vip' | 'affiliates' | 'support';
type Row = { id: string; [key: string]: any };
const meta: Record<Resource, { title: string; subtitle: string; icon: typeof Trophy; headers: string[] }> = {
  sportsbook: { title: 'Sportsbook', subtitle: 'Trading, exposição, liability e mercado em tempo real.', icon: Trophy, headers: ['Evento','Mercado','Handle','Liability','Hold','Estado','Trader'] },
  players: { title: 'Players', subtitle: 'Conta, KYC, segmento, LTV e sinais de valor.', icon: Users, headers: ['Player','Segmento','KYC','Balance','LTV','Risk','Estado'] },
  payments: { title: 'Payments', subtitle: 'Depósitos, levantamentos, PSP performance e revisão.', icon: WalletCards, headers: ['Tipo','Método','Player','Amount','Estado','Fee','Data'] },
  risk: { title: 'Risk & Fraud', subtitle: 'Detecção, investigação, escalations e controlo de abuso.', icon: ShieldAlert, headers: ['Caso','Player','Severidade','Estado','Project'] },
  'responsible-gaming': { title: 'Responsible Gaming', subtitle: 'Sinais de risco do jogador e intervenções de protecção.', icon: BadgeCheck, headers: ['Player','Trigger','Severidade','Estado','Última revisão'] },
  vip: { title: 'CRM & VIP', subtitle: 'Carteira VIP, valor, saúde e ownership comercial.', icon: Users, headers: ['Player','Tier','Monthly Handle','Monthly NGR','Manager','Health'] },
  affiliates: { title: 'Affiliates', subtitle: 'Parceiros, FTD, CPA/RevShare e compliance comercial.', icon: Activity, headers: ['Partner','Model','Rate','FTD','Compliance','Active'] },
  support: { title: 'Customer Support', subtitle: 'Fila, SLA, prioridade e atendimento operacional.', icon: LifeBuoy, headers: ['Ticket','Category','Player','Priority','Status','SLA','Assignee'] },
};

const money = (value: unknown) => `MZN ${Number(value ?? 0).toLocaleString('pt-PT', { maximumFractionDigits: 0 })}`;

export default function BettingOperationsPage({ resource }: { resource: Resource }) {
  const [rows, setRows] = useState<Row[]>([]); const [metrics, setMetrics] = useState<Record<string, number>>({}); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/betting-ops?resource=${resource}${query ? `&q=${encodeURIComponent(query)}` : ''}`, { cache: 'no-store', credentials: 'include' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'Falha ao carregar dados.'); setRows(Array.isArray(payload.rows) ? payload.rows : []); setMetrics(payload.metrics ?? {}); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao carregar dados.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [resource]);
  const definition = meta[resource];
  const displayRows = useMemo(() => rows.slice(0, 80).map((row) => { if (resource === 'sportsbook') return [String(row.event),String(row.market),money(row.handle),money(row.liability),`${row.hold ?? 0}%`,<OryonStatus key={row.id} status={row.status === 'suspended' ? 'critical' : 'active'} label={String(row.status ?? 'open')} />,String(row.trader ?? '')]; if (resource === 'players') return [String(row.playerId),String(row.segment),<OryonBadge key="kyc" tone={row.kycStatus === 'verified' ? 'success' : 'warning'}>{String(row.kycStatus)}</OryonBadge>,money(row.balance),money(row.lifetimeValue),String(row.riskScore),<OryonStatus key="status" status={row.status === 'suspended' ? 'critical' : 'active'} label={String(row.status)} />]; if (resource === 'payments') return [String(row.type),String(row.method),String(row.playerId),money(row.amount),String(row.status),money(row.fee),String(row.createdAt ?? '').slice(0,16).replace('T',' ')]; if (resource === 'risk') return [String(row.title),String(row.playerId),<OryonBadge key="sev" tone={String(row.severity).includes('critical') ? 'danger' : String(row.severity).includes('high') ? 'warning' : 'neutral'}>{String(row.severity)}</OryonBadge>,String(row.status),String(row.projectId)]; if (resource === 'responsible-gaming') return [String(row.playerId),String(row.trigger),String(row.severity),String(row.status),String(row.lastReviewedAt ?? '').slice(0,16)]; if (resource === 'vip') return [String(row.playerId),String(row.tier),money(row.monthlyHandle),money(row.monthlyNgr),String(row.assignedManager),String(row.health)]; if (resource === 'affiliates') return [String(row.name),String(row.model),String(row.commissionRate),String(row.ftd),String(row.complianceStatus),row.active ? 'Yes' : 'No']; return [String(row.ticket),String(row.category),String(row.playerId),String(row.priority),String(row.status),String(row.slaMinutes),String(row.assignee)]; }), [rows, resource]);
  const metricCards = Object.entries(metrics).slice(0, 4);
  const labels: Record<string, string> = { handle: 'Handle', liability: 'Liability', averageHold: 'Avg Hold', suspended: 'Suspended', active: 'Active', vip: 'VIP', kycReview: 'KYC Review', ltv: 'LTV', processed: 'Processed', completed: 'Completed', failed: 'Failed', review: 'Review', total: 'Total', open: 'Open', high: 'High' };
  return <div className="grid gap-5"><OryonEntityHeader title={definition.title} subtitle={definition.subtitle} meta={<OryonBadge tone="accent"><definition.icon className="mr-1 h-3 w-3"/>Live operator view</OryonBadge>} actions={<OryonButton variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? 'h-3.5 w-3.5 animate-spin' : 'h-3.5 w-3.5'}/>Actualizar</OryonButton>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(([key,value]) => <OryonCard key={key} className="p-4"><p className="text-label">{labels[key] ?? key}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{key === 'averageHold' ? `${value}%` : key === 'handle' || key === 'liability' || key === 'ltv' || key === 'processed' ? money(value) : Number(value).toLocaleString('pt-PT')}</p></OryonCard>)}</div><OryonPanel className="p-3"><div className="flex flex-col gap-2 md:flex-row md:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><OryonInput className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void load()} placeholder={`Pesquisar em ${definition.title.toLowerCase()}…`}/></div><OryonButton onClick={() => void load()}>Pesquisar</OryonButton></div></OryonPanel>{error ? <OryonCard className="p-5 text-sm text-[hsl(var(--status-danger))]">{error}</OryonCard> : loading ? <OryonPanel className="p-8 text-sm text-muted-foreground">A carregar dados operacionais…</OryonPanel> : displayRows.length ? <OryonPanel className="overflow-hidden"><OryonDataGrid headers={definition.headers} rows={displayRows}/></OryonPanel> : <OryonEmptyState icon={<AlertTriangle className="h-5 w-5"/>} title="Sem registos" description="Não existem registos para este contexto."/>}</div>;
}
