'use client';

import Link from 'next/link';
import { BookOpen, FileText, Network, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { OryonBadge, OryonButton, OryonCard, OryonDataGrid, OryonEntityHeader, OryonInput, OryonPanel } from '@/components/oryon-ui';

type Row = Record<string, any> & { id: string };
async function fetchModule(module: string, query = ''): Promise<Row[]> { const response = await fetch(`/api/modules/${module}${query ? `?q=${encodeURIComponent(query)}` : ''}`, { cache:'no-store', credentials:'include' }); const payload=await response.json(); if(!response.ok) throw new Error(payload.error ?? 'Falha ao carregar conhecimento.'); return Array.isArray(payload.data)?payload.data:[]; }

export default function KnowledgeHubExperience(){
 const [q,setQ]=useState(''); const [results,setResults]=useState<Row[]>([]); const [docs,setDocs]=useState<Row[]>([]); const [files,setFiles]=useState<Row[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
 useEffect(()=>{ Promise.all([fetchModule('documents'),fetchModule('cloud')]).then(([d,f])=>{setDocs(d);setFiles(f)}).catch(e=>setError(e instanceof Error?e.message:'Falha')); },[]);
 const search=async()=>{ if(!q.trim()){setResults([]);return;} setLoading(true);try{const [kb,d,f]=await Promise.all([fetchModule('knowledge-base',q),fetchModule('documents',q),fetchModule('cloud',q)]);setResults([...kb,...d,...f].slice(0,50));}catch(e){setError(e instanceof Error?e.message:'Falha')}finally{setLoading(false)}};
 return <div className="grid gap-6"><OryonEntityHeader title="Knowledge" subtitle="Search, Docs, Files e contexto de conhecimento num único espaço."/><OryonPanel className="p-4"><div className="flex flex-col gap-3 md:flex-row"><OryonInput className="flex-1" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Pesquisar em todo o conhecimento…" aria-label="Pesquisar conhecimento"/><OryonButton onClick={()=>void search()} disabled={loading}><Search className="h-3.5 w-3.5"/>Search</OryonButton></div></OryonPanel>{error&&<OryonCard className="p-4 text-sm text-[hsl(var(--status-danger))]">{error}</OryonCard>}<div className="grid gap-4 lg:grid-cols-3"><OryonCard className="p-5"><BookOpen className="h-5 w-5 text-primary"/><h2 className="mt-3 text-h2">Search</h2><p className="mt-1 text-body-small text-muted-foreground">Pesquisa transversal sobre conteúdo operacional.</p><OryonBadge className="mt-4">{results.length || '0'} resultados</OryonBadge></OryonCard><Link href="/dashboard/documents"><OryonCard className="h-full p-5 hover:bg-surface-2"><FileText className="h-5 w-5 text-primary"/><h2 className="mt-3 text-h2">Docs</h2><p className="mt-1 text-body-small text-muted-foreground">{docs.length} documentos disponíveis no backend.</p></OryonCard></Link><Link href="/dashboard/cloud"><OryonCard className="h-full p-5 hover:bg-surface-2"><Network className="h-5 w-5 text-primary"/><h2 className="mt-3 text-h2">Files</h2><p className="mt-1 text-body-small text-muted-foreground">{files.length} recursos persistidos.</p></OryonCard></Link></div>{results.length?<OryonPanel className="p-4"><p className="text-label">Resultados</p><div className="mt-3"><OryonDataGrid headers={['Título','Tipo','Contexto']} rows={results.map(r=>[String(r.title??r.name??r.id),String(r.type??r.mimeType??'knowledge'),String(r.category??r.department??'Knowledge')])}/></div></OryonPanel>:null}</div>;
}
