'use client';

import { useState } from 'react';
import { Activity, Bot, CalendarDays, FileText, FolderKanban, MessageSquare, Sparkles, Workflow, ArrowRight } from 'lucide-react';
import { OryonAIResponse, OryonBadge, OryonButton, OryonCard, OryonEntityHeader, OryonPanel } from '@/components/oryon-ui';

const scopes = [
 {key:'operations',label:'Operations',icon:Activity}, {key:'projects',label:'Projects',icon:FolderKanban}, {key:'meetings',label:'Meetings',icon:CalendarDays}, {key:'knowledge',label:'Knowledge',icon:FileText}, {key:'reports',label:'Reports',icon:MessageSquare}, {key:'automation',label:'Automation',icon:Workflow},
];

export default function OryonAIExperience(){
 const [scope,setScope]=useState('operations'); const [prompt,setPrompt]=useState(''); const [busy,setBusy]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState<string|null>(null);
 const ask=async()=>{if(!prompt.trim())return;setBusy(true);setError(null);try{const response=await fetch('/api/oryon-ai',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({prompt:prompt.trim(),scope})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'AI_REQUEST_FAILED');setResult(payload.data??payload)}catch(e){setError(e instanceof Error?e.message:'Falha ao executar OryonAI')}finally{setBusy(false)}};
 return <div className="grid gap-6"><OryonEntityHeader title="Ask Oryon" subtitle="Descreva o que precisa. O Oryon decide internamente a melhor inteligência e as ferramentas a utilizar." meta={<OryonBadge tone="accent"><Sparkles className="mr-1 h-3 w-3"/>Oryon Intelligence</OryonBadge>}/><div className="grid gap-4 xl:grid-cols-[220px_minmax(0,1fr)]"><OryonPanel className="p-3"><p className="px-2 py-2 text-label">Context</p>{scopes.map(({key,label,icon:Icon})=><button key={key} onClick={()=>setScope(key)} className={`flex w-full items-center gap-2 rounded-[7px] px-2.5 py-2 text-left text-[12px] ${scope===key?'bg-primary/[0.08] text-primary':'text-muted-foreground hover:bg-surface-1'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</OryonPanel><div className="grid gap-4"><OryonPanel elevated className="relative overflow-hidden p-5"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-[9px] bg-primary/10 text-primary"><Bot className="h-4 w-4"/></div><div><p className="text-[12px] font-semibold text-foreground">What do you need?</p><p className="text-[11px] text-muted-foreground">Context: {scopes.find(x=>x.key===scope)?.label}</p></div></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex.: Resume o trabalho em risco e sugere as três decisões mais importantes." className="mt-5 min-h-32 w-full resize-y rounded-[10px] border border-border bg-surface-1 p-3 text-[13px] leading-5 outline-none transition-colors focus:border-primary/60"/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-[10px] text-muted-foreground">O agente é seleccionado internamente. O contexto fica visível, a complexidade fica escondida.</p><OryonButton onClick={()=>void ask()} disabled={busy||!prompt.trim()}>{busy?<Sparkles className="h-3.5 w-3.5 animate-pulse"/>:<ArrowRight className="h-3.5 w-3.5"/>}{busy?'A analisar…':'Ask Oryon'}</OryonButton></div></OryonPanel>{error&&<OryonCard className="p-4 text-sm text-[hsl(var(--status-danger))]">{error}</OryonCard>}{result?<OryonAIResponse status="ready" title="Oryon Intelligence" answer={result.answer??result.response??result.briefing??result.summary??'Resposta recebida.'} evidence={result.evidence??(result.toolResults?`${result.toolResults.length} tool results`:undefined)} sources={result.sources?result.sources.map((s:any)=>typeof s==='string'?s:String(s.title??s.uri??s.id)).join(' · '):undefined} confidence={typeof result.confidence==='number'?result.confidence:undefined} nextStep={result.nextStep??result.recommendedNextStep}/>:null}</div></div></div>;
}
