'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, CalendarDays, Clock3, DollarSign, GanttChartSquare, LayoutDashboard, Plus, Target, Users, XCircle } from 'lucide-react';
import { OryonBadge, OryonButton, OryonCard, OryonDataGrid, OryonEntityHeader, OryonPanel, OryonRiskCard, OryonStatus, OryonTimeline } from '@/components/oryon-ui';

type Row = { id: string; [key: string]: any };
type Payload = { project: Row; overview: any; tasks: Row[]; subtasks: Row[]; milestones: Row[]; dependencies: Row[]; files: Row[]; docs: Row[]; meetings: Row[]; risks: Row[]; decisions: Row[]; activities: Row[]; goals: Row[]; allocations: Row[]; timeEntries: Row[] };
const groups = [{ key: 'overview', label: 'Overview', icon: LayoutDashboard }, { key: 'work', label: 'Work', icon: GanttChartSquare, children: ['Board','Timeline','Calendar'] }, { key: 'planning', label: 'Planning', icon: Users, children: ['Resources','Goals','Budget'] }, { key: 'intelligence', label: 'Intelligence', icon: Activity, children: ['Risks','Activity','Time'] }];

export default function ProjectExperience() {
  const [workspaces, setWorkspaces] = useState<Row[]>([]); const [projectId, setProjectId] = useState(''); const [payload, setPayload] = useState<Payload | null>(null); const [section, setSection] = useState('overview'); const [newProject, setNewProject] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const api = async (url: string, options?: RequestInit) => { const response = await fetch(url, { cache: 'no-store', credentials: 'include', ...options }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'REQUEST_FAILED'); return result; };
  const load = async () => { setLoading(true); try { const result = await api('/api/project-os?resource=workspaces'); const rows = Array.isArray(result.data) ? result.data : []; setWorkspaces(rows); if (!projectId) { const first = rows.flatMap((w: Row) => Array.isArray(w.projects) ? w.projects : []).find((p: Row) => p.id); if (first?.id) setProjectId(String(first.id)); } } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } finally { setLoading(false); } };
  const loadProject = async () => { if (!projectId) return; try { const result = await api(`/api/project-os?resource=project&projectId=${encodeURIComponent(projectId)}`); setPayload(result.data as Payload); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } };
  useEffect(() => { void load(); }, []); useEffect(() => { void loadProject(); }, [projectId]);
  const createProject = async () => { if (!newProject.trim()) return; try { const selectedWorkspace = workspaces.find((w) => Array.isArray(w.projects) && w.projects.some((p: Row) => String(p.id) === projectId)); await api('/api/project-os', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'project.create', input: { name: newProject.trim(), workspaceId: selectedWorkspace?.id } }) }); setNewProject(''); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } };
  const tasksByStatus = useMemo(() => { const groups: Record<string, Row[]> = { todo: [], in_progress: [], blocked: [], done: [] }; for (const task of payload?.tasks ?? []) { const status = String(task.status ?? '').toLowerCase(); const bucket = status.includes('done') || status.includes('complete') ? 'done' : status.includes('block') ? 'blocked' : status.includes('progress') || status.includes('active') ? 'in_progress' : 'todo'; groups[bucket].push(task); } return groups; }, [payload?.tasks]);
  if (loading && !payload) return <div className="grid gap-4"><div className="h-14 animate-pulse rounded-[10px] bg-surface-2"/><div className="grid gap-4 xl:grid-cols-[260px_1fr]"><div className="h-[520px] animate-pulse rounded-[10px] bg-surface-1"/><div className="h-[520px] animate-pulse rounded-[10px] bg-surface-1"/></div></div>;
  if (error && !payload) return <OryonCard className="p-6 text-sm text-[hsl(var(--status-danger))]">{error}</OryonCard>;

  const renderContent = () => {
    if (!payload) return <OryonCard className="p-8 text-sm text-muted-foreground">Selecione um projecto.</OryonCard>;
    if (section === 'overview') return <div className="grid gap-4"><div className="grid gap-px overflow-hidden rounded-[10px] border border-border bg-border sm:grid-cols-2 xl:grid-cols-4">{[['Tasks',payload.tasks.length],['Overdue',payload.overview.overdueTasks],['Blocked',payload.overview.blockedTasks],['Critical',payload.overview.criticalTasks]].map(([label,value])=><div key={String(label)} className="bg-surface-1 p-4"><p className="text-label">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{String(value)}</p></div>)}</div><OryonPanel className="p-5"><div className="flex items-center justify-between"><div><p className="text-label">Health engine</p><h2 className="mt-1 text-h2">Project health</h2></div><OryonBadge tone={payload.project.health === 'HEALTHY' ? 'success' : payload.project.health === 'AT_RISK' ? 'warning' : 'danger'}>{String(payload.project.health ?? 'UNKNOWN')}</OryonBadge></div><div className="mt-4 grid gap-3 md:grid-cols-3"><OryonRiskCard title="Capacity" level={payload.overview.capacity.overloadHours > 0 ? 'high' : 'low'} score={Math.round(payload.overview.capacity.utilization ?? 0)} description={`${payload.overview.capacity.allocatedHours ?? 0}h alocadas de ${payload.overview.capacity.availableHours ?? 0}h.`}/><OryonRiskCard title="Deadline" level={Number(payload.overview.deadlineDays) < 0 ? 'critical' : Number(payload.overview.deadlineDays) < 7 ? 'medium' : 'low'} score={Math.min(100, Math.max(0, 100 - Number(payload.overview.deadlineDays ?? 0)))} description={`${payload.overview.deadlineDays ?? 0} dias para o deadline.`}/><OryonRiskCard title="Milestones" level={Number(payload.overview.milestoneVarianceDays) > 0 ? 'medium' : 'low'} score={Math.min(100, Math.abs(Number(payload.overview.milestoneVarianceDays ?? 0)) * 5)} description={`Variância ${payload.overview.milestoneVarianceDays ?? 0} dias.`}/></div></OryonPanel></div>;
    if (section === 'board') return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{Object.entries(tasksByStatus).map(([key,rows])=><OryonPanel key={key} className="p-3"><div className="mb-3 flex items-center justify-between"><span className="text-label capitalize">{key.replace('_',' ')}</span><OryonBadge>{rows.length}</OryonBadge></div>{rows.map((task)=><button key={task.id} onClick={()=>{}} className="mb-2 block w-full rounded-[8px] border border-border bg-surface-1 p-3 text-left hover:bg-surface-2"><span className="block text-[12px] font-medium">{String(task.title ?? 'Task')}</span><span className="mt-1 block text-[10px] text-muted-foreground">{String(task.priority ?? 'medium')} · {task.dueDate ? new Date(task.dueDate).toLocaleDateString('pt-PT') : 'sem prazo'}</span></button>)}</OryonPanel>)}</div>;
    if (section === 'timeline') return <OryonPanel className="p-5"><OryonTimeline items={payload.tasks.slice(0,30).map((task)=>({title:String(task.title??'Task'),meta:task.dueDate?new Date(task.dueDate).toLocaleDateString('pt-PT'):'Sem data',description:String(task.description??''),status:String(task.status??'').toLowerCase().includes('done')?'done':'current'}))}/></OryonPanel>;
    if (section === 'calendar') return <OryonDataGrid headers={['Task','Due','Status']} rows={payload.tasks.filter((t)=>t.dueDate).slice(0,40).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).map((task)=>[String(task.title??'Task'),new Date(task.dueDate).toLocaleDateString('pt-PT'),<OryonStatus key={task.id} status="idle" label={String(task.status??'todo')}/>])}/>;
    if (section === 'resources') return <OryonDataGrid headers={['Resource','Available','Allocated','Utilization']} rows={payload.allocations.slice(0,40).map((row)=>[String(row.userId??row.id),String(row.availableHours??0),String(row.allocatedHours??0),`${Math.round(Number(row.utilization??0))}%`])}/>;
    if (section === 'goals') return <OryonDataGrid headers={['Goal','Progress','Target','Status']} rows={payload.goals.slice(0,40).map((goal)=>[String(goal.title??goal.name??'Goal'),`${Number(goal.progress??0)}%`,String(goal.target??100),String(goal.status??'active')])}/>;
    if (section === 'budget') return <OryonDataGrid headers={['Budget','Value']} rows={[["Budget",String(payload.project.budget??payload.project.budgetAmount??'n/a')],["Spent",String(payload.project.spent??'n/a')],["Budget health",`${Number(payload.overview.budgetPercent??0)}%`]]}/>;
    if (section === 'risks') return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{payload.risks.slice(0,30).map((risk)=><OryonRiskCard key={risk.id} title={String(risk.title??risk.name??'Risk')} level={String(risk.level??risk.severity??'medium').includes('critical')?'critical':String(risk.level??risk.severity??'medium').includes('high')?'high':'medium'} description={String(risk.description??risk.mitigation??'')}/>)}</div>;
    if (section === 'activity') return <OryonDataGrid headers={['Actor','Action','Time']} rows={payload.activities.slice(0,40).map((item)=>[String(item.actorName??item.userId??'User'),String(item.action??item.event??item.description??'Activity'),String(item.createdAt??item.time??'')])}/>;
    return <OryonDataGrid headers={['Entry','Minutes','Note']} rows={payload.timeEntries.slice(0,40).map((item)=>[String(item.id),String(item.minutes??0),String(item.note??'')])}/>;
  };

  return <div className="grid gap-5"><OryonEntityHeader title={String(payload?.project.name ?? 'Project OS')} subtitle={String(payload?.project.objective ?? 'Projectos, execução, planeamento e inteligência.')} meta={<div className="flex items-center gap-2"><OryonStatus status="active" label={String(payload?.project.health ?? 'operational')} /><OryonBadge>{String(payload?.project.ownerName ?? payload?.project.ownerId ?? 'Owner')}</OryonBadge></div>} actions={<div className="flex gap-2"><OryonButton variant="outline" onClick={()=>void loadProject()}>Actualizar</OryonButton><OryonButton onClick={()=>{}}><Plus className="h-3.5 w-3.5"/>Acção</OryonButton></div>}/><div className="grid xl:grid-cols-[240px_1fr] gap-4"><OryonPanel className="h-fit p-2"><p className="px-2 py-2 text-label">Project navigation</p>{groups.map((group)=><div key={group.key} className="mb-1"><button onClick={()=>setSection(group.key)} className={`flex w-full items-center gap-2 rounded-[7px] px-2.5 py-2 text-left text-[12px] ${section===group.key?'bg-primary/[0.08] text-primary':'text-muted-foreground hover:bg-surface-1'}`}><group.icon className="h-3.5 w-3.5"/>{group.label}</button>{group.children?.map((child)=><button key={child} onClick={()=>setSection(child.toLowerCase())} className={`ml-5 block w-[calc(100%-20px)] rounded-[6px] px-2 py-1.5 text-left text-[11px] ${section===child.toLowerCase()?'text-primary':'text-muted-foreground hover:text-foreground'}`}>{child}</button>)}</div>)}<div className="mt-3 border-t border-border pt-3"><p className="px-2 py-1.5 text-label">Create</p><div className="flex gap-1.5"><input aria-label="Novo projecto" className="h-8 min-w-0 flex-1 rounded-[6px] border border-border bg-surface-1 px-2 text-[11px]" value={newProject} onChange={(e)=>setNewProject(e.target.value)} placeholder="Novo"/><button className="grid h-8 w-8 place-items-center rounded-[6px] bg-primary text-primary-foreground" onClick={()=>void createProject()}><Plus className="h-3.5 w-3.5"/></button></div></div></OryonPanel><div className="min-w-0">{renderContent()}</div></div></div>;
}
