import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        headline: ['var(--font-inter)', 'Inter', 'sans-serif'],
        code: ['monospace'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: {
          0: 'hsl(var(--surface-0))',
          1: 'hsl(var(--surface-1))',
          2: 'hsl(var(--surface-2))',
          3: 'hsl(var(--surface-3))',
        },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        'border-strong': 'hsl(var(--border-strong))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--primary))',
          '2': 'hsl(var(--muted-foreground))',
          '3': 'hsl(var(--text-secondary))',
          '4': 'hsl(var(--surface-3))',
          '5': 'hsl(var(--border-strong))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--surface-1))',
          foreground: 'hsl(var(--foreground))',
          primary: 'hsl(var(--primary))',
          'primary-foreground': 'hsl(var(--primary-foreground))',
          accent: 'hsl(var(--surface-2))',
          'accent-foreground': 'hsl(var(--foreground))',
          border: 'hsl(var(--border))',
          ring: 'hsl(var(--ring))',
        },
      },
      borderRadius: {
        control: '6px',
        input: '8px',
        card: '10px',
        panel: '12px',
        dialog: '14px',
        pill: '999px',
        lg: 'var(--radius-card)',
        md: 'var(--radius-input)',
        sm: 'var(--radius-control)',
      },
      boxShadow: {
        flat: 'var(--elevation-flat)',
        raised: 'var(--elevation-raised)',
        floating: 'var(--elevation-floating)',
        overlay: 'var(--elevation-overlay)',
        modal: 'var(--elevation-modal)',
      },
      transitionDuration: {
        motionFast: '160ms',
        motionBase: '200ms',
        motionSurface: '320ms',
        motionSlow: '400ms',
      },
      transitionTimingFunction: {
        oryon: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fadeIn': { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slideInRight': { from: { transform: 'translateX(18px)', opacity: '0' }, to: { transform: 'translateX(0)', opacity: '1' } },
        'pulseSoft': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.72' } },
      },
      animation: {
        'accordion-down': 'accordion-down 180ms ease-out',
        'accordion-up': 'accordion-up 180ms ease-out',
        'fade-in': 'fadeIn 200ms cubic-bezier(0.22,1,0.36,1)',
        'slide-in-right': 'slideInRight 320ms cubic-bezier(0.22,1,0.36,1)',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
