import * as admin from 'firebase-admin';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { onSchedule } from 'firebase-functions/v2/scheduler';
import * as logger from 'firebase-functions/logger';
import { z } from 'zod';

if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();
const REGION = 'africa-south1';
const MAX_JOBS_PER_TICK = 20;
const MAX_ATTEMPTS = 8;
const LEASE_MS = 8 * 60 * 1000;
const DEFAULT_TIMEOUT_MS = 120000;
const MAX_WAIT_MS = 60000;
type Data = Record<string, unknown>;
type Job = Data & { id: string; companyId: string; automationId: string; workflowId: string; workflowVersion: number; attempts: number; maxAttempts: number; trigger: string; payload: Data };
type Step = { id: string; type: 'log'|'http'|'module.create'|'module.update'|'module.delete'|'condition'|'action'; name?: string; config: Data };
const StepSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,80}$/),type:z.enum(['log','http','module.create','module.update','module.delete','condition','action']),name:z.string().max(180).optional(),config:z.record(z.unknown()).default({})});
const WorkflowSchema=z.object({name:z.string().min(1).max(180),description:z.string().max(5000).optional(),active:z.boolean().default(true),executionTimeoutMs:z.number().int().min(1000).max(900000).default(DEFAULT_TIMEOUT_MS),retryPolicy:z.object({maxAttempts:z.number().int().min(1).max(20).default(5),backoffMs:z.number().int().min(1000).max(900000).default(30000)}).default({maxAttempts:5,backoffMs:30000}),steps:z.array(StepSchema).min(1).max(100)});
const MODULES:Record<string,string>={tasks:'module_tasks',projects:'projects',meetings:'module_meetings',campaigns:'module_campaigns',calendar:'module_calendar_events',workspaces:'module_workspaces',reports:'module_reports',integrations:'module_integrations','knowledge-base':'module_knowledge_articles'};
function now(){return admin.firestore.Timestamp.now();}
export function retryDelayMs(attempt:number,base=30000){return Math.min(900000,Math.max(1000,base)*(2**Math.max(0,attempt-1)));}
function template(value:unknown,ctx:Data):unknown{if(typeof value==='string')return value.replace(/{{\s*([^}]+)\s*}}/g,(_,path:string)=>{let cur:unknown=ctx;for(const part of path.split('.')){if(!cur||typeof cur!=='object')return '';cur=(cur as Data)[part];}return cur==null?'':String(cur)});if(Array.isArray(value))return value.map(v=>template(v,ctx));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Data).map(([k,v])=>[k,template(v,ctx)]));return value;}
function safeData(config:Data):Data{const source=config.data;const data=source&&typeof source==='object'&&!Array.isArray(source)?{...(source as Data)}:{};for(const key of ['id','companyId','ownerId','createdBy','updatedBy','createdAt','updatedAt','version','searchTitle'])delete data[key];return data;}
async function withTimeout<T>(promise:Promise<T>,ms:number):Promise<T>{let timer:NodeJS.Timeout|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('EXECUTION_TIMEOUT')),ms);})]);}finally{if(timer)clearTimeout(timer);}}
async function claimJob(ref:admin.firestore.DocumentReference):Promise<Job|null>{return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)return null;const d=snap.data()??{};const status=String(d.status??'');const next=d.nextAttemptAt instanceof admin.firestore.Timestamp?d.nextAttemptAt.toMillis():0;const lease=d.leaseUntil instanceof admin.firestore.Timestamp?d.leaseUntil.toMillis():0;if(['succeeded','dead','cancelled'].includes(status))return null;if(status==='running'&&lease>Date.now())return null;if(status==='pending'&&next>Date.now())return null;const attempts=Number(d.attempts??0)+1;tx.update(ref,{status:'running',attempts,leaseUntil:admin.firestore.Timestamp.fromMillis(Date.now()+LEASE_MS),startedAt:d.startedAt??now(),updatedAt:now()});return{...d,id:snap.id,companyId:String(d.companyId??''),automationId:String(d.automationId??''),workflowId:String(d.workflowId??''),workflowVersion:Number(d.workflowVersion??1),attempts,maxAttempts:Number(d.maxAttempts??MAX_ATTEMPTS),trigger:String(d.trigger??'manual'),payload:d.payload&&typeof d.payload==='object'&&!Array.isArray(d.payload)?d.payload as Data:{}};});}
function receiptId(jobId:string,executionId:string,stepId:string){return`${jobId}:${executionId}:${stepId}`.replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,700);}
async function writeStepLog(runRef:admin.firestore.DocumentReference,jobId:string,stepId:string,patch:Data){await runRef.collection('steps').doc(stepId).set({jobId,stepId,...patch,updatedAt:now()},{merge:true});await runRef.collection('logs').add({jobId,stepId,...patch,createdAt:now()});}
async function notify(companyId:string,userId:string,title:string,body:string,entityType:string,entityId:string){if(!userId)return;const ref=db.collection('notifications').doc(userId).collection('items').doc(`${entityId}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`);await ref.create({id:ref.id,companyId,userId,title,body,entityType,entityId,eventName:'automation.action',severity:'medium',category:'system',actionUrl:'/dashboard/inbox',read:false,createdAt:now(),metadata:{source:'automation-engine-v2'}});}
async function createApproval(companyId:string,jobId:string,cfg:Data){const approverId=String(cfg.approverId??'');if(!approverId)throw new Error('APPROVER_REQUIRED');const approvalRef=db.collection('approvals').doc();const eventRef=db.collection('event_outbox').doc(`automation_approval_${approvalRef.id}`);const title=String(cfg.title??'Aprovação automática');const requesterId=String(cfg.requesterId??'automation-worker');await db.runTransaction(async tx=>{tx.create(approvalRef,{id:approvalRef.id,companyId,createdBy:'automation-worker',requesterId,updatedBy:'automation-worker',title,description:String(cfg.description??''),entityType:String(cfg.entityType??'automation'),entityId:String(cfg.entityId??jobId),approverId,mode:'single',steps:[{id:'approval_1',approverId,status:'PENDING',index:0}],currentStep:0,state:'PENDING',status:'pending',metadata:{source:'automation-engine-v2'},version:1,createdAt:now(),updatedAt:now()});tx.create(eventRef,{eventId:eventRef.id,companyId,eventName:'approval.requested',entityType:'approval',entityId:approvalRef.id,actorId:'automation-worker',occurredAt:now(),payload:{title,approverId,requesterId,entityType:String(cfg.entityType??'automation'),entityId:String(cfg.entityId??jobId)},metadata:{source:'automation-engine-v2'},schemaVersion:1,status:'pending',attempts:0,nextAttemptAt:now()});});return{id:approvalRef.id};}
async function executeAction(job:Job,executionId:string,config:Data):Promise<Data>{const cfg=template(config,{payload:job.payload,job:{id:job.id,executionId},company:{id:job.companyId}}) as Data;const op=String(cfg.operation??'');
 if(op==='notify'){await notify(job.companyId,String(cfg.userId??job.payload.userId??''),String(cfg.title??'Automação'),String(cfg.body??''),String(cfg.entityType??'automation'),String(cfg.entityId??job.id));return{ok:true,operation:op};}
 if(op==='email'){const ref=db.collection('notification_deliveries').doc(`${job.id}_${executionId}_${Date.now()}`);await ref.create({id:ref.id,companyId:job.companyId,channel:'email',to:String(cfg.to??''),subject:String(cfg.subject??''),body:String(cfg.body??''),status:'queued',createdAt:now(),source:'automation'});return{queued:true,operation:op};}
 if(op==='wait'){const ms=Math.min(MAX_WAIT_MS,Math.max(0,Number(cfg.ms??1000)));await new Promise(resolve=>setTimeout(resolve,ms));return{operation:op,waitedMs:ms};}
 if(op==='condition'||op==='branch'){const actual=job.payload[String(cfg.field??'')];const expected=cfg.value;const operator=String(cfg.operator??'equals');const valid=operator==='equals'?actual===expected:operator==='not_equals'?actual!==expected:operator==='contains'?String(actual??'').includes(String(expected??'')):false;if(!valid&&String(cfg.whenFalse??'stop')==='stop')throw new Error('CONDITION_NOT_MET');return{operation:op,valid};}
 if(op==='request.approval')return createApproval(job.companyId,job.id,cfg);
 if(op==='escalate'){const ids=Array.isArray(cfg.userIds)?cfg.userIds.map(String):[];for(const uid of ids)await notify(job.companyId,uid,String(cfg.title??'Escalação'),String(cfg.body??'Uma automação requer atenção.'),'automation',job.id);return{operation:op,recipients:ids.length};}
 if(op==='run.workflow'){const workflowId=String(cfg.workflowId??'');const w=await db.collection('module_workflows').doc(workflowId).get();if(!w.exists||w.data()?.companyId!==job.companyId)throw new Error('WORKFLOW_NOT_FOUND');const id=`chain_${job.id}_${executionId}_${Date.now()}`;await db.collection('automation_jobs').doc(id).create({id,companyId:job.companyId,automationId:String(cfg.automationId??''),workflowId,workflowVersion:Number(w.data()?.version??1),trigger:'workflow',payload:job.payload,idempotencyKey:id,status:'pending',attempts:0,maxAttempts:5,createdAt:now(),updatedAt:now(),nextAttemptAt:now(),parentExecutionId:executionId});return{operation:op,jobId:id};}
 if(['webhook','integration','http'].includes(op)){const url=String(cfg.url??'');if(!url.startsWith('https://'))throw new Error('HTTP_URL_NOT_ALLOWED');const parsed=new URL(url);if(['localhost','127.0.0.1','0.0.0.0','::1'].includes(parsed.hostname))throw new Error('HTTP_HOST_NOT_ALLOWED');const headers=cfg.headers&&typeof cfg.headers==='object'?Object.fromEntries(Object.entries(cfg.headers as Data).map(([k,v])=>[k,String(v)])):{};headers['Idempotency-Key']=`${job.companyId}:${job.id}:${executionId}`;const method=String(cfg.method??'POST').toUpperCase();const response=await fetch(url,{method,headers,body:method==='GET'||method==='HEAD'?undefined:JSON.stringify(cfg.body??job.payload),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`HTTP_${response.status}`);return{operation:op,status:response.status};}
 const creates:Record<string,string>={ 'create.task':'tasks','create.project':'projects','create.meeting':'meetings','create.record':String(cfg.module??'')};if(creates[op]){const collection=MODULES[creates[op]];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const id=`automation_${job.id.slice(0,36)}_${executionId.slice(0,16)}`;await db.collection(collection).doc(id).create({id,companyId:job.companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...safeData(cfg)});return{operation:op,id};}
 if(op==='generate.document'){const ref=db.collection('module_reports').doc();await ref.create({id:ref.id,companyId:job.companyId,title:String(cfg.title??'Generated document'),content:String(cfg.content??''),createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,source:'automation'});return{operation:op,id:ref.id};}
 if(op==='update.record'||op==='assign.user'||op==='assign.team'||op==='delete.record'){const collection=MODULES[String(cfg.module??'')];const id=String(cfg.id??'');if(!collection||!id)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(id);const s=await ref.get();if(op==='delete.record'){if(s.exists&&s.data()?.companyId===job.companyId)await ref.delete();return{operation:op,id};}if(!s.exists||s.data()?.companyId!==job.companyId)throw new Error('TARGET_NOT_FOUND');const patch=op==='assign.user'?{assigneeId:String(cfg.userId??''),ownerId:String(cfg.userId??'')}:op==='assign.team'?{teamId:String(cfg.teamId??'')}:safeData(cfg);await ref.update({...patch,updatedBy:'automation-worker',updatedAt:now()});return{operation:op,id};}
 if(op==='ai'){const ref=db.collection('automation_action_requests').doc();await ref.create({id:ref.id,companyId:job.companyId,operation:'ai',prompt:String(cfg.prompt??''),payload:job.payload,status:'queued',createdAt:now(),jobId:job.id,executionId});return{operation:op,id:ref.id,status:'queued'};}
 throw new Error('ACTION_NOT_SUPPORTED');}
async function executeStep(job:Job,step:Step,executionId:string):Promise<Data>{const receiptRef=db.collection('automation_step_receipts').doc(receiptId(job.id,executionId,step.id));const existing=await receiptRef.get();if(existing.exists&&existing.data()?.status==='completed')return(existing.data()?.result??{}) as Data;const config=template(step.config,{payload:job.payload,job:{id:job.id,executionId},company:{id:job.companyId}}) as Data;let result:Data;if(step.type==='log')result={message:String(config.message??step.name??'')};else if(step.type==='condition')result=await executeAction(job,executionId,{operation:'condition',...config});else if(step.type==='http')result=await executeAction(job,executionId,{operation:'http',...config});else if(step.type==='action')result=await executeAction(job,executionId,config);else{const collection=MODULES[String(config.module??'')];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const data=safeData(config);const targetId=step.type==='module.create'?`job_${job.id.slice(0,40)}_${step.id}`:String(config.id??'');if(!targetId)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(targetId);if(step.type==='module.create')await ref.set({id:targetId,companyId:job.companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...data});else{const target=await ref.get();if(step.type==='module.update'){if(!target.exists||target.data()?.companyId!==job.companyId)throw new Error('TARGET_NOT_FOUND');await ref.update({...data,updatedAt:now(),updatedBy:'automation-worker'});}else if(target.exists&&target.data()?.companyId===job.companyId)await ref.delete();}result={id:targetId};}await receiptRef.create({companyId:job.companyId,jobId:job.id,executionId,stepId:step.id,mutationKey:`${job.companyId}:${job.id}:${executionId}:${step.id}`,status:'completed',result,createdAt:now(),updatedAt:now()});return result;}
async function executeJob(job:Job){const snap=await db.collection('module_workflows').doc(job.workflowId).collection('versions').doc(String(job.workflowVersion)).get();if(!snap.exists)throw new Error('WORKFLOW_VERSION_NOT_FOUND');const parsed=WorkflowSchema.safeParse(snap.data());if(!parsed.success)throw new Error('WORKFLOW_INVALID');const runRef=db.collection('automation_runs').doc(job.id);await runRef.set({id:job.id,jobId:job.id,automationId:job.automationId,workflowId:job.workflowId,workflowVersion:job.workflowVersion,companyId:job.companyId,status:'running',attempts:job.attempts,trigger:job.trigger,payload:job.payload,startedAt:now(),updatedAt:now()},{merge:true});const deadline=Date.now()+parsed.data.executionTimeoutMs;try{for(const step of parsed.data.steps as Step[]){if(Date.now()>deadline)throw new Error('EXECUTION_TIMEOUT');const jobState=await db.collection('automation_jobs').doc(job.id).get();if(String(jobState.data()?.status)==='cancelled')throw new Error('EXECUTION_CANCELLED');const started=Date.now();await writeStepLog(runRef,job.id,step.id,{status:'running',name:step.name??step.id});try{const result=await withTimeout(executeStep(job,step,job.id),Math.max(1000,deadline-Date.now()));await writeStepLog(runRef,job.id,step.id,{status:'succeeded',result,durationMs:Date.now()-started,finishedAt:now()});}catch(error){const message=error instanceof Error?error.message:'STEP_FAILED';await writeStepLog(runRef,job.id,step.id,{status:'failed',error:message,durationMs:Date.now()-started});throw error;}}await runRef.set({status:'succeeded',finishedAt:now(),updatedAt:now()},{merge:true});}catch(error){await runRef.set({status:'failed',error:error instanceof Error?error.message:'RUN_FAILED',finishedAt:now(),updatedAt:now()},{merge:true});throw error;}}
async function processOne(ref:admin.firestore.QueryDocumentSnapshot){const job=await claimJob(ref.ref);if(!job)return;const automation=await db.collection('module_automations').doc(job.automationId).get();const limit=Math.max(1,Number(automation.data()?.concurrencyLimit??5));const rate=Math.max(1,Number(automation.data()?.rateLimitPerMinute??100));if(!(await acquireConcurrency(job.companyId,limit))){await ref.ref.update({status:'pending',attempts:Math.max(0,job.attempts-1),nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+5000),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});return;}try{if(!(await consumeRateLimit(job.companyId,rate))){await ref.ref.update({status:'pending',nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+30000),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});return;}await executeJob(job);await ref.ref.update({status:'succeeded',finishedAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now(),error:admin.firestore.FieldValue.delete()});}catch(error){const message=error instanceof Error?error.message:'JOB_FAILED';if(message==='EXECUTION_CANCELLED'){await ref.ref.update({status:'cancelled',leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});}else if(job.attempts>=job.maxAttempts){await ref.ref.update({status:'dead',error:message,finishedAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});await db.collection('automation_dead_letters').doc(ref.id).set({...job,status:'dead',error:message,deadAt:now()},{merge:true});}else{const workflow=await db.collection('module_workflows').doc(job.workflowId).get();const base=Number((workflow.data()?.retryPolicy as Data|undefined)?.backoffMs??30000);await ref.ref.update({status:'pending',error:message,nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+retryDelayMs(job.attempts,base)),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});}}finally{await releaseConcurrency(job.companyId);}}
async function acquireConcurrency(companyId:string,limit:number):Promise<boolean>{const ref=db.collection('automation_concurrency').doc(companyId);return db.runTransaction(async tx=>{const s=await tx.get(ref);const active=Number(s.data()?.active??0);if(active>=limit)return false;tx.set(ref,{companyId,active:active+1,updatedAt:now()},{merge:true});return true;});}
async function releaseConcurrency(companyId:string){const ref=db.collection('automation_concurrency').doc(companyId);await db.runTransaction(async tx=>{const s=await tx.get(ref);tx.set(ref,{companyId,active:Math.max(0,Number(s.data()?.active??0)-1),updatedAt:now()},{merge:true});});}
async function consumeRateLimit(companyId:string,limit:number):Promise<boolean>{const key=`${companyId}_${new Date().toISOString().slice(0,16).replace(/[-:T]/g,'')}`;const ref=db.collection('automation_rate_limits').doc(key);return db.runTransaction(async tx=>{const s=await tx.get(ref);const count=Number(s.data()?.count??0);if(count>=limit)return false;tx.set(ref,{companyId,count:count+1,updatedAt:now()},{merge:true});return true;});}
async function identity(request:{auth?:{uid:string;token:Data}}){if(!request.auth)throw new HttpsError('unauthenticated','A autenticação é necessária.');const companyId=typeof request.auth.token.companyId==='string'?request.auth.token.companyId:'';if(!companyId)throw new HttpsError('permission-denied','Empresa não encontrada.');const member=await db.collection('companies').doc(companyId).collection('members').doc(request.auth.uid).get();if(!member.exists||member.data()?.status!=='active')throw new HttpsError('permission-denied','Membership inactiva.');return{uid:request.auth.uid,companyId,role:String(member.data()?.role??'viewer')};}
export const automationWorkerV2=onSchedule({schedule:'* * * * *',timeZone:'UTC',region:REGION,timeoutSeconds:540,memory:'512MiB'},async()=>{const[pending,running]=await Promise.all([db.collection('automation_jobs').where('status','==','pending').limit(MAX_JOBS_PER_TICK).get(),db.collection('automation_jobs').where('status','==','running').limit(MAX_JOBS_PER_TICK).get()]);await Promise.all([...pending.docs,...running.docs].map(processOne));logger.info('Automation V2 tick completed',{pending:pending.size,running:running.size});});
export const triggerAutomationEventV2=onCall({region:REGION},async request=>{const i=await identity(request);const p=z.object({eventName:z.string().min(1).max(180),eventId:z.string().max(180).optional(),payload:z.record(z.unknown()).default({})}).safeParse(request.data);if(!p.success)throw new HttpsError('invalid-argument','Evento inválido.');const automations=await db.collection('module_automations').where('companyId','==',i.companyId).where('active','==',true).limit(500).get();const jobs:string[]=[];for(const automation of automations.docs){const trigger=automation.data().trigger as Data|undefined;if(trigger?.type!=='event'||trigger.eventName!==p.data.eventName)continue;const workflow=await db.collection('module_workflows').doc(String(automation.data().workflowId??'')).get();if(!workflow.exists||workflow.data()?.companyId!==i.companyId)continue;const id=`event_${automation.id}_${p.data.eventId??Date.now()}_${i.uid}`.replace(/[^A-Za-z0-9_-]/g,'_');await db.collection('automation_jobs').doc(id).create({id,companyId:i.companyId,automationId:automation.id,workflowId:workflow.id,workflowVersion:Number(workflow.data()?.version??1),trigger:'event',payload:{...p.data.payload,eventName:p.data.eventName,eventId:p.data.eventId??null},idempotencyKey:id,status:'pending',attempts:0,maxAttempts:Number((automation.data().retryPolicy as Data|undefined)?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now()});jobs.push(id);}return{queued:jobs.length,jobIds:jobs};});
export const runAutomationNowV2=onCall({region:REGION},async request=>{const i=await identity(request);if(!['owner','admin','manager'].includes(i.role))throw new HttpsError('permission-denied','Sem permissão.');const p=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,180}$/),payload:z.record(z.unknown()).default({})}).safeParse(request.data);if(!p.success)throw new HttpsError('invalid-argument','Dados inválidos.');const automation=await db.collection('module_automations').doc(p.data.id).get();if(!automation.exists||automation.data()?.companyId!==i.companyId||automation.data()?.active!==true)throw new HttpsError('failed-precondition','Automação inexistente ou inactiva.');const d=automation.data()??{};const workflow=await db.collection('module_workflows').doc(String(d.workflowId??'')).get();if(!workflow.exists||workflow.data()?.companyId!==i.companyId)throw new HttpsError('failed-precondition','Workflow inexistente.');const id=`manual_${automation.id}_${Date.now()}_${i.uid}`;await db.collection('automation_jobs').doc(id).create({id,companyId:i.companyId,automationId:automation.id,workflowId:workflow.id,workflowVersion:Number(workflow.data()?.version??1),trigger:'manual',payload:p.data.payload,idempotencyKey:id,status:'pending',attempts:0,maxAttempts:Number((d.retryPolicy as Data|undefined)?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now()});return{queued:true,jobId:id,workflowVersion:Number(workflow.data()?.version??1)};});
