import * as admin from 'firebase-admin';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { onSchedule } from 'firebase-functions/v2/scheduler';
import * as logger from 'firebase-functions/logger';
import { z } from 'zod';

if (!admin.apps.length) admin.initializeApp();
const db=admin.firestore();
const REGION='africa-south1'; const PAGE_SIZE=500; const MAX_JOBS_PER_TICK=20; const MAX_ATTEMPTS=8; const LEASE_MS=8*60*1000; const DEFAULT_TIMEOUT_MS=120000; const MAX_WAIT_MS=60000;
const MODULE_COLLECTIONS:Record<string,string>={calendar:'module_calendar_events',meetings:'module_meetings',integrations:'module_integrations','knowledge-base':'module_knowledge_articles',campaigns:'module_campaigns',tasks:'module_tasks',reports:'module_reports',pulse:'module_pulse_items',workspaces:'module_workspaces',projects:'projects'};
const StepSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,80}$/),type:z.enum(['log','http','module.create','module.update','module.delete','condition','action']),name:z.string().max(180).optional(),config:z.record(z.unknown()).default({})});
const WorkflowSchema=z.object({name:z.string().min(1).max(180),description:z.string().max(5000).optional(),active:z.boolean().default(true),executionTimeoutMs:z.number().int().min(1000).max(15*60*1000).default(DEFAULT_TIMEOUT_MS),retryPolicy:z.object({maxAttempts:z.number().int().min(1).max(20).default(5),backoffMs:z.number().int().min(1000).max(15*60*1000).default(30000)}).default({maxAttempts:5,backoffMs:30000}),steps:z.array(StepSchema).min(1).max(100)});
function now(){return admin.firestore.Timestamp.now()}
function replaceTemplate(value:unknown,ctx:Record<string,unknown>):unknown{if(typeof value==='string')return value.replace(/{{\s*([^}]+)\s*}}/g,(_,path:string)=>{let c:unknown=ctx;for(const part of path.split('.')){if(!c||typeof c!=='object')return '';c=(c as Record<string,unknown>)[part]}return c==null?'':String(c)});if(Array.isArray(value))return value.map(v=>replaceTemplate(v,ctx));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,replaceTemplate(v,ctx)]));return value}
function retryDelayMs(attempt:number,base:number){return Math.min(15*60*1000,Math.max(1000,base)*(2**Math.max(0,attempt-1)))}
async function withTimeout<T>(promise:Promise<T>,ms:number){let timer:NodeJS.Timeout|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('EXECUTION_TIMEOUT')),ms)})])}finally{if(timer)clearTimeout(timer)}}
async function acquireConcurrency(companyId:string,limit:number){const ref=db.collection('automation_concurrency').doc(companyId);return db.runTransaction(async tx=>{const s=await tx.get(ref);const active=Number(s.data()?.active??0);if(active>=limit)return false;tx.set(ref,{companyId,active:active+1,updatedAt:now()},{merge:true});return true})}
async function releaseConcurrency(companyId:string){const ref=db.collection('automation_concurrency').doc(companyId);await db.runTransaction(async tx=>{const s=await tx.get(ref);const active=Math.max(0,Number(s.data()?.active??0)-1);tx.set(ref,{companyId,active,updatedAt:now()},{merge:true})})}
async function rateLimit(companyId:string,limit:number){const key=`${companyId}_${new Date().toISOString().slice(0,16).replace(/[-:T]/g,'')}`;const ref=db.collection('automation_rate_limits').doc(key);return db.runTransaction(async tx=>{const s=await tx.get(ref);const count=Number(s.data()?.count??0);if(count>=limit)return false;tx.set(ref,{companyId,count:count+1,updatedAt:now()},{merge:true});return true})}
async function claimJob(ref:admin.firestore.DocumentReference){return db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)return null;const d=s.data()??{};const status=String(d.status??'');const next=d.nextAttemptAt instanceof admin.firestore.Timestamp?d.nextAttemptAt.toMillis():0;const lease=d.leaseUntil instanceof admin.firestore.Timestamp?d.leaseUntil.toMillis():0;if(['succeeded','dead','cancelled'].includes(status))return null;if(status==='running'&&lease>Date.now())return null;if(status==='pending'&&next>Date.now())return null;const attempts=Number(d.attempts??0)+1;tx.update(ref,{status:'running',attempts,leaseUntil:admin.firestore.Timestamp.fromMillis(Date.now()+LEASE_MS),startedAt:d.startedAt??now(),updatedAt:now()});return{...d,id:s.id,attempts}})}
function receiptId(jobId:string,executionId:string,stepId:string){return`${jobId}:${executionId}:${stepId}`.replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,700)}
async function recordStep(companyId:string,runRef:admin.firestore.DocumentReference,jobId:string,executionId:string,stepId:string,patch:Record<string,unknown>){const ref=runRef.collection('steps').doc(stepId);await ref.set({companyId,jobId,executionId,stepId,...patch,updatedAt:now()},{merge:true});await runRef.collection('logs').add({companyId,jobId,executionId,stepId,...patch,createdAt:now()})}
async function notifyUser(companyId:string,userId:string,title:string,body:string,entityType:string,entityId:string){if(!userId)return;const ref=db.collection('notifications').doc(userId).collection('items').doc(`${entityId}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`);await ref.create({id:ref.id,companyId,userId,category:'system',severity:'medium',title,body,entityType,entityId,eventName:'automation.action',actionUrl:'/dashboard/inbox',read:false,channels:['in-app'],deliveryMode:'instant',createdAt:now(),metadata:{source:'automation-engine-v2'}})}
async function action(companyId:string,jobId:string,executionId:string,config:Record<string,unknown>,payload:Record<string,unknown>){const op=String(config.operation??'');const cfg=replaceTemplate(config,{payload,job:{id:jobId,executionId},company:{id:companyId}}) as Record<string,unknown>;
 if(op==='notify'){await notifyUser(companyId,String(cfg.userId??payload.userId??''),String(cfg.title??'Automação'),String(cfg.body??''),String(cfg.entityType??'automation'),String(cfg.entityId??jobId));return{ok:true,operation:op}}
 if(op==='email'){const ref=db.collection('notification_deliveries').doc(`${jobId}_${executionId}_${Date.now()}`);await ref.create({id:ref.id,companyId,channel:'email',to:String(cfg.to??''),subject:String(cfg.subject??''),body:String(cfg.body??''),status:'queued',createdAt:now(),source:'automation'});return{queued:true,operation:op}}
 if(op==='wait'){const ms=Math.min(MAX_WAIT_MS,Math.max(0,Number(cfg.ms??1000)));await new Promise(r=>setTimeout(r,ms));return{waitedMs:ms}}
 if(op==='condition'||op==='branch'){const actual=payload[String(cfg.field??'')];const expected=cfg.value;const operator=String(cfg.operator??'equals');const valid=operator==='equals'?actual===expected:operator==='not_equals'?actual!==expected:operator==='contains'?String(actual??'').includes(String(expected??'')):false;if(!valid&&String(cfg.whenFalse??'stop')==='stop')throw new Error('CONDITION_NOT_MET');return{valid}}
 if(op==='create.task'||op==='create.project'||op==='create.meeting'||op==='create.record'){const module=op==='create.task'?'tasks':op==='create.project'?'projects':op==='create.meeting'?'meetings':String(cfg.module??'');const collection=MODULE_COLLECTIONS[module];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const data=cfg.data&&typeof cfg.data==='object'&&!Array.isArray(cfg.data)?cfg.data as Record<string,unknown>:{};const id=`automation_${jobId.slice(0,36)}_${executionId.slice(0,20)}`;const ref=db.collection(collection).doc(id);await ref.set({id,companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...data},{merge:false});return{id,collection,operation:op}}
 if(op==='update.record'||op==='assign.user'||op==='assign.team'){const collection=MODULE_COLLECTIONS[String(cfg.module??'')];const targetId=String(cfg.id??'');if(!collection||!/^[A-Za-z0-9_-]{1,180}$/.test(targetId))throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(targetId);const s=await ref.get();if(!s.exists||s.data()?.companyId!==companyId)throw new Error('TARGET_NOT_FOUND');const patch=op==='assign.user'?{assigneeId:String(cfg.userId??''),ownerId:String(cfg.userId??'')}:op==='assign.team'?{teamId:String(cfg.teamId??'')}:(cfg.data&&typeof cfg.data==='object'?cfg.data:{});await ref.update({...patch,updatedAt:now(),updatedBy:'automation-worker'});return{id:targetId,operation:op}}
 if(op==='delete.record'){const collection=MODULE_COLLECTIONS[String(cfg.module??'')];const targetId=String(cfg.id??'');if(!collection||!targetId)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(targetId);const s=await ref.get();if(s.exists&&s.data()?.companyId===companyId)await ref.delete();return{id:targetId,operation:op}}
 if(op==='request.approval'){const ref=db.collection('approvals').doc();const approverId=String(cfg.approverId??'');if(!approverId)throw new Error('APPROVER_REQUIRED');await ref.create({id:ref.id,companyId,createdBy:'automation-worker',updatedBy:'automation-worker',title:String(cfg.title??'Aprovação automática'),description:String(cfg.description??''),entityType:String(cfg.entityType??'automation'),entityId:String(cfg.entityId??jobId),approverId,requesterId:String(cfg.requesterId??'automation-worker'),mode:'single',steps:[{id:'approval_1',approverId,status:'PENDING',index:0}],currentStep:0,state:'PENDING',status:'pending',metadata:{source:'automation-engine-v2'},version:1,createdAt:now(),updatedAt:now()});return{id:ref.id,operation:op}}
 if(op==='escalate'){const recipients=(Array.isArray(cfg.userIds)?cfg.userIds:[]).map(String);for(const uid of recipients)await notifyUser(companyId,uid,String(cfg.title??'Escalação'),String(cfg.body??'Uma automação foi escalada.'),'automation',jobId);return{recipients:recipients.length}}
 if(op==='run.workflow'){const workflowId=String(cfg.workflowId??'');if(!workflowId)throw new Error('WORKFLOW_REQUIRED');const w=await db.collection('module_workflows').doc(workflowId).get();if(!w.exists||w.data()?.companyId!==companyId)throw new Error('WORKFLOW_NOT_FOUND');const key=`chain_${jobId}_${executionId}_${Date.now()}`;await db.collection('automation_jobs').doc(key).create({id:key,companyId,automationId:String(cfg.automationId??''),workflowId,workflowVersion:Number(w.data()?.version??1),trigger:'workflow',payload,idempotencyKey:key,status:'pending',attempts:0,maxAttempts:5,createdAt:now(),updatedAt:now(),nextAttemptAt:now(),parentExecutionId:executionId});return{jobId:key,operation:op}}
 if(op==='webhook'||op==='integration'||op==='http'){const url=String(cfg.url??'');if(!url.startsWith('https://'))throw new Error('HTTP_URL_NOT_ALLOWED');const headers=cfg.headers&&typeof cfg.headers==='object'?Object.fromEntries(Object.entries(cfg.headers as Record<string,unknown>).map(([k,v])=>[k,String(v)])):{};headers['Idempotency-Key']=`${companyId}:${jobId}:${executionId}`;const response=await fetch(url,{method:String(cfg.method??'POST').toUpperCase(),headers,body:JSON.stringify(cfg.body??payload),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`HTTP_${response.status}`);return{status:response.status,operation:op}}
 if(op==='generate.document'){const ref=db.collection('module_reports').doc();await ref.create({id:ref.id,companyId,title:String(cfg.title??'Generated document'),content:String(cfg.content??''),createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,source:'automation'});return{id:ref.id,operation:op}}
 if(op==='ai'){const ref=db.collection('automation_action_requests').doc();await ref.create({id:ref.id,companyId,operation:'ai',prompt:String(cfg.prompt??''),payload,status:'queued',createdAt:now(),jobId,executionId});return{id:ref.id,status:'queued',operation:op}}
 throw new Error('ACTION_NOT_SUPPORTED');
}
async function executeStep(companyId:string,jobId:string,executionId:string,step:z.infer<typeof StepSchema>,payload:Record<string,unknown>){const receiptRef=db.collection('automation_step_receipts').doc(receiptId(jobId,executionId,step.id));const existing=await receiptRef.get();if(existing.exists&&existing.data()?.status==='completed')return(existing.data()?.result??{}) as Record<string,unknown>;const config=replaceTemplate(step.config,{payload,job:{id:jobId,executionId},company:{id:companyId}}) as Record<string,unknown>;let result:Record<string,unknown>;
 if(step.type==='log')result={message:String(config.message??step.name??'')};
 else if(step.type==='condition'){result=await action(companyId,jobId,executionId,{...config,operation:'condition'},payload)}
 else if(step.type==='http')result=await action(companyId,jobId,executionId,{...config,operation:'http'},payload)
 else if(step.type==='action')result=await action(companyId,jobId,executionId,config,payload)
 else {const module=String(config.module??'');const collection=MODULE_COLLECTIONS[module];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const data=cfgData(config);if(step.type==='module.create'){const id=`job_${jobId.slice(0,40)}_${step.id}`;await db.collection(collection).doc(id).set({id,companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...data});result={id};}else{const targetId=String(config.id??'');if(!targetId)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(targetId);const s=await ref.get();if(step.type==='module.update'){if(!s.exists||s.data()?.companyId!==companyId)throw new Error('TARGET_NOT_FOUND');await ref.update({...data,updatedAt:now(),updatedBy:'automation-worker'});}else if(s.exists&&s.data()?.companyId===companyId)await ref.delete();result={id:targetId};}}
 await receiptRef.create({companyId,jobId,executionId,stepId:step.id,mutationKey:`${companyId}:${jobId}:${executionId}:${step.id}`,status:'completed',result,createdAt:now(),updatedAt:now()});return result}
function cfgData(config:Record<string,unknown>){const data=config.data&&typeof config.data==='object'&&!Array.isArray(config.data)?{...(config.data as Record<string,unknown>)}:{};for(const key of ['id','companyId','createdBy','updatedBy','createdAt','updatedAt','version','searchTitle'])delete data[key];return data}
async function executeJob(job:Record<string,unknown>){const jobId=String(job.id);const companyId=String(job.companyId);const workflowId=String(job.workflowId);const version=Number(job.workflowVersion??1);const snap=await db.collection('module_workflows').doc(workflowId).collection('versions').doc(String(version)).get();if(!snap.exists)throw new Error('WORKFLOW_VERSION_NOT_FOUND');const parsed=WorkflowSchema.safeParse(snap.data());if(!parsed.success)throw new Error('WORKFLOW_INVALID');const runRef=db.collection('automation_runs').doc(jobId);await runRef.set({id:jobId,jobId,automationId:job.automationId,workflowId,workflowVersion:version,companyId,status:'running',attempts:job.attempts,trigger:job.trigger,payload:job.payload??{},startedAt:now(),updatedAt:now()},{merge:true});
 const payload=job.payload&&typeof job.payload==='object'?job.payload as Record<string,unknown>:{};const timeout=parsed.data.executionTimeoutMs;try{for(const step of parsed.data.steps){const jobState=await db.collection('automation_jobs').doc(jobId).get();if(String(jobState.data()?.status)==='cancelled')throw new Error('EXECUTION_CANCELLED');await recordStep(companyId,runRef,jobId,jobId,step.id,{status:'running',attempts:1,name:step.name??step.id});const started=Date.now();try{const result=await withTimeout(executeStep(companyId,jobId,jobId,step,payload),timeout);await recordStep(companyId,runRef,jobId,jobId,step.id,{status:'succeeded',result,durationMs:Date.now()-started,finishedAt:now()});}catch(error){const message=error instanceof Error?error.message:'STEP_FAILED';await recordStep(companyId,runRef,jobId,jobId,step.id,{status:'failed',error:message,durationMs:Date.now()-started});throw error;}}
 await runRef.set({status:'succeeded',finishedAt:now(),updatedAt:now()},{merge:true});}catch(error){await runRef.set({status:'failed',error:error instanceof Error?error.message:'RUN_FAILED',finishedAt:now(),updatedAt:now()},{merge:true});throw error}}
async function processOne(ref:admin.firestore.QueryDocumentSnapshot){const job=await claimJob(ref.ref);if(!job)return;const automation=await db.collection('module_automations').doc(String(job.automationId??'')).get();const limit=Math.max(1,Number(automation.data()?.concurrencyLimit??5));const rate=Math.max(1,Number(automation.data()?.rateLimitPerMinute??100));if(!(await acquireConcurrency(String(job.companyId),limit))){await ref.ref.update({status:'pending',attempts:Math.max(0,Number(job.attempts??1)-1),nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+5000),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});return;}try{if(!(await rateLimit(String(job.companyId),rate))){await ref.ref.update({status:'pending',nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+30000),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});return;}await executeJob(job);await ref.ref.update({status:'succeeded',finishedAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now(),error:admin.firestore.FieldValue.delete()})}catch(error){const attempts=Number(job.attempts??1);const maxAttempts=Number(job.maxAttempts??MAX_ATTEMPTS);const message=error instanceof Error?error.message:'JOB_FAILED';if(message==='EXECUTION_CANCELLED'){await ref.ref.update({status:'cancelled',leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});}else if(attempts>=maxAttempts){await ref.ref.update({status:'dead',error:message,finishedAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});await db.collection('automation_dead_letters').doc(ref.id).set({...job,status:'dead',error:message,deadAt:now()},{merge:true});}else{const backoff=Number((await db.collection('module_workflows').doc(String(job.workflowId)).get()).data()?.retryPolicy?.backoffMs??30000);await ref.ref.update({status:'pending',error:message,nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+retryDelayMs(attempts,backoff)),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()})}}finally{await releaseConcurrency(String(job.companyId))}}
export const automationWorkerV2=onSchedule({schedule:'* * * * *',timeZone:'UTC',region:REGION,timeoutSeconds:540,memory:'512MiB'},async()=>{const pending=await db.collection('automation_jobs').where('status','==','pending').limit(MAX_JOBS_PER_TICK).get();const running=await db.collection('automation_jobs').where('status','==','running').limit(MAX_JOBS_PER_TICK).get();await Promise.all([...pending.docs,...running.docs].map(processOne));});
async function identity(request:{auth?:{uid:string;token:Record<string,unknown>}}){if(!request.auth)throw new HttpsError('unauthenticated','A autenticação é necessária.');const companyId=typeof request.auth.token.companyId==='string'?request.auth.token.companyId:'';if(!companyId)throw new HttpsError('permission-denied','Empresa não encontrada.');const member=await db.collection('companies').doc(companyId).collection('members').doc(request.auth.uid).get();if(!member.exists||member.data()?.status!=='active')throw new HttpsError('permission-denied','Membership inactiva.');return{companyId,uid:request.auth.uid,role:String(member.data()?.role??'viewer')}}
export const triggerAutomationEventV2=onCall({region:REGION},async request=>{const i=await identity(request);const schema=z.object({eventName:z.string().min(1).max(180),eventId:z.string().max(180).optional(),payload:z.record(z.unknown()).default({})});const p=schema.safeParse(request.data);if(!p.success)throw new HttpsError('invalid-argument','Evento inválido.');const s=await db.collection('module_automations').where('companyId','==',i.companyId).where('active','==',true).limit(500).get();const jobs:string[]=[];for(const a of s.docs){const d=a.data();const t=d.trigger as Record<string,unknown>|undefined;if(t?.type!=='event'||t.eventName!==p.data.eventName)continue;const w=await db.collection('module_workflows').doc(String(d.workflowId??'')).get();if(!w.exists||w.data()?.companyId!==i.companyId)continue;const id=`event_${a.id}_${p.data.eventId??Date.now()}_${i.uid}`.replace(/[^A-Za-z0-9_-]/g,'_');await db.collection('automation_jobs').doc(id).create({id,companyId:i.companyId,automationId:a.id,workflowId:w.id,workflowVersion:Number(w.data()?.version??1),trigger:'event',payload:{...p.data.payload,eventName:p.data.eventName,eventId:p.data.eventId??null},idempotencyKey:id,status:'pending',attempts:0,maxAttempts:Number(d.retryPolicy?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now()});jobs.push(id)}return{queued:jobs.length,jobIds:jobs}});
export const runAutomationNowV2=onCall({region:REGION},async request=>{const i=await identity(request);if(!['owner','admin','manager'].includes(i.role))throw new HttpsError('permission-denied','Sem permissão.');const p=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,180}$/),payload:z.record(z.unknown()).default({})}).safeParse(request.data);if(!p.success)throw new HttpsError('invalid-argument','Dados inválidos.');const a=await db.collection('module_automations').doc(p.data.id).get();if(!a.exists||a.data()?.companyId!==i.companyId||a.data()?.active!==true)throw new HttpsError('failed-precondition','Automação inexistente ou inactiva.');const d=a.data()??{};const w=await db.collection('module_workflows').doc(String(d.workflowId??'')).get();if(!w.exists||w.data()?.companyId!==i.companyId)throw new HttpsError('failed-precondition','Workflow inexistente.');const id=`manual_${a.id}_${Date.now()}_${i.uid}`;await db.collection('automation_jobs').doc(id).create({id,companyId:i.companyId,automationId:a.id,workflowId:w.id,workflowVersion:Number(w.data()?.version??1),trigger:'manual',payload:p.data.payload,idempotencyKey:id,status:'pending',attempts:0,maxAttempts:Number((d.retryPolicy as Record<string,unknown>|undefined)?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now()});return{queued:true,jobId:id,workflowVersion:Number(w.data()?.version??1)}});
