import * as admin from 'firebase-admin';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { onSchedule } from 'firebase-functions/v2/scheduler';
import { defineSecret } from 'firebase-functions/params';
import * as logger from 'firebase-functions/logger';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { executeGraph, GraphEdge, GraphNode, GraphResult, selectRoute, validateWorkflowGraph } from './automation-graph-core';
import { cronMatches, retryDelayMs } from './automation-cron-core';
import { generateGemini, sendEmail } from './automation-providers';

if (!admin.apps.length) admin.initializeApp();
const db=admin.firestore();
const REGION='africa-south1';
const MAX_JOBS_PER_TICK=20;
const MAX_ATTEMPTS=8;
const LEASE_MS=8*60*1000;
const DEFAULT_TIMEOUT_MS=120000;
const MAX_WAIT_MS=60000;
const RESEND_API_KEY=defineSecret('RESEND_API_KEY');
const GEMINI_API_KEY=defineSecret('GEMINI_API_KEY');
type Data=Record<string,unknown>;
type Job=Data&{id:string;companyId:string;automationId:string;workflowId:string;workflowVersion:number;attempts:number;maxAttempts:number;trigger:string;payload:Data};
type Step={id:string;type:'log'|'http'|'module.create'|'module.update'|'module.delete'|'condition'|'action';name?:string;config:Data};
type Automation=Data&{active?:boolean;trigger?:Data;workflowVersion?:number;concurrencyLimit?:number;rateLimitPerMinute?:number};
type Graph=Data&{nodes:GraphNode[];edges:GraphEdge[];viewport?:Data};
const MODULES:Record<string,string>={tasks:'module_tasks',projects:'projects',meetings:'module_meetings',campaigns:'module_campaigns',calendar:'module_calendar_events',workspaces:'module_workspaces',reports:'module_reports',integrations:'module_integrations','knowledge-base':'module_knowledge_articles'};
const StepSchema=z.object({id:z.string(),type:z.enum(['log','http','module.create','module.update','module.delete','condition','action']),name:z.string().optional(),config:z.record(z.unknown()).default({})});
const WorkflowSchema=z.object({name:z.string().min(1).max(180),description:z.string().optional(),active:z.boolean().default(true),executionTimeoutMs:z.number().int().min(1000).max(900000).default(DEFAULT_TIMEOUT_MS),retryPolicy:z.object({maxAttempts:z.number().int().min(1).max(20).default(5),backoffMs:z.number().int().min(1000).max(900000).default(30000)}).default({maxAttempts:5,backoffMs:30000}),graph:z.record(z.unknown()).optional(),steps:z.array(StepSchema).min(1).max(100)});
const GraphSchema=z.object({nodes:z.array(z.object({id:z.string(),type:z.string(),label:z.string().optional(),x:z.number().optional(),y:z.number().optional(),config:z.record(z.unknown()).optional()})).max(100),edges:z.array(z.object({id:z.string(),source:z.string(),target:z.string(),label:z.string().optional()})).max(200),viewport:z.record(z.unknown()).optional()});
function now(){return admin.firestore.Timestamp.now();}
function resolvePath(root:unknown,path:string){let cur:unknown=root;for(const part of path.split('.')){if(!cur||typeof cur!=='object')return undefined;cur=(cur as Data)[part];}return cur;}
function template(value:unknown,ctx:Data):unknown{if(typeof value==='string')return value.replace(/{{\s*([^}]+)\s*}}/g,(_,path:string)=>{const v=resolvePath(ctx,path.trim());return v==null?'':String(v);});if(Array.isArray(value))return value.map(v=>template(v,ctx));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Data).map(([k,v])=>[k,template(v,ctx)]));return value;}
function safeData(config:Data){const source=config.data&&typeof config.data==='object'&&!Array.isArray(config.data)?{...(config.data as Data)}:{};for(const key of ['id','companyId','ownerId','createdBy','updatedBy','createdAt','updatedAt','version','searchTitle'])delete source[key];return source;}
function contextFor(job:Job,results:Record<string,GraphResult>){return{payload:job.payload,job:{id:job.id,automationId:job.automationId,workflowId:job.workflowId,executionId:job.id},company:{id:job.companyId},steps:results};}
async function withTimeout<T>(promise:Promise<T>,ms:number){let timer:NodeJS.Timeout|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error('EXECUTION_TIMEOUT')),ms);})]);}finally{if(timer)clearTimeout(timer);}}
function receiptId(jobId:string,executionId:string,stepId:string){return`${jobId}:${executionId}:${stepId}`.replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,700);}
async function writeStepLog(runRef:admin.firestore.DocumentReference,jobId:string,stepId:string,patch:Data){await runRef.collection('steps').doc(stepId).set({jobId,stepId,...patch,updatedAt:now()},{merge:true});await runRef.collection('logs').add({jobId,stepId,...patch,createdAt:now()});}
async function notify(companyId:string,userId:string,title:string,body:string,entityType:string,entityId:string){if(!userId)return;const ref=db.collection('notifications').doc(userId).collection('items').doc(`${entityId}_${Date.now()}_${randomUUID().slice(0,8)}`);await ref.create({id:ref.id,companyId,userId,title,body,entityType,entityId,eventName:'automation.action',severity:'medium',category:'system',actionUrl:'/dashboard/inbox',read:false,createdAt:now(),metadata:{source:'automation-engine-v2'}});}
async function createApproval(companyId:string,job:Job,cfg:Data){const approverId=String(cfg.approverId??'');if(!approverId)throw new Error('APPROVER_REQUIRED');const approvalRef=db.collection('approvals').doc();const eventRef=db.collection('event_outbox').doc(`automation_approval_${approvalRef.id}`);await db.runTransaction(async tx=>{tx.create(approvalRef,{id:approvalRef.id,companyId,createdBy:'automation-worker',requesterId:String(cfg.requesterId??job.payload.userId??'automation-worker'),updatedBy:'automation-worker',title:String(cfg.title??'Aprovação automática'),description:String(cfg.description??''),entityType:String(cfg.entityType??'automation'),entityId:String(cfg.entityId??job.id),approverId,mode:String(cfg.mode??'single'),steps:Array.isArray(cfg.steps)?cfg.steps:[{id:'approval_1',approverId,status:'PENDING',index:0}],currentStep:0,state:'PENDING',status:'pending',metadata:{source:'automation-engine-v2',jobId:job.id},version:1,createdAt:now(),updatedAt:now()});tx.create(eventRef,{eventId:eventRef.id,companyId,eventName:'approval.requested',entityType:'approval',entityId:approvalRef.id,actorId:'automation-worker',occurredAt:now(),payload:{approvalId:approvalRef.id},metadata:{source:'automation-engine-v2'},schemaVersion:1,status:'pending',attempts:0,nextAttemptAt:now()});});return{id:approvalRef.id};}
async function executeAction(job:Job,executionId:string,config:Data,results:Record<string,GraphResult>):Promise<GraphResult>{const cfg=template(config,contextFor(job,results)) as Data;const op=String(cfg.operation??'');
if(op==='notify'){await notify(job.companyId,String(cfg.userId??job.payload.userId??''),String(cfg.title??'Automação'),String(cfg.body??''),String(cfg.entityType??'automation'),String(cfg.entityId??job.id));return{operation:op,status:'succeeded'};}
if(op==='email'){const deliveryRef=db.collection('notification_deliveries').doc(`${job.id}_${executionId}`);await deliveryRef.set({id:deliveryRef.id,companyId:job.companyId,channel:'email',to:cfg.to,subject:String(cfg.subject??''),body:String(cfg.html??cfg.text??cfg.body??''),status:'sending',provider:'resend',source:'automation',createdAt:now(),updatedAt:now()},{merge:true});try{const sent=await sendEmail(RESEND_API_KEY.value(),{to:cfg.to,subject:cfg.subject,html:cfg.html??cfg.body,text:cfg.text,from:cfg.from,replyTo:cfg.replyTo,headers:cfg.headers,idempotencyKey:`${job.companyId}:${job.id}:${executionId}:email`});await deliveryRef.set({status:'sent',providerId:sent.id,updatedAt:now()},{merge:true});return{operation:op,status:'sent',provider:'resend',providerId:sent.id};}catch(error){await deliveryRef.set({status:'failed',error:error instanceof Error?error.message:'EMAIL_FAILED',updatedAt:now()},{merge:true});throw error;}}
if(op==='ai'){const result=await generateGemini(GEMINI_API_KEY.value(),{prompt:String(cfg.prompt??''),model:cfg.model,systemInstruction:cfg.systemInstruction,temperature:cfg.temperature,maxOutputTokens:cfg.maxOutputTokens,responseMimeType:cfg.responseMimeType});const ref=db.collection('automation_ai_results').doc();await ref.create({id:ref.id,companyId:job.companyId,jobId:job.id,executionId,operation:op,model:result.model,text:String(result.text??''),usageMetadata:result.usageMetadata??null,createdAt:now()});return{operation:op,status:'succeeded',id:ref.id,model:result.model,text:result.text};}
if(op==='wait'){const ms=Math.min(MAX_WAIT_MS,Math.max(0,Number(cfg.ms??1000)));await new Promise(resolve=>setTimeout(resolve,ms));return{operation:op,waitedMs:ms};}
if(op==='condition'||op==='branch'){const actual=resolvePath(contextFor(job,results),String(cfg.field??''));const expected=cfg.value;const operator=String(cfg.operator??'equals');const valid=operator==='equals'?actual===expected:operator==='not_equals'?actual!==expected:operator==='contains'?String(actual??'').includes(String(expected??'')):operator==='greater_than'?Number(actual)>Number(expected):operator==='less_than'?Number(actual)<Number(expected):false;return{operation:op,valid,route:valid?'true':'false',value:actual};}
if(op==='join')return{operation:op,joined:true};
if(op==='request.approval')return createApproval(job.companyId,job,cfg);
if(op==='escalate'){const ids=Array.isArray(cfg.userIds)?cfg.userIds.map(String):[];await Promise.all(ids.map(uid=>notify(job.companyId,uid,String(cfg.title??'Escalação'),String(cfg.body??'Uma automação requer atenção.'),'automation',job.id)));return{operation:op,recipients:ids.length};}
if(op==='run.workflow'){const workflowId=String(cfg.workflowId??'');const w=await db.collection('module_workflows').doc(workflowId).get();if(!w.exists||w.data()?.companyId!==job.companyId)throw new Error('WORKFLOW_NOT_FOUND');const id=`chain_${job.id}_${executionId}_${Date.now()}`;await db.collection('automation_jobs').doc(id).create({id,companyId:job.companyId,automationId:String(cfg.automationId??''),workflowId,workflowVersion:Number(w.data()?.version??1),trigger:'workflow',payload:job.payload,idempotencyKey:id,status:'pending',attempts:0,maxAttempts:Number((w.data()?.retryPolicy as Data|undefined)?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now(),parentExecutionId:executionId});return{operation:op,jobId:id};}
if(['webhook','integration','http'].includes(op)){const url=String(cfg.url??'');if(!url.startsWith('https://'))throw new Error('HTTP_URL_NOT_ALLOWED');const parsed=new URL(url);if(['localhost','127.0.0.1','0.0.0.0','::1'].includes(parsed.hostname))throw new Error('HTTP_HOST_NOT_ALLOWED');const headers=cfg.headers&&typeof cfg.headers==='object'?Object.fromEntries(Object.entries(cfg.headers as Data).map(([k,v])=>[k,String(v)])):{};headers['Idempotency-Key']=`${job.companyId}:${job.id}:${executionId}`;const method=String(cfg.method??'POST').toUpperCase();const response=await fetch(url,{method,headers,body:method==='GET'||method==='HEAD'?undefined:JSON.stringify(cfg.body??job.payload),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`HTTP_${response.status}`);return{operation:op,status:response.status};}
const creates:Record<string,string>={'create.task':'tasks','create.project':'projects','create.meeting':'meetings','create.record':String(cfg.module??'')};if(creates[op]){const collection=MODULES[creates[op]];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const id=`automation_${job.id.slice(0,36)}_${executionId.slice(0,16)}`;await db.collection(collection).doc(id).create({id,companyId:job.companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...safeData(cfg)});return{operation:op,id};}
if(op==='generate.document'){const ref=db.collection('module_reports').doc();await ref.create({id:ref.id,companyId:job.companyId,title:String(cfg.title??'Generated document'),content:String(cfg.content??''),createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,source:'automation'});return{operation:op,id:ref.id};}
if(op==='update.record'||op==='assign.user'||op==='assign.team'||op==='delete.record'){const collection=MODULES[String(cfg.module??'')];const id=String(cfg.id??'');if(!collection||!id)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(id);const s=await ref.get();if(op==='delete.record'){if(s.exists&&s.data()?.companyId===job.companyId)await ref.delete();return{operation:op,id};}if(!s.exists||s.data()?.companyId!==job.companyId)throw new Error('TARGET_NOT_FOUND');const patch=op==='assign.user'?{assigneeId:String(cfg.userId??''),ownerId:String(cfg.userId??'')}:op==='assign.team'?{teamId:String(cfg.teamId??'')}:safeData(cfg);await ref.update({...patch,updatedBy:'automation-worker',updatedAt:now()});return{operation:op,id};}
throw new Error('ACTION_NOT_SUPPORTED');}
async function executeStep(job:Job,step:Step,executionId:string,results:Record<string,GraphResult>):Promise<GraphResult>{const ref=db.collection('automation_step_receipts').doc(receiptId(job.id,executionId,step.id));const prior=await ref.get();if(prior.exists&&prior.data()?.status==='completed')return(prior.data()?.result??{}) as GraphResult;const result=step.type==='log'?{message:String(step.config.message??step.name??'')}:step.type==='condition'?await executeAction(job,executionId,{operation:'condition',...step.config},results):step.type==='http'?await executeAction(job,executionId,{operation:'http',...step.config},results):step.type==='action'?await executeAction(job,executionId,step.config,results):await executeModuleStep(job,step);results[step.id]=result;await ref.set({companyId:job.companyId,jobId:job.id,executionId,stepId:step.id,status:'completed',result,mutationKey:`${job.companyId}:${job.id}:${executionId}:${step.id}`,createdAt:now(),updatedAt:now()},{merge:false});return result;}
async function executeModuleStep(job:Job,step:Step):Promise<GraphResult>{const cfg=step.config as Data;const collection=MODULES[String(cfg.module??'')];if(!collection)throw new Error('MODULE_NOT_ALLOWED');const data=safeData(cfg);if(step.type==='module.create'){const id=`job_${job.id.slice(0,40)}_${step.id}`;await db.collection(collection).doc(id).set({id,companyId:job.companyId,createdBy:'automation-worker',updatedBy:'automation-worker',createdAt:now(),updatedAt:now(),version:1,...data});return{id};}const id=String(cfg.id??'');if(!id)throw new Error('INVALID_TARGET');const ref=db.collection(collection).doc(id);const target=await ref.get();if(!target.exists||target.data()?.companyId!==job.companyId)throw new Error('TARGET_NOT_FOUND');if(step.type==='module.update'){await ref.update({...data,updatedBy:'automation-worker',updatedAt:now()});return{id};}await ref.delete();return{id};}
async function executeGraphWorkflow(job:Job,graph:Graph,runRef:admin.firestore.DocumentReference,timeoutMs:number){const issues=validateWorkflowGraph(graph.nodes,graph.edges);if(issues.length)throw new Error(`GRAPH_INVALID:${issues.join('|')}`);const deadline=Date.now()+timeoutMs;return executeGraph({nodes:graph.nodes,edges:graph.edges,isStartNode:node=>{if(!node.type.startsWith('trigger.'))return false;if(['manual','replay','workflow'].includes(job.trigger))return true;const map:Record<string,string>={'trigger.record.created':'record.created','trigger.record.updated':'record.updated','trigger.record.deleted':'record.deleted','trigger.status.changed':'record.status.changed','trigger.form.submitted':'form.submitted','trigger.approval.requested':'approval.requested','trigger.approval.completed':'approval.completed','trigger.meeting.ended':'meeting.ended','trigger.document.changed':'document.changed','trigger.campaign.approved':'campaign.approved','trigger.webhook':'webhook.received','trigger.api':'api.called'};const cfg=node.config??{};return String((cfg as Data).eventName??map[node.type]??node.type)===job.trigger;},isJoinNode:node=>node.type==='action.join',joinExpected:node=>{const configured=Number((node.config as Data|undefined)?.joinExpected??0);if(configured>0)return configured;const incoming=graph.edges.filter(e=>e.target===node.id).length;return Math.max(1,incoming);},route:(node,result,edges)=>node.type==='action.condition'||node.type==='action.branch'?selectRoute(edges,result.route):edges,runId:job.id,execute:async(node,ctx)=>{if(Date.now()>deadline)throw new Error('EXECUTION_TIMEOUT');const state=await db.collection('automation_jobs').doc(job.id).get();if(String(state.data()?.status)==='cancelled')throw new Error('EXECUTION_CANCELLED');if(node.type.startsWith('trigger.')){await writeStepLog(runRef,job.id,node.id,{status:'succeeded',name:node.label??node.id,result:{trigger:job.trigger},finishedAt:now()});return{trigger:job.trigger};}const step:Step={id:node.id,type:'action',name:node.label,config:{operation:node.type.replace(/^action\./,''),...(node.config??{})}};const started=Date.now();await writeStepLog(runRef,job.id,node.id,{status:'running',name:node.label??node.id});try{const result=await withTimeout(executeStep(job,step,job.id,ctx.results),Math.max(1000,deadline-Date.now()));await writeStepLog(runRef,job.id,node.id,{status:'succeeded',result,durationMs:Date.now()-started,finishedAt:now()});return result;}catch(error){await writeStepLog(runRef,job.id,node.id,{status:'failed',error:error instanceof Error?error.message:'STEP_FAILED',durationMs:Date.now()-started,finishedAt:now()});throw error;}}});}
async function executeJob(job:Job){const snap=await db.collection('module_workflows').doc(job.workflowId).collection('versions').doc(String(job.workflowVersion)).get();if(!snap.exists)throw new Error('WORKFLOW_VERSION_NOT_FOUND');const parsed=WorkflowSchema.safeParse(snap.data());if(!parsed.success)throw new Error('WORKFLOW_INVALID');const runRef=db.collection('automation_runs').doc(job.id);await runRef.set({id:job.id,jobId:job.id,automationId:job.automationId,workflowId:job.workflowId,workflowVersion:job.workflowVersion,companyId:job.companyId,status:'running',attempts:job.attempts,trigger:job.trigger,payload:job.payload,startedAt:now(),updatedAt:now()},{merge:true});try{if(parsed.data.graph){await executeGraphWorkflow(job,GraphSchema.parse(parsed.data.graph) as Graph,runRef,parsed.data.executionTimeoutMs);}else{const results:Record<string,GraphResult>={};for(const step of parsed.data.steps as Step[]){const state=await db.collection('automation_jobs').doc(job.id).get();if(String(state.data()?.status)==='cancelled')throw new Error('EXECUTION_CANCELLED');await executeStep(job,step,job.id,results);}}await runRef.set({status:'succeeded',finishedAt:now(),updatedAt:now()},{merge:true});await db.collection('automation_jobs').doc(job.id).update({status:'succeeded',leaseUntil:admin.firestore.FieldValue.delete(),finishedAt:now(),updatedAt:now()});}catch(error){const message=error instanceof Error?error.message:'EXECUTION_FAILED';const cancelled=message==='EXECUTION_CANCELLED';const retry=!cancelled&&job.attempts<job.maxAttempts;const next=retry?admin.firestore.Timestamp.fromMillis(Date.now()+retryDelayMs(job.attempts)):null;await runRef.set({status:cancelled?'cancelled':retry?'failed':'dead',error:message,finishedAt:now(),nextAttemptAt:next,updatedAt:now()},{merge:true});if(retry)await db.collection('automation_jobs').doc(job.id).update({status:'pending',error:message,nextAttemptAt:next,leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});else{await db.collection('automation_jobs').doc(job.id).update({status:cancelled?'cancelled':'dead',error:message,finishedAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});if(!cancelled)await db.collection('automation_dead_letters').doc(job.id).set({...job,error:message,createdAt:now()});}}}
async function claimJob(ref:admin.firestore.DocumentReference){return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)return null;const d=snap.data()??{};const status=String(d.status??'');const next=d.nextAttemptAt instanceof admin.firestore.Timestamp?d.nextAttemptAt.toMillis():0;const lease=d.leaseUntil instanceof admin.firestore.Timestamp?d.leaseUntil.toMillis():0;if(['succeeded','dead','cancelled'].includes(status)||(status==='running'&&lease>Date.now())||(status==='pending'&&next>Date.now()))return null;const attempts=Number(d.attempts??0)+1;tx.update(ref,{status:'running',attempts,leaseUntil:admin.firestore.Timestamp.fromMillis(Date.now()+LEASE_MS),updatedAt:now()});return{...d,id:snap.id,companyId:String(d.companyId??''),automationId:String(d.automationId??''),workflowId:String(d.workflowId??''),workflowVersion:Number(d.workflowVersion??1),attempts,maxAttempts:Number(d.maxAttempts??MAX_ATTEMPTS),trigger:String(d.trigger??'manual'),payload:d.payload&&typeof d.payload==='object'&&!Array.isArray(d.payload)?d.payload as Data:{}} as Job;});}
async function acquireLimit(automationId:string,concurrencyLimit:number,rateLimitPerMinute:number){const minute=Math.floor(Date.now()/60000);const counterRef=db.collection('automation_concurrency').doc(automationId);const rateRef=db.collection('automation_rate_limits').doc(`${automationId}_${minute}`);return db.runTransaction(async tx=>{const counter=await tx.get(counterRef);const rate=await tx.get(rateRef);const active=Number(counter.data()?.active??0);const count=Number(rate.data()?.count??0);if(active>=concurrencyLimit||count>=rateLimitPerMinute)return false;tx.set(counterRef,{automationId,active:active+1,updatedAt:now()},{merge:true});tx.set(rateRef,{automationId,minute,count:count+1,updatedAt:now()},{merge:true});return true;});}
async function releaseLimit(automationId:string){const ref=db.collection('automation_concurrency').doc(automationId);await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)return;tx.set(ref,{active:Math.max(0,Number(s.data()?.active??0)-1),updatedAt:now()},{merge:true});});}
async function enqueueJob(automationId:string,payload:Data,trigger:string,idempotencyKey:string){const automation=await db.collection('module_automations').doc(automationId).get();if(!automation.exists||automation.data()?.active!==true)throw new Error('AUTOMATION_NOT_ACTIVE');const a=automation.data()??{};const workflowId=String(a.workflowId??'');const workflow=await db.collection('module_workflows').doc(workflowId).get();if(!workflow.exists||workflow.data()?.active===false)throw new Error('WORKFLOW_NOT_ACTIVE');const jobRef=db.collection('automation_jobs').doc(idempotencyKey);await jobRef.create({id:idempotencyKey,companyId:String(a.companyId??''),automationId,workflowId,workflowVersion:Number(a.workflowVersion??workflow.data()?.version??1),trigger,payload,idempotencyKey,status:'pending',attempts:0,maxAttempts:Number((workflow.data()?.retryPolicy as Data|undefined)?.maxAttempts??5),createdAt:now(),updatedAt:now(),nextAttemptAt:now()});return{id:idempotencyKey,automationId,workflowId};}
async function recoverExpiredJobs(){const snap=await db.collection('automation_jobs').where('status','==','running').limit(MAX_JOBS_PER_TICK).get();await Promise.all(snap.docs.map(async doc=>{const lease=doc.data().leaseUntil;const ms=lease instanceof admin.firestore.Timestamp?lease.toMillis():0;if(ms&&ms<Date.now())await doc.ref.update({status:'pending',nextAttemptAt:now(),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now(),error:'LEASE_EXPIRED'});}));}
async function scheduledAutomations(){const snap=await db.collection('module_automations').where('active','==',true).limit(500).get();const date=new Date();for(const doc of snap.docs){const trigger=(doc.data().trigger??{}) as Data;if(trigger.type!=='cron')continue;if(!cronMatches(String(trigger.cron??''),date,String(trigger.timezone??'UTC')))continue;const key=`cron_${doc.id}_${new Date(Math.floor(Date.now()/60000)*60000).toISOString()}`;try{await enqueueJob(doc.id,{scheduledAt:date.toISOString()},'cron',key);}catch(error){if((error as {code?:number}).code!==6)logger.warn('cron enqueue skipped',{automationId:doc.id,error});}}}
async function drainJobs(){const snap=await db.collection('automation_jobs').where('status','==','pending').limit(MAX_JOBS_PER_TICK).get();await Promise.all(snap.docs.map(async doc=>{const job=await claimJob(doc.ref);if(!job)return;const aSnap=await db.collection('module_automations').doc(job.automationId).get();const automation=aSnap.data() as Automation|undefined;if(!automation||automation.active===false){await doc.ref.update({status:'cancelled',error:'AUTOMATION_NOT_ACTIVE',updatedAt:now()});return;}const acquired=await acquireLimit(job.automationId,Number(automation.concurrencyLimit??5),Number(automation.rateLimitPerMinute??100));if(!acquired){await doc.ref.update({status:'pending',nextAttemptAt:admin.firestore.Timestamp.fromMillis(Date.now()+15000),leaseUntil:admin.firestore.FieldValue.delete(),updatedAt:now()});return;}try{await executeJob(job);}catch(error){logger.error('terminal automation failure',{jobId:job.id,error});}finally{await releaseLimit(job.automationId);}}));}
export const automationWorkerV2=onSchedule({schedule:'every 1 minutes',timeZone:'UTC',region:REGION,secrets:[RESEND_API_KEY,GEMINI_API_KEY]},async()=>{await recoverExpiredJobs();await scheduledAutomations();await drainJobs();});
export const triggerAutomationEventV2=onCall({region:REGION,secrets:[RESEND_API_KEY,GEMINI_API_KEY]},async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Autenticação necessária.');const eventName=String(request.data?.eventName??'');if(!eventName)throw new HttpsError('invalid-argument','eventName é obrigatório.');const companyId=String(request.auth.token.companyId??'');const snap=await db.collection('module_automations').where('active','==',true).limit(200).get();const queued:Data[]=[];for(const doc of snap.docs){const a=doc.data();const trigger=(a.trigger??{}) as Data;if(trigger.type!=='event'||String(trigger.eventName??'')!==eventName||String(a.companyId??'')!==companyId)continue;const filter=trigger.filter&&typeof trigger.filter==='object'?trigger.filter as Data:{};const payload=(request.data?.payload&&typeof request.data.payload==='object'?request.data.payload:{}) as Data;if(Object.entries(filter).some(([k,v])=>resolvePath(payload,k)!==v))continue;const key=`event_${doc.id}_${String(request.data?.eventId??randomUUID())}`;try{queued.push(await enqueueJob(doc.id,payload,eventName,key));}catch(error){logger.warn('event enqueue skipped',{automationId:doc.id,error});}}return{queued};});
export const runAutomationNowV2=onCall({region:REGION,secrets:[RESEND_API_KEY,GEMINI_API_KEY]},async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Autenticação necessária.');const automationId=String(request.data?.automationId??'');if(!automationId)throw new HttpsError('invalid-argument','automationId é obrigatório.');const automation=await db.collection('module_automations').doc(automationId).get();if(!automation.exists||automation.data()?.companyId!==String(request.auth.token.companyId??''))throw new HttpsError('not-found','Automation não encontrada.');const payload=request.data?.payload&&typeof request.data.payload==='object'?request.data.payload:{};return enqueueJob(automationId,payload as Data,'manual',`manual_${automationId}_${request.auth.uid}_${randomUUID()}`);});
