export const PERMISSIONS = {
  PLATFORM_ADMIN: 'platform.admin',
  USERS_READ: 'users.read',
  USERS_MANAGE: 'users.manage',
  DEPARTMENTS_READ: 'departments.read',
  DEPARTMENTS_MANAGE: 'departments.manage',
  TEAMS_READ: 'teams.read',
  TEAMS_MANAGE: 'teams.manage',
  COMPANY_READ: 'company.read',
  COMPANY_CREATE: 'company.create',
  COMPANY_UPDATE: 'company.update',
  COMPANY_DELETE: 'company.delete',
  COMPANY_MANAGE: 'company.manage',
  COMPANY_ADMIN: 'company.admin',
  COMPANY_EXPORT: 'company.export',
  COMPANY_SHARE: 'company.share',
  CHAT_READ: 'chat.read',
  CHAT_WRITE: 'chat.write',
  CHAT_MODERATE: 'chat.moderate',
  DOCUMENTS_READ: 'documents.read',
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_EDIT: 'documents.edit',
  DOCUMENTS_SHARE: 'documents.share',
  FILES_READ: 'files.read',
  FILES_WRITE: 'files.write',
  FINANCE_READ: 'finance.read',
  FINANCE_MANAGE: 'finance.manage',
  AUDIT_READ: 'audit.read',
  OPERATIONS_READ: 'operations.read',
  OPERATIONS_MANAGE: 'operations.manage',
  MARKETING_READ: 'marketing.read',
  MARKETING_MANAGE: 'marketing.manage',
  KNOWLEDGE_READ: 'knowledge.read',
  KNOWLEDGE_MANAGE: 'knowledge.manage',
  AUTOMATION_READ: 'automation.read',
  AUTOMATION_MANAGE: 'automation.manage',
  REPORTING_READ: 'reporting.read',
  REPORTING_MANAGE: 'reporting.manage',
  FORMS_READ: 'forms.read',
  FORMS_MANAGE: 'forms.manage',
  APPROVALS_READ: 'approvals.read',
  APPROVALS_MANAGE: 'approvals.manage',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
export type MembershipRole = 'owner' | 'admin' | 'manager' | 'member' | 'viewer';

export const ROLE_PERMISSIONS: Record<MembershipRole, readonly Permission[]> = {
  owner: Object.values(PERMISSIONS),
  admin: Object.values(PERMISSIONS),
  manager: [
    PERMISSIONS.USERS_READ, PERMISSIONS.DEPARTMENTS_READ, PERMISSIONS.TEAMS_READ, PERMISSIONS.COMPANY_READ,
    PERMISSIONS.CHAT_READ, PERMISSIONS.CHAT_WRITE, PERMISSIONS.CHAT_MODERATE, PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_EDIT, PERMISSIONS.DOCUMENTS_SHARE, PERMISSIONS.FILES_READ,
    PERMISSIONS.FILES_WRITE, PERMISSIONS.AUDIT_READ, PERMISSIONS.OPERATIONS_READ, PERMISSIONS.OPERATIONS_MANAGE,
    PERMISSIONS.MARKETING_READ, PERMISSIONS.MARKETING_MANAGE, PERMISSIONS.KNOWLEDGE_READ, PERMISSIONS.KNOWLEDGE_MANAGE,
    PERMISSIONS.AUTOMATION_READ, PERMISSIONS.AUTOMATION_MANAGE, PERMISSIONS.REPORTING_READ, PERMISSIONS.REPORTING_MANAGE,
    PERMISSIONS.FORMS_READ, PERMISSIONS.FORMS_MANAGE, PERMISSIONS.APPROVALS_READ, PERMISSIONS.APPROVALS_MANAGE,
  ],
  member: [
    PERMISSIONS.DEPARTMENTS_READ, PERMISSIONS.TEAMS_READ, PERMISSIONS.COMPANY_READ, PERMISSIONS.CHAT_READ, PERMISSIONS.CHAT_WRITE,
    PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.DOCUMENTS_CREATE, PERMISSIONS.DOCUMENTS_EDIT, PERMISSIONS.DOCUMENTS_SHARE,
    PERMISSIONS.FILES_READ, PERMISSIONS.FILES_WRITE, PERMISSIONS.OPERATIONS_READ, PERMISSIONS.OPERATIONS_MANAGE,
    PERMISSIONS.MARKETING_READ, PERMISSIONS.KNOWLEDGE_READ, PERMISSIONS.KNOWLEDGE_MANAGE, PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_MANAGE, PERMISSIONS.REPORTING_READ, PERMISSIONS.FORMS_READ, PERMISSIONS.FORMS_MANAGE,
    PERMISSIONS.APPROVALS_READ, PERMISSIONS.APPROVALS_MANAGE,
  ],
  viewer: [
    PERMISSIONS.DEPARTMENTS_READ, PERMISSIONS.TEAMS_READ, PERMISSIONS.COMPANY_READ, PERMISSIONS.CHAT_READ,
    PERMISSIONS.DOCUMENTS_READ, PERMISSIONS.FILES_READ, PERMISSIONS.OPERATIONS_READ, PERMISSIONS.MARKETING_READ,
    PERMISSIONS.KNOWLEDGE_READ, PERMISSIONS.AUTOMATION_READ, PERMISSIONS.REPORTING_READ, PERMISSIONS.FORMS_READ,
    PERMISSIONS.APPROVALS_READ,
  ],
};

export function roleHasPermission(role: MembershipRole, permission: Permission, explicit: readonly string[] = []): boolean {
  return explicit.includes(permission) || ROLE_PERMISSIONS[role].includes(permission);
}
