import 'server-only';
import crypto from 'node:crypto';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { writeAuditEvent } from '@/server/repositories/audit';

export type OryonAppStatus='draft'|'active'|'suspended'|'revoked';
export type OryonAppManifest={name:string;description?:string;permissions:string[];events:string[];actions:string[];uiExtensions?:Array<Record<string,unknown>>;redirectUris?:string[]} & Record<string, unknown>;
const safeId=/^[A-Za-z0-9_-]{1,180}$/;
const encryptKey=()=>{const raw=process.env.ORYON_INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY_MISSING');const key=Buffer.from(raw,'base64');if(key.length!==32)throw new Error('INTEGRATION_ENCRYPTION_KEY_INVALID');return key;};
const encrypt=(s:string)=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',encryptKey(),iv);const x=Buffer.concat([c.update(s,'utf8'),c.final()]);return{ciphertext:x.toString('base64'),iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64')};};
const EVENTS=['entity.created','entity.updated','entity.deleted','approval.approved','approval.rejected','workflow.failed','meeting.ended','campaign.approved','incident.created'];
const ACTIONS=['create_task','update_task','request_approval','run_workflow','create_report','send_notification'];
export async function registerOryonApp(input:OryonAppManifest){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const name=input.name?.trim().slice(0,180);if(!name||!Array.isArray(input.permissions))throw new Error('INVALID_APP');const permissions=Array.from(new Set(input.permissions)).slice(0,40);const events=Array.from(new Set(input.events??[])).filter(x=>EVENTS.includes(x)).slice(0,40);const actions=Array.from(new Set(input.actions??[])).filter(x=>ACTIONS.includes(x)).slice(0,40);const ref=getAdminDb().collection('oryon_apps').doc();const clientId=`oryon_${ref.id}`;const clientSecret=crypto.randomBytes(36).toString('base64url');await ref.create({id:ref.id,companyId:identity.companyId,name,description:String(input.description??'').slice(0,3000),status:'draft',clientId,permissions,events,actions,uiExtensions:Array.isArray(input.uiExtensions)?input.uiExtensions.slice(0,20):[],redirectUris:Array.isArray(input.redirectUris)?input.redirectUris.filter(Boolean).slice(0,20):[],createdBy:identity.uid,createdAt:Timestamp.now(),updatedAt:Timestamp.now()});await getAdminDb().collection('oryon_app_secrets').doc(ref.id).create({companyId:identity.companyId,appId:ref.id,secret:encrypt(clientSecret),createdAt:Timestamp.now()});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'app.register',resourceType:'integration',resourceId:ref.id,metadata:{permissions,events,actions}});return{id:ref.id,clientId,clientSecret};}
export async function listOryonApps(){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const s=await getAdminDb().collection('oryon_apps').where('companyId','==',identity.companyId).limit(200).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function updateOryonApp(id:string,input:Partial<OryonAppManifest>&{status?:OryonAppStatus}){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);if(!safeId.test(id))throw new Error('INVALID_ID');const ref=getAdminDb().collection('oryon_apps').doc(id);const s=await ref.get();if(!s.exists||s.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');const patch:Record<string,unknown>={updatedAt:Timestamp.now(),updatedBy:identity.uid};const editableKeys:Array<keyof OryonAppManifest|'status'>=['name','description','permissions','events','actions','uiExtensions','redirectUris','status'];for(const key of editableKeys)if(key in input)patch[key]=input[key];await ref.update(patch);return{id,...patch};}
export function getAppCatalog(){return{events:EVENTS,actions:ACTIONS};}
export async function createAppWebhookSubscription(appId:string,eventNames:string[],targetUrl:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);if(!safeId.test(appId))throw new Error('INVALID_ID');try{const url=new URL(targetUrl);if(url.protocol!=='https:')throw new Error('HTTPS_REQUIRED');}catch(error){throw new Error(error instanceof Error?error.message:'INVALID_URL');}const ref=getAdminDb().collection('oryon_app_webhooks').doc();await ref.create({id:ref.id,companyId:identity.companyId,appId,eventNames:Array.from(new Set(eventNames)).filter(x=>EVENTS.includes(x)).slice(0,30),targetUrl,state:'active',createdAt:Timestamp.now(),updatedAt:Timestamp.now()});return ref.id;}
export async function revokeOryonApp(id:string){return updateOryonApp(id,{status:'revoked'});}
