import 'server-only';

import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requireIdentity, requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { writeAuditEvent } from '@/server/repositories/audit';

export type WhiteboardObjectType='note'|'shape'|'person'|'project'|'task'|'workflow'|'meeting'|'document'|'image'|'text';
export type WhiteboardObject={id:string;type:WhiteboardObjectType;x:number;y:number;w:number;h:number;rotation?:number;text?:string;style?:Record<string,unknown>;refType?:string;refId?:string};

export async function listWhiteboards(){const identity=await requirePermission(PERMISSIONS.OPERATIONS_READ);const snap=await getAdminDb().collection('whiteboards').where('companyId','==',identity.companyId).orderBy('updatedAt','desc').limit(50).get();return snap.docs.map(doc=>({id:doc.id,...doc.data()}));}
export async function getWhiteboard(id:string){const identity=await requirePermission(PERMISSIONS.OPERATIONS_READ);const snap=await getAdminDb().collection('whiteboards').doc(id).get();if(!snap.exists||snap.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');return{id:snap.id,...snap.data()};}
export async function saveWhiteboard(input:{id?:string;name:string;objects:WhiteboardObject[];edges?:Array<{id:string;source:string;target:string;label?:string}>;viewport?:{x:number;y:number;zoom:number}}){const identity=await requirePermission(PERMISSIONS.OPERATIONS_MANAGE);if(input.objects.length>300)throw new Error('WHITEBOARD_TOO_LARGE');const ref=input.id?getAdminDb().collection('whiteboards').doc(input.id):getAdminDb().collection('whiteboards').doc();if(input.id){const current=await ref.get();if(!current.exists||current.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');}await ref.set({id:ref.id,companyId:identity.companyId,name:input.name.trim().slice(0,180),objects:input.objects,edges:(input.edges??[]).slice(0,500),viewport:input.viewport??{x:0,y:0,zoom:1},updatedAt:Timestamp.now(),updatedBy:identity.uid,createdAt:(await ref.get()).data()?.createdAt??Timestamp.now(),createdBy:(await ref.get()).data()?.createdBy??identity.uid,version:FieldValue.increment(1)},{merge:true});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'whiteboard.save',resourceType:'whiteboard',resourceId:ref.id,metadata:{objects:input.objects.length}});return getWhiteboard(ref.id);}

export async function createClip(input:{title?:string;cloudFileId?:string;storagePath?:string;durationMs?:number;transcript?:string;summary?:string;sourceType?:'screen'|'webcam'|'screen+webcam'|'voice'}){const identity=await requirePermission(PERMISSIONS.OPERATIONS_MANAGE);const ref=getAdminDb().collection('module_clips').doc();await ref.create({id:ref.id,companyId:identity.companyId,title:String(input.title??'Clip').trim().slice(0,240),cloudFileId:input.cloudFileId??null,storagePath:input.storagePath??null,durationMs:Math.max(0,Number(input.durationMs??0)),transcript:String(input.transcript??'').slice(0,50000),summary:String(input.summary??'').slice(0,10000),sourceType:input.sourceType??'screen',createdBy:identity.uid,updatedBy:identity.uid,createdAt:Timestamp.now(),updatedAt:Timestamp.now(),version:1});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'clip.create',resourceType:'clip',resourceId:ref.id});return{id:ref.id,...(await ref.get()).data()};}
export async function listClips(){const identity=await requirePermission(PERMISSIONS.OPERATIONS_READ);const snap=await getAdminDb().collection('module_clips').where('companyId','==',identity.companyId).orderBy('createdAt','desc').limit(100).get();return snap.docs.map(doc=>({id:doc.id,...doc.data()}));}
