import 'server-only';

import { FieldValue } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import type { AuthenticatedIdentity } from '@/server/authorization';

export const BET_DEPARTMENTS = [
  ['marketing', 'Marketing'], ['finance', 'Finance'], ['hr', 'HR'], ['it', 'IT'], ['operations', 'Operations'], ['compliance', 'Compliance'], ['security', 'Security'],
  ['trading', 'Trading & Sportsbook'], ['payments', 'Payments & Treasury'], ['risk', 'Risk & Fraud'], ['responsible-gaming', 'Responsible Gaming'], ['crm-vip', 'CRM & VIP'],
  ['customer-support', 'Customer Support'], ['product', 'Product'], ['data-bi', 'Data & BI'], ['legal', 'Legal'], ['affiliate', 'Affiliates & Partnerships'], ['procurement', 'Procurement'], ['strategy', 'Strategy & Executive'],
] as const;

const names = ['Ana Mucavel','Carlos Matola','Marta Chissano','João Tembe','Elisa Nhantumbo','Ricardo Sitoe','Paulo Macamo','Sara Bila','Daniel Mussa','Lídia Cossa','Nelson Muianga','Teresa Zandamela','Filipe Manjate','Rita Massango','Edson Chivambo','Cláudia Nhamatanda','Bruno Langa','Mónica Matusse','Tomás Balói','Inês Mabote','Arlindo Mabunda','Carla Uamusse','Dário Cossa','Helena Massingue','Jorge Mahumane','Sílvia Nhalungo','Abel Macuácua','Nádia Nhaca','Vasco Mavume','Célia Mucavele','Henrique Sitoe','Joana Matola','Miguel Chongo','Natércia Cuambe','Armando Bambo','Ema Matusse','Gerson Vilanculos','Laura Bila','Mário Mandlate','Yara Salimo'];
const iso = (daysFromNow: number, hour: number) => { const d = new Date(); d.setDate(d.getDate() + daysFromNow); d.setHours(hour, 0, 0, 0); return d.toISOString(); };
const batchSet = async (collection: string, rows: Record<string, unknown>[]) => { const db = getAdminDb(); for (let i = 0; i < rows.length; i += 450) { const batch = db.batch(); rows.slice(i, i + 450).forEach((row) => batch.set(db.collection(collection).doc(String(row.id)), row, { merge: true })); await batch.commit(); } };

export async function ensureDemoData(identity: AuthenticatedIdentity): Promise<void> {
  const db = getAdminDb();
  const marker = db.collection('companies').doc(identity.companyId).collection('system').doc('demo-seed');
  const current = await marker.get();
  if (current.exists && Number(current.data()?.version) >= 4) return;
  const ts = FieldValue.serverTimestamp();

  const departments = BET_DEPARTMENTS.map(([slug, name], i) => ({ id: `demo-dept-${slug}`, companyId: identity.companyId, name, slug, description: `Área de ${name.toLowerCase()} da operação Txuna Bet.`, status: 'active', budget: 450000 + i * 42000, memberCount: 0, projects: 0, goals: ['Melhorar eficiência operacional','Reduzir SLA e incidentes','Aumentar qualidade e controlo'], createdAt: ts, updatedAt: ts }));
  await batchSet('departments', departments);

  const users = names.map((name, i) => { const [slug] = BET_DEPARTMENTS[i % BET_DEPARTMENTS.length]; const uid = `demo-user-${String(i + 1).padStart(3, '0')}`; return { id: uid, uid, companyId: identity.companyId, email: `${name.toLowerCase().replace(/[^a-z0-9]+/g, '.')}@txunabet.com`, displayName: name, role: i < 19 ? 'manager' : 'member', departmentId: `demo-dept-${slug}`, departmentIds: [slug], status: 'active', mfaRequired: true, photoURL: null, createdAt: ts, updatedAt: ts }; });
  const profileBatch = db.batch(); profileBatch.set(db.collection('users').doc(identity.uid), { uid: identity.uid, companyId: identity.companyId, email: identity.email ?? 'admin@txunabet.com', displayName: 'Administrador Txuna Bet', role: identity.role, status: 'active', mfaRequired: true, createdAt: ts, updatedAt: ts }, { merge: true }); users.forEach((u) => profileBatch.set(db.collection('users').doc(String(u.uid)), u, { merge: true })); await profileBatch.commit();

  const memberBatch = db.batch(); memberBatch.set(db.collection('companies').doc(identity.companyId).collection('members').doc(identity.uid), { userId: identity.uid, companyId: identity.companyId, role: identity.role, permissions: [], departmentIds: BET_DEPARTMENTS.slice(0, 7).map(([slug]) => slug), status: 'active', createdAt: ts, updatedAt: ts }, { merge: true }); users.forEach((u, i) => memberBatch.set(db.collection('companies').doc(identity.companyId).collection('members').doc(String(u.uid)), { userId: u.uid, companyId: identity.companyId, role: i < 8 ? 'manager' : 'member', permissions: [], departmentIds: u.departmentIds, status: 'active', createdAt: ts, updatedAt: ts }, { merge: true })); await memberBatch.commit();

  const common = { companyId: identity.companyId, createdBy: identity.uid, updatedBy: identity.uid, createdAt: ts, updatedAt: ts, status: 'active', version: 1 };
  await batchSet('module_workspaces', ['Sportsbook Operations','Commercial Growth','Finance Control Room','Compliance Command','Technology Delivery','Executive Office'].map((name, i) => ({ ...common, id: `demo-workspace-${i + 1}`, name, description: `Workspace operacional de ${name.toLowerCase()}.`, ownerId: identity.uid })));
  const projectTitles = ['Sportsbook Q4 Trading Optimisation','Payment Success Recovery','KYC Automation v2','VIP Retention Wave 3','Affiliate Growth 2026','Responsible Gaming Controls','Mobile App Release 4.8','CRM Personalisation Engine','Live Betting Reliability','Finance Reconciliation Automation','SOC Detection Upgrade','Data Mart Executive KPIs'];
  await batchSet('projects', projectTitles.map((name, i) => ({ ...common, id: `demo-project-${i + 1}`, name, description: 'Iniciativa operacional activa.', objective: 'Entregar impacto mensurável no negócio.', workspaceId: `demo-workspace-${(i % 6) + 1}`, ownerId: users[i % users.length].uid, budget: 150000 + i * 25000, budgetSpent: 42000 + i * 6200, startDate: iso(-120 + i, 9), dueDate: iso(15 + i, 18), health: i % 6 === 0 ? 'AT_RISK' : 'HEALTHY', healthScore: i % 6 === 0 ? 71 : 90 }))); 
  await batchSet('module_tasks', Array.from({ length: 72 }, (_, i) => ({ ...common, id: `demo-task-${i + 1}`, title: ['Rever exposição pré-live','Validar payout excepcional','Aprovar reconciliação PSP','Investigar chargebacks','Actualizar matriz AML','Preparar trading live pack','Rever retenção VIP','Validar mudança de odds','Fechar incidente SOC','Publicar daily operations'][i % 10], description: 'Tarefa operacional realista do ciclo diário.', status: ['todo','in-progress','done','blocked','waiting'][i % 5], priority: ['low','medium','high','critical'][i % 4], dueDate: iso(i % 4 === 0 ? 0 : i % 9, 17), assignedTo: [users[i % users.length].uid], departmentId: users[i % users.length].departmentId, projectId: `demo-project-${(i % 12) + 1}` })));
  await batchSet('module_meetings', Array.from({ length: 24 }, (_, i) => ({ ...common, id: `demo-meeting-${i + 1}`, title: ['Daily Trading Stand-up','Risk Committee','Finance Reconciliation Review','CRM Performance Review','KYC Operations Review','SOC Threat Briefing','Executive Weekly','Payments Incident Review'][i % 8], description: 'Agenda operacional, decisões e follow-up.', date: iso(i % 7, 9), time: `${String(9 + (i % 7)).padStart(2, '0')}:00`, duration: 30 + (i % 3) * 30, participants: [identity.uid, users[i % users.length].uid], status: i % 8 === 0 ? 'active' : 'scheduled' })));
  await batchSet('module_calendar_events', Array.from({ length: 32 }, (_, i) => ({ ...common, id: `demo-event-${i + 1}`, title: ['Trading review','PSP settlement','Compliance filing','Campaign launch','Payroll','Provider call','Risk review','Product release'][i % 8], start: iso(i % 14, 8 + (i % 9)), end: iso(i % 14, 9 + (i % 9)), type: i % 3 === 0 ? 'compliance' : 'operations', participants: [identity.uid] })));
  await batchSet('documents', Array.from({ length: 20 }, (_, i) => ({ ...common, id: `demo-doc-${i + 1}`, title: ['Trading Shift Handover','Monthly Finance Close','AML Risk Assessment','KYC Operations Handbook','Campaign Brief Q4','VIP Tier Policy','Payments Reconciliation SOP','Incident Management Handbook','Responsible Gaming Policy','Affiliate Commercial Terms'][i % 10], ownerId: identity.uid, currentVersion: 2 + (i % 4), contentVersion: 2 + (i % 4), sharedCompany: true, editorIds: [identity.uid], viewerIds: [users[i % users.length].uid], textPreview: 'Documento operacional actualizado com políticas e métricas.' })));
  await batchSet('goals', Array.from({ length: 22 }, (_, i) => ({ ...common, id: `demo-goal-${i + 1}`, title: ['Aumentar depósito aprovado','Reduzir tempo de KYC','Reduzir chargeback rate','Aumentar retenção D30','Melhorar sportsbook hold','Reduzir backlog suporte','Atingir reconciliação diária','Reduzir falsos positivos AML'][i % 8], description: 'Objectivo operacional com progresso mensurável.', current: 35 + (i * 3) % 61, target: 100, progress: 35 + (i * 3) % 61, status: i % 9 === 0 ? 'at-risk' : i % 7 === 0 ? 'completed' : 'in-progress', ownerId: users[i % users.length].uid, dueDate: iso(30 + i, 18) })));
  await batchSet('risks', Array.from({ length: 18 }, (_, i) => ({ ...common, id: `demo-risk-${i + 1}`, title: ['Multi-accounting cluster','Chargeback spike','Odds feed divergence','Withdrawal velocity anomaly','VPN/geolocation anomaly','Bonus abuse pattern','Provider latency','KYC mismatch','Account takeover signal'][i % 9], description: 'Caso em análise pelo Risk & Fraud.', severity: ['low','medium','high','critical'][i % 4], status: i % 4 === 0 ? 'investigating' : 'open', playerId: `P${10400 + i}`, projectId: `demo-project-${(i % 12) + 1}` })));
  await batchSet('decisions', Array.from({ length: 16 }, (_, i) => ({ ...common, id: `demo-decision-${i + 1}`, title: ['Ajustar limite pré-live','Migrar PSP fallback','Aprovar regra AML','Rever tier VIP','Congelar campanha','Activar odds provider B','Alterar SLA suporte','Reforçar MFA'][i % 8], decision: 'Aprovado e encaminhado para execução.' })));
  await batchSet('activities', Array.from({ length: 80 }, (_, i) => ({ ...common, id: `demo-activity-${i + 1}`, actorId: users[i % users.length].uid, actorName: names[i % names.length], action: ['approved','updated','created','escalated','resolved','commented'][i % 6], description: ['Aprovou payout','Actualizou exposição','Criou tarefa','Escalou para Compliance','Resolveu alerta','Comentou o relatório'][i % 6], entityType: ['task','project','player','payment','risk','campaign'][i % 6], entityId: `demo-entity-${i + 1}`, createdAt: iso(-(i % 14), 7 + (i % 12)) })));
  await batchSet('payments', Array.from({ length: 48 }, (_, i) => ({ ...common, id: `demo-payment-${i + 1}`, playerId: `P${10400 + i % 48}`, method: ['M-Pesa','e-Mola','Visa','Mastercard','Bank Transfer'][i % 5], type: i % 2 ? 'deposit' : 'withdrawal', amount: 350 + (i % 12) * 250, currency: 'MZN', status: i % 11 === 0 ? 'review' : i % 9 === 0 ? 'failed' : 'completed', fee: 5 + (i % 4), createdAt: iso(-(i % 12), 8 + i % 12) })));
  await batchSet('players', Array.from({ length: 54 }, (_, i) => ({ ...common, id: `P${10400 + i}`, playerId: `P${10400 + i}`, name: `Cliente ${i + 1}`, country: 'MZ', segment: ['standard','active','high-value','VIP','at-risk'][i % 5], kycStatus: i % 13 === 0 ? 'review' : 'verified', balance: 250 + i * 390, lifetimeValue: 3200 + i * 910, lastBetAt: iso(-(i % 6), 22), riskScore: 18 + (i * 7) % 78, status: i % 17 === 0 ? 'suspended' : 'active' })));
  await batchSet('bet_ledger', Array.from({ length: 96 }, (_, i) => ({ ...common, id: `demo-bet-${i + 1}`, betId: `B${55000 + i}`, playerId: `P${10400 + i % 54}`, event: ['Real Madrid v Barcelona','Man City v Arsenal','Liverpool v Chelsea','Inter v Milan','Benfica v Porto'][i % 5], market: ['1X2','Over/Under 2.5','BTTS','Asian Handicap'][i % 4], stake: 120 + (i % 9) * 180, odds: Number((1.35 + (i % 11) * 0.21).toFixed(2)), status: ['won','lost','settled','cashout'][i % 4], live: i % 3 === 0, createdAt: iso(-(i % 12), 12 + i % 11) })));
  await batchSet('trading_events', Array.from({ length: 30 }, (_, i) => ({ ...common, id: `demo-trading-${i + 1}`, event: ['Real Madrid v Barcelona','Man City v Arsenal','Liverpool v Chelsea','Inter v Milan'][i % 4], market: ['1X2','O/U 2.5','BTTS'][i % 3], handle: 185000 + i * 13750, liability: 42000 + i * 3100, hold: Number((6.1 + (i % 9) * 0.42).toFixed(2)), status: i % 8 === 0 ? 'suspended' : 'open', trader: names[5 + i % 15] })));
  await batchSet('responsible_gaming_cases', Array.from({ length: 16 }, (_, i) => ({ ...common, id: `demo-rg-${i + 1}`, playerId: `P${10400 + i}`, trigger: ['deposit velocity','loss threshold','session duration','self-exclusion request','affordability signal'][i % 5], severity: ['low','medium','high'][i % 3], status: i % 5 === 0 ? 'escalated' : 'open', lastReviewedAt: iso(-(i % 8), 15) })));
  await batchSet('vip_accounts', Array.from({ length: 20 }, (_, i) => ({ ...common, id: `demo-vip-${i + 1}`, playerId: `P${10420 + i}`, tier: ['Silver','Gold','Platinum','Diamond'][i % 4], monthlyHandle: 85000 + i * 11200, monthlyNgr: 6400 + i * 870, assignedManager: names[20 + i % 8], health: ['healthy','watch','churn-risk'][i % 3] })));
  await batchSet('affiliates', Array.from({ length: 14 }, (_, i) => ({ ...common, id: `demo-affiliate-${i + 1}`, name: ['BetRadar Africa','Moz Sports Network','Football MZ','Maputo Tips','Premium Odds Hub','Soccer Central','PlayMZ'][i % 7], model: i % 2 ? 'RevShare' : 'CPA', commissionRate: i % 2 ? 0.28 + (i % 4) * 0.02 : 35 + i * 5, ftd: 110 + i * 17, active: true, complianceStatus: i % 7 === 0 ? 'review' : 'approved' })));
  await batchSet('support_tickets', Array.from({ length: 36 }, (_, i) => ({ ...common, id: `demo-ticket-${i + 1}`, ticket: `CS-${82000 + i}`, category: ['payment','kyc','settlement','bonus','technical','account'][i % 6], priority: ['low','medium','high','urgent'][i % 4], status: ['open','pending','waiting','resolved'][i % 4], playerId: `P${10400 + i % 54}`, assignee: names[12 + i % 16], slaMinutes: 30 + (i % 6) * 30, openedAt: iso(-(i % 7), 8 + i % 11) })));

  const notificationRef = db.collection('notifications').doc(identity.uid).collection('items'); const notificationBatch = db.batch(); for (let i = 0; i < 20; i++) notificationBatch.set(notificationRef.doc(`demo-${i + 1}`), { id: `demo-notification-${i + 1}`, type: ['due','mention','request','created','file'][i % 5], title: ['Nova tarefa crítica','Mencionado no Risk Committee','Solicitação de pagamento','Relatório diário disponível','Ficheiro partilhado'][i % 5], message: 'Actividade pendente na operação Txuna Bet.', actorName: names[i % names.length], entity: ['Sportsbook Q4 Trading Optimisation','Risk Committee','Withdrawal Review','Daily Operations Pack','Trading Shift Handover'][i % 5], read: i > 7, archived: false, createdAt: iso(-(i % 4), 8 + i % 10) }, { merge: true }); await notificationBatch.commit();
  await marker.set({ version: 4, seededAt: ts, seededBy: identity.uid, departmentCount: BET_DEPARTMENTS.length, userCount: users.length, note: 'realistic Txuna Bet operating dataset' }, { merge: true });
}
