import 'server-only';
import { Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { replayAutomationRun } from '@/server/services/automation-control';

export async function createBackupManifest(label='scheduled'){const identity=await requirePermission(PERMISSIONS.COMPANY_ADMIN);const ref=getAdminDb().collection('dr_manifests').doc();const collections=['companies','departments','teams','projects','goals','key_results','module_tasks','module_campaigns','module_meetings','module_calendar_events','documents','module_cloud_files','module_knowledge_articles','module_reports','module_workflows','module_automations','approvals','automation_jobs','automation_runs','automation_dead_letters','event_outbox','entity_relationships','auditLogs'];await ref.create({id:ref.id,companyId:identity.companyId,label:label.slice(0,120),status:'prepared',collections,restoreOrder:['companies','departments','teams','projects','goals','key_results','module_tasks','module_campaigns','module_meetings','documents','approvals','module_workflows','module_automations','automation_jobs'],createdBy:identity.uid,createdAt:Timestamp.now(),retentionDays:30,note:'Manifesto de DR. Backup físico depende da infraestrutura Firebase/GCP configurada para o projeto.'});return{id:ref.id,collections};}
export async function listRecoveryManifests(){const identity=await requirePermission(PERMISSIONS.COMPANY_ADMIN);const s=await getAdminDb().collection('dr_manifests').where('companyId','==',identity.companyId).orderBy('createdAt','desc').limit(50).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function replayDeadLetter(runId:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const snapshot=await getAdminDb().collection('automation_runs').doc(runId).get();if(!snapshot.exists||snapshot.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');return replayAutomationRun(runId);}
export function getDRChecklist(){return{backup:'external_backup_required',restore:'documented_manifest',deadLetter:'replay_supported',audit:'immutable_server_audit',migrations:'versioned_migration_directory',rtoMinutes:Number(process.env.ORYON_DR_RTO_MINUTES??60),rpoMinutes:Number(process.env.ORYON_DR_RPO_MINUTES??60)};}
