import 'server-only';
import { Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requirePermission, requireMfa } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { integrationHealth } from '@/server/services/integration-platform';

async function count(companyId:string,collection:string,filters:Array<[string,'==',unknown]>=[]):Promise<number>{let q=getAdminDb().collection(collection).where('companyId','==',companyId);for(const [field,op,value]of filters)q=q.where(field,op,value);return(await q.get()).size;}
export async function getEnterpriseAdminSnapshot(){const identity=await requirePermission(PERMISSIONS.COMPANY_READ);const db=getAdminDb();const [members,departments,teams,connections,queued,failed,dead,aiUsage,audit,policies]=await Promise.all([db.collection('companies').doc(identity.companyId).collection('members').where('status','==','active').limit(500).get(),count(identity.companyId,'departments'),count(identity.companyId,'teams'),integrationHealth(),count(identity.companyId,'automation_jobs',[['status','==','pending']]),count(identity.companyId,'automation_jobs',[['status','==','failed']]),count(identity.companyId,'automation_dead_letters'),db.collection('ai_usage').where('companyId','==',identity.companyId).limit(200).get(),db.collection('companies').doc(identity.companyId).collection('auditLogs').limit(50).get(),count(identity.companyId,'enterprise_policies')]);const aiRequests=aiUsage.docs.reduce((sum,d)=>sum+Number(d.data().requests??0),0),aiInputChars=aiUsage.docs.reduce((sum,d)=>sum+Number(d.data().inputChars??0),0);return{organization:{companyId:identity.companyId,users:members.size,departments,teams},identity:{role:identity.role,permissions:identity.permissions,departmentIds:identity.departmentIds,mfaConfigured:Boolean(identity.token.firebase?.sign_in_second_factor)},security:{recentAuditEvents:audit.size,policies},automation:{queued,failed,deadLetters:dead},ai:{requests:aiRequests,inputChars:aiInputChars,models:{fast:process.env.ORYON_AI_FAST_MODEL??'gemini-2.5-flash',balanced:process.env.ORYON_AI_BALANCED_MODEL??'gemini-2.5-flash',deep:process.env.ORYON_AI_DEEP_MODEL??'gemini-2.5-flash'}},integrations:connections};}
export async function listEnterpriseAudit(limit=200){const identity=await requirePermission(PERMISSIONS.AUDIT_READ);const s=await getAdminDb().collection('companies').doc(identity.companyId).collection('auditLogs').orderBy('createdAt','desc').limit(Math.min(limit,500)).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function writeEnterprisePolicy(key:string,value:Record<string,unknown>){const identity=await requireMfa();if(identity.role!=='owner'&&identity.role!=='admin')throw new Error('FORBIDDEN');if(!/^[A-Za-z0-9_.-]{1,120}$/.test(key))throw new Error('INVALID_POLICY');await getAdminDb().collection('enterprise_policies').doc(`${identity.companyId}_${key}`).set({companyId:identity.companyId,key,value,updatedBy:identity.uid,updatedAt:Timestamp.now()},{merge:true});return{key,value};}
