import 'server-only';

import crypto from 'node:crypto';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requireIdentity, requirePermission, type AuthenticatedIdentity } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { writeAuditEvent } from '@/server/repositories/audit';
import { publishDomainEvent } from '@/server/services/foundation';
import { assertSafeOutboundUrl, signWebhook, verifyWebhookSignature } from '@/server/services/security-hardening';

export type IntegrationProvider='google-workspace'|'google-calendar'|'gmail'|'google-drive'|'microsoft-365'|'outlook'|'slack'|'zoom'|'teams'|'github'|'gitlab'|'dropbox'|'external-api';
export type ConnectionState='disconnected'|'pending'|'connected'|'error'|'reauth_required';
export type IntegrationDefinition={provider:IntegrationProvider;label:string;category:string;oauth:boolean;scopes:string[];supportsRefresh:boolean;supportsWebhooks:boolean;supportsSync:boolean;authorizationUrl?:string;tokenUrl?:string};
const GOOGLE_AUTH='https://accounts.google.com/o/oauth2/v2/auth',GOOGLE_TOKEN='https://oauth2.googleapis.com/token';
const MICROSOFT_AUTH='https://login.microsoftonline.com/common/oauth2/v2.0/authorize',MICROSOFT_TOKEN='https://login.microsoftonline.com/common/oauth2/v2.0/token';
const INTEGRATIONS:IntegrationDefinition[]=[
 {provider:'google-workspace',label:'Google Workspace',category:'productivity',oauth:true,scopes:['openid','email','profile'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:GOOGLE_AUTH,tokenUrl:GOOGLE_TOKEN},
 {provider:'google-calendar',label:'Google Calendar',category:'calendar',oauth:true,scopes:['openid','email','profile','https://www.googleapis.com/auth/calendar'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:GOOGLE_AUTH,tokenUrl:GOOGLE_TOKEN},
 {provider:'gmail',label:'Gmail',category:'communication',oauth:true,scopes:['openid','email','profile','https://www.googleapis.com/auth/gmail.readonly'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:GOOGLE_AUTH,tokenUrl:GOOGLE_TOKEN},
 {provider:'google-drive',label:'Google Drive',category:'files',oauth:true,scopes:['openid','email','profile','https://www.googleapis.com/auth/drive.file'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:GOOGLE_AUTH,tokenUrl:GOOGLE_TOKEN},
 {provider:'microsoft-365',label:'Microsoft 365',category:'productivity',oauth:true,scopes:['openid','profile','email','offline_access'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:MICROSOFT_AUTH,tokenUrl:MICROSOFT_TOKEN},
 {provider:'outlook',label:'Outlook',category:'communication',oauth:true,scopes:['openid','profile','email','offline_access','https://graph.microsoft.com/Mail.Read'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:MICROSOFT_AUTH,tokenUrl:MICROSOFT_TOKEN},
 {provider:'slack',label:'Slack',category:'communication',oauth:true,scopes:['openid','profile','email'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:'https://slack.com/oauth/v2/authorize',tokenUrl:'https://slack.com/api/oauth.v2.access'},
 {provider:'zoom',label:'Zoom',category:'meetings',oauth:true,scopes:['account:read','meeting:read','recording:read'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:'https://zoom.us/oauth/authorize',tokenUrl:'https://zoom.us/oauth/token'},
 {provider:'teams',label:'Microsoft Teams',category:'meetings',oauth:true,scopes:['openid','profile','email','offline_access','User.Read'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:MICROSOFT_AUTH,tokenUrl:MICROSOFT_TOKEN},
 {provider:'github',label:'GitHub',category:'development',oauth:true,scopes:['read:user','repo'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:'https://github.com/login/oauth/authorize',tokenUrl:'https://github.com/login/oauth/access_token'},
 {provider:'gitlab',label:'GitLab',category:'development',oauth:true,scopes:['read_user','read_api','offline_access'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:'https://gitlab.com/oauth/authorize',tokenUrl:'https://gitlab.com/oauth/token'},
 {provider:'dropbox',label:'Dropbox',category:'files',oauth:true,scopes:['account_info.read','files.metadata.read','files.content.read'],supportsRefresh:true,supportsWebhooks:true,supportsSync:true,authorizationUrl:'https://www.dropbox.com/oauth2/authorize',tokenUrl:'https://api.dropboxapi.com/oauth2/token'},
 {provider:'external-api',label:'External API',category:'custom',oauth:false,scopes:['api.read','api.write'],supportsRefresh:false,supportsWebhooks:true,supportsSync:true},
];
const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
const idOk=(id:string)=>/^[A-Za-z0-9_-]{1,180}$/.test(id);
function keyMaterial():Buffer{const raw=process.env.ORYON_INTEGRATION_ENCRYPTION_KEY;if(!raw)throw new Error('INTEGRATION_ENCRYPTION_KEY_MISSING');const key=Buffer.from(raw,'base64');if(key.length!==32)throw new Error('INTEGRATION_ENCRYPTION_KEY_INVALID');return key;}
function encrypt(value:string){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',keyMaterial(),iv),ciphertext=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return{ciphertext:ciphertext.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64')};}
function decrypt(payload:{ciphertext:string;iv:string;tag:string}){const decipher=crypto.createDecipheriv('aes-256-gcm',keyMaterial(),Buffer.from(payload.iv,'base64'));decipher.setAuthTag(Buffer.from(payload.tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(payload.ciphertext,'base64')),decipher.final()]).toString('utf8');}
export function getIntegrationCatalog(){return INTEGRATIONS.map((item)=>({...item,scopes:[...item.scopes]}));}
export function getIntegrationDefinition(provider:IntegrationProvider){const item=INTEGRATIONS.find((x)=>x.provider===provider);if(!item)throw new Error('INTEGRATION_PROVIDER_NOT_FOUND');return item;}
export function validateExternalUrl(input:string){return assertSafeOutboundUrl(input);}
function oauthClient(provider:IntegrationProvider){const id=process.env[`ORYON_${provider.replace(/-/g,'_').toUpperCase()}_CLIENT_ID`]??process.env.ORYON_OAUTH_CLIENT_ID;const secret=process.env[`ORYON_${provider.replace(/-/g,'_').toUpperCase()}_CLIENT_SECRET`]??process.env.ORYON_OAUTH_CLIENT_SECRET;return{id,secret};}
export async function createOAuthState(provider:IntegrationProvider,redirectUri:string,verifier?:string):Promise<{state:string;url:string}>{const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const definition=getIntegrationDefinition(provider);if(!definition.oauth||!definition.authorizationUrl)throw new Error('OAUTH_PROVIDER_NOT_CONFIGURED');const safeRedirect=validateExternalUrl(redirectUri);const appUrl=process.env.ORYON_PUBLIC_URL||process.env.NEXT_PUBLIC_APP_URL;if(appUrl&&new URL(appUrl).origin!==safeRedirect.origin)throw new Error('OAUTH_REDIRECT_NOT_ALLOWED');const client=oauthClient(provider);if(!client.id)throw new Error('OAUTH_CLIENT_ID_MISSING');const state=crypto.randomBytes(32).toString('hex');const ref=getAdminDb().collection('integration_oauth_states').doc(hash(state));await ref.create({companyId:identity.companyId,userId:identity.uid,provider,redirectUri:safeRedirect.toString(),verifierHash:verifier?hash(verifier):null,verifier:verifier?encrypt(verifier):null,expiresAt:Timestamp.fromMillis(Date.now()+10*60*1000),used:false,createdAt:FieldValue.serverTimestamp()});const params=new URLSearchParams({client_id:client.id,redirect_uri:safeRedirect.toString(),response_type:'code',scope:definition.scopes.join(' '),state});if(verifier){params.set('code_challenge',crypto.createHash('sha256').update(verifier).digest('base64url'));params.set('code_challenge_method','S256');}return{state,url:`${definition.authorizationUrl}?${params}`};}
export async function exchangeOAuthCode(provider:IntegrationProvider,state:string,code:string):Promise<{connectionId:string;status:ConnectionState}>{const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const stateRef=getAdminDb().collection('integration_oauth_states').doc(hash(state));const snap=await stateRef.get();if(!snap.exists)throw new Error('OAUTH_STATE_INVALID');const sd=snap.data()??{};if(sd.companyId!==identity.companyId||sd.userId!==identity.uid||sd.used===true)throw new Error('OAUTH_STATE_INVALID');if(sd.expiresAt instanceof Timestamp&&sd.expiresAt.toMillis()<Date.now())throw new Error('OAUTH_STATE_EXPIRED');const def=getIntegrationDefinition(provider);if(!def.tokenUrl)throw new Error('OAUTH_PROVIDER_NOT_CONFIGURED');const client=oauthClient(provider);if(!client.id||!client.secret)throw new Error('OAUTH_CREDENTIALS_MISSING');const body=new URLSearchParams({client_id:client.id,client_secret:client.secret,code,redirect_uri:String(sd.redirectUri),grant_type:'authorization_code'});if(sd.verifier)body.set('code_verifier',decrypt(sd.verifier));const response=await fetch(def.tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body,signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`OAUTH_TOKEN_${response.status}`);const tokens=await response.json() as Record<string,unknown>;const connectionRef=getAdminDb().collection('integration_connections').doc();const fields:Record<string,unknown>={};for(const field of ['access_token','refresh_token','id_token'])if(typeof tokens[field]==='string')fields[field]=encrypt(tokens[field] as string);await getAdminDb().collection('integration_secrets').doc(connectionRef.id).set({companyId:identity.companyId,connectionId:connectionRef.id,fields,updatedAt:Timestamp.now()});await connectionRef.create({id:connectionRef.id,companyId:identity.companyId,provider,state:'connected',accountEmail:typeof tokens.email==='string'?tokens.email:null,scope:typeof tokens.scope==='string'?tokens.scope:null,expiresAt:typeof tokens.expires_in==='number'?Timestamp.fromMillis(Date.now()+Number(tokens.expires_in)*1000):null,createdBy:identity.uid,updatedBy:identity.uid,createdAt:Timestamp.now(),updatedAt:Timestamp.now(),lastSyncAt:null,lastError:null});await stateRef.update({used:true,usedAt:Timestamp.now()});await publishDomainEvent({eventName:'integration.connected',entityType:'integration',entityId:connectionRef.id,payload:{provider},metadata:{source:'integration-platform'}},{companyId:identity.companyId,actorId:identity.uid});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'integration.connect',resourceType:'integration',resourceId:connectionRef.id,metadata:{provider}});return{connectionId:connectionRef.id,status:'connected'};}
export async function refreshConnection(id:string):Promise<void>{const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);if(!idOk(id))throw new Error('INVALID_ID');const ref=getAdminDb().collection('integration_connections').doc(id),snap=await ref.get();if(!snap.exists||snap.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');const data=snap.data()??{},def=getIntegrationDefinition(data.provider as IntegrationProvider),client=oauthClient(data.provider as IntegrationProvider);const secrets=await getAdminDb().collection('integration_secrets').doc(id).get();const refresh=secrets.data()?.fields?.refresh_token;if(!refresh||!def.tokenUrl||!client.id||!client.secret)throw new Error('REFRESH_UNAVAILABLE');const body=new URLSearchParams({client_id:client.id,client_secret:client.secret,grant_type:'refresh_token',refresh_token:decrypt(refresh)});const response=await fetch(def.tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body,signal:AbortSignal.timeout(15000)});if(!response.ok){await ref.update({state:'reauth_required',lastError:`REFRESH_${response.status}`,updatedAt:Timestamp.now()});throw new Error(`REFRESH_TOKEN_${response.status}`);}const tokens=await response.json() as Record<string,unknown>;const patch:Record<string,unknown>={};for(const field of ['access_token','refresh_token','id_token'])if(typeof tokens[field]==='string')patch[field]=encrypt(tokens[field] as string);await secrets.ref.set({companyId:identity.companyId,connectionId:id,fields:{...(secrets.data()?.fields??{}),...patch},updatedAt:Timestamp.now()},{merge:true});await ref.update({state:'connected',expiresAt:typeof tokens.expires_in==='number'?Timestamp.fromMillis(Date.now()+Number(tokens.expires_in)*1000):data.expiresAt,lastError:null,updatedBy:identity.uid,updatedAt:Timestamp.now()});}
export async function listConnections(){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const snap=await getAdminDb().collection('integration_connections').where('companyId','==',identity.companyId).limit(200).get();return snap.docs.map((d)=>({id:d.id,...d.data()}));}
export async function disconnectConnection(id:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);if(!idOk(id))throw new Error('INVALID_ID');const ref=getAdminDb().collection('integration_connections').doc(id),snap=await ref.get();if(!snap.exists||snap.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');await getAdminDb().collection('integration_secrets').doc(id).delete().catch(()=>undefined);await ref.update({state:'disconnected',updatedAt:Timestamp.now(),updatedBy:identity.uid});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'integration.disconnect',resourceType:'integration',resourceId:id});}
export async function createWebhook(provider:IntegrationProvider,connectionId:string,endpoint:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);assertSafeOutboundUrl(endpoint);const ref=getAdminDb().collection('integration_webhooks').doc(),secret=crypto.randomBytes(32).toString('hex');await ref.create({id:ref.id,companyId:identity.companyId,provider,connectionId,endpoint,secret:encrypt(secret),secretHash:hash(secret),state:'active',events:[],lastDeliveryAt:null,lastError:null,createdAt:Timestamp.now(),updatedAt:Timestamp.now()});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'integration.webhook.create',resourceType:'integration',resourceId:connectionId,metadata:{provider,webhookId:ref.id}});return secret;}
export async function enqueueSyncJob(connectionId:string,kind='incremental'){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const conn=await getAdminDb().collection('integration_connections').doc(connectionId).get();if(!conn.exists||conn.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');const ref=getAdminDb().collection('integration_sync_jobs').doc();await ref.create({id:ref.id,companyId:identity.companyId,connectionId,kind,status:'pending',attempts:0,maxAttempts:8,nextAttemptAt:Timestamp.now(),lastError:null,createdAt:Timestamp.now(),updatedAt:Timestamp.now()});return ref.id;}
export async function verifyInboundWebhook(webhookId:string,timestamp:string,signature:string,body:string){const snap=await getAdminDb().collection('integration_webhooks').doc(webhookId).get();if(!snap.exists)throw new Error('WEBHOOK_NOT_FOUND');const data=snap.data()??{},secret=data.secret;if(!secret)throw new Error('WEBHOOK_SECRET_UNAVAILABLE');const valid=verifyWebhookSignature(decrypt(secret),timestamp,body,signature);if(!valid)throw new Error('WEBHOOK_SIGNATURE_INVALID');await snap.ref.update({lastDeliveryAt:Timestamp.now(),lastError:null,updatedAt:Timestamp.now()});return{companyId:String(data.companyId),provider:data.provider as IntegrationProvider,connectionId:String(data.connectionId)};}
export async function integrationHealth(){const identity=await requireIdentity(),db=getAdminDb();const[connections,jobs,webhooks]=await Promise.all([db.collection('integration_connections').where('companyId','==',identity.companyId).limit(200).get(),db.collection('integration_sync_jobs').where('companyId','==',identity.companyId).limit(200).get(),db.collection('integration_webhooks').where('companyId','==',identity.companyId).limit(200).get()]);return{connections:{total:connections.size,connected:connections.docs.filter(d=>d.data().state==='connected').length,errors:connections.docs.filter(d=>['error','reauth_required'].includes(String(d.data().state))).length},syncJobs:{total:jobs.size,pending:jobs.docs.filter(d=>d.data().status==='pending').length,failed:jobs.docs.filter(d=>d.data().status==='failed').length},webhooks:{total:webhooks.size,healthy:webhooks.docs.filter(d=>!d.data().lastError).length}};}
