import 'server-only';
import { Timestamp } from 'firebase-admin/firestore';
import { getAdminDb } from '@/server/firebase/admin';
import { requireIdentity, requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';

export type EnterpriseMetricName='api_latency_ms'|'firestore_latency_ms'|'function_latency_ms'|'worker_latency_ms'|'queue_depth'|'job_failure'|'ai_latency_ms'|'ai_cost_chars'|'search_latency_ms'|'meeting_processing_ms'|'error_rate';
export type EnterpriseMetric={name:EnterpriseMetricName;value:number;success?:boolean;route?:string;component?:string;timestamp?:string};
const allowedMetrics=new Set<EnterpriseMetricName>(['api_latency_ms','firestore_latency_ms','function_latency_ms','worker_latency_ms','queue_depth','job_failure','ai_latency_ms','ai_cost_chars','search_latency_ms','meeting_processing_ms','error_rate']);
export async function recordEnterpriseMetric(metric:EnterpriseMetric){const identity=await requireIdentity();if(!allowedMetrics.has(metric.name)||!Number.isFinite(metric.value))throw new Error('INVALID_METRIC');const ref=getAdminDb().collection('observability_metrics').doc();await ref.create({id:ref.id,companyId:identity.companyId,name:metric.name,value:Math.max(0,Math.min(metric.value,1e9)),success:metric.success??true,route:String(metric.route??'').slice(0,240),component:String(metric.component??'').slice(0,120),timestamp:metric.timestamp??new Date().toISOString(),createdAt:Timestamp.now()});return ref.id;}
export async function createObservabilityAlert(name:string,severity:'info'|'warning'|'critical',threshold:number,metric:EnterpriseMetricName){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);if(!allowedMetrics.has(metric)||!name.trim())throw new Error('INVALID_ALERT');const ref=getAdminDb().collection('observability_alerts').doc();await ref.create({id:ref.id,companyId:identity.companyId,name:name.trim().slice(0,180),severity,threshold,metric,active:true,state:'ok',lastValue:null,lastTriggeredAt:null,createdBy:identity.uid,createdAt:Timestamp.now(),updatedAt:Timestamp.now()});return{id:ref.id};}
export async function getObservabilityDashboard(){const identity=await requirePermission(PERMISSIONS.OPERATIONS_READ);const db=getAdminDb();const [metrics,alerts]=await Promise.all([db.collection('observability_metrics').where('companyId','==',identity.companyId).orderBy('timestamp','desc').limit(1000).get(),db.collection('observability_alerts').where('companyId','==',identity.companyId).limit(200).get()]);const grouped=new Map<string,number[]>();for(const d of metrics.docs){const name=String(d.data().name);const v=Number(d.data().value);if(!grouped.has(name))grouped.set(name,[]);grouped.get(name)!.push(v);}const summary=Object.fromEntries(Array.from(grouped.entries()).map(([name,values])=>[name,{count:values.length,average:Math.round(values.reduce((a,b)=>a+b,0)/values.length),max:Math.max(...values),latest:values[0]}]));return{summary,alerts:alerts.docs.map(d=>({id:d.id,...d.data()})),samples:metrics.docs.slice(0,100).map(d=>({id:d.id,...d.data()}))};}
export async function evaluateObservabilityAlerts(){const identity=await requireIdentity();const db=getAdminDb();const [alerts,metrics]=await Promise.all([db.collection('observability_alerts').where('companyId','==',identity.companyId).where('active','==',true).limit(200).get(),db.collection('observability_metrics').where('companyId','==',identity.companyId).orderBy('timestamp','desc').limit(500).get()]);let triggered=0;for(const alert of alerts.docs){const a=alert.data();const latest=metrics.docs.find(m=>m.data().name===a.metric);if(!latest)continue;const value=Number(latest.data().value);const hit=value>=Number(a.threshold);await alert.ref.update({lastValue:value,state:hit?'triggered':'ok',lastTriggeredAt:hit?Timestamp.now():a.lastTriggeredAt,updatedAt:Timestamp.now()});if(hit)triggered++;}return{checked:alerts.size,triggered};}
