import 'server-only';

import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { z } from 'zod';
import { requireIdentity, requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { getAdminDb } from '@/server/firebase/admin';
import { queueDomainEventTransaction, recordAuditMutation } from '@/server/services/foundation';

export type ProjectHealth = 'HEALTHY' | 'AT_RISK' | 'CRITICAL';

const IdSchema = z.string().regex(/^[A-Za-z0-9_-]{1,180}$/);
const WorkspaceSchema = z.object({ name: z.string().min(1).max(180), description: z.string().max(3000).default(''), departmentId: IdSchema.optional(), ownerId: IdSchema.optional(), metadata: z.record(z.unknown()).default({}) });
const ProjectSchema = z.object({ name: z.string().min(1).max(180), description: z.string().max(5000).default(''), workspaceId: IdSchema.optional(), teamId: IdSchema.optional(), ownerId: IdSchema.optional(), objective: z.string().max(1000).default(''), startDate: z.string().datetime().optional(), dueDate: z.string().datetime().optional(), budget: z.number().nonnegative().max(1_000_000_000).default(0), metadata: z.record(z.unknown()).default({}) });
const GoalSchema = z.object({ title: z.string().min(1).max(240), description: z.string().max(5000).default(''), level: z.enum(['company', 'department', 'team']).default('company'), parentGoalId: IdSchema.optional(), ownerId: IdSchema.optional(), target: z.number().nonnegative().max(1_000_000_000).default(100), current: z.number().max(1_000_000_000).default(0), unit: z.string().max(40).default('%'), dueDate: z.string().datetime().optional(), metadata: z.record(z.unknown()).default({}) });
const KeyResultSchema = z.object({ goalId: IdSchema, title: z.string().min(1).max(240), target: z.number().nonnegative().max(1_000_000_000), current: z.number().max(1_000_000_000).default(0), unit: z.string().max(40).default('%'), ownerId: IdSchema.optional(), projectId: IdSchema.optional(), taskId: IdSchema.optional(), dueDate: z.string().datetime().optional() });
const AllocationSchema = z.object({ userId: IdSchema, projectId: IdSchema, weekStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), availableHours: z.number().nonnegative().max(168), allocatedHours: z.number().nonnegative().max(1680), metadata: z.record(z.unknown()).default({}) });
const TimeEntrySchema = z.object({ projectId: IdSchema, taskId: IdSchema.optional(), startedAt: z.string().datetime(), endedAt: z.string().datetime().optional(), minutes: z.number().nonnegative().max(100000).optional(), note: z.string().max(2000).default('') });
const BudgetSchema = z.object({ spent: z.number().nonnegative().max(1_000_000_000), committed: z.number().nonnegative().max(1_000_000_000).default(0) });

export function calculateGoalProgress(current: number, target: number): number { if (target <= 0) return 0; return Math.max(0, Math.min(100, (current / target) * 100)); }
export function calculateCapacity(availableHours: number, allocatedHours: number) { const available = Math.max(0, availableHours); const allocated = Math.max(0, allocatedHours); const utilization = available > 0 ? (allocated / available) * 100 : allocated > 0 ? 100 : 0; return { availableHours: available, allocatedHours: allocated, utilization: Math.round(utilization * 10) / 10, overloadHours: Math.max(0, allocated - available), underloadHours: Math.max(0, available - allocated) }; }

export function calculateProjectHealth(input: { overdueTasks: number; blockedTasks: number; criticalTasks: number; capacityUtilization: number; milestoneVarianceDays: number; deadlineDays: number; recentActivityDays: number; budgetPercent: number; unresolvedRisks: number }) {
  const reasons: string[] = []; let score = 100;
  if (input.overdueTasks > 0) { score -= Math.min(30, input.overdueTasks * 6); reasons.push(`${input.overdueTasks} tarefas em atraso`); }
  if (input.blockedTasks > 0) { score -= Math.min(25, input.blockedTasks * 8); reasons.push(`${input.blockedTasks} tarefas bloqueadas`); }
  if (input.criticalTasks > 0) { score -= Math.min(25, input.criticalTasks * 10); reasons.push(`${input.criticalTasks} tarefas críticas`); }
  if (input.capacityUtilization > 100) { score -= Math.min(25, (input.capacityUtilization - 100) * 0.8); reasons.push(`capacidade a ${Math.round(input.capacityUtilization)}%`); }
  if (input.milestoneVarianceDays > 0) { score -= Math.min(20, input.milestoneVarianceDays * 2); reasons.push(`milestones ${input.milestoneVarianceDays} dias atrasados`); }
  if (input.deadlineDays >= 0 && input.deadlineDays <= 3) { score -= 10; reasons.push('deadline próximo'); }
  if (input.recentActivityDays > 7) { score -= 8; reasons.push('baixa atividade recente'); }
  if (input.budgetPercent > 100) { score -= Math.min(25, input.budgetPercent - 100); reasons.push(`budget ${Math.round(input.budgetPercent)}% consumido`); }
  if (input.unresolvedRisks > 0) { score -= Math.min(20, input.unresolvedRisks * 5); reasons.push(`${input.unresolvedRisks} riscos por resolver`); }
  const health: ProjectHealth = score < 55 || input.criticalTasks >= 3 || input.capacityUtilization >= 125 || input.budgetPercent >= 120 ? 'CRITICAL' : score < 80 || input.overdueTasks >= 2 || input.capacityUtilization > 100 || input.unresolvedRisks >= 2 ? 'AT_RISK' : 'HEALTHY';
  return { health, score: Math.round(Math.max(0, Math.min(100, score))), reasons };
}

function millis(value: unknown): number { if (value instanceof Timestamp) return value.toMillis(); if (value instanceof Date) return value.getTime(); if (typeof value === 'string') return Date.parse(value) || 0; return 0; }
function records(snapshot: FirebaseFirestore.QuerySnapshot<FirebaseFirestore.DocumentData>) { return snapshot.docs.map((doc) => ({ id: doc.id, ...(doc.data() as Record<string, unknown>) })); }
async function companyQuery(collection: string, companyId: string, limit = 500) { return getAdminDb().collection(collection).where('companyId', '==', companyId).limit(limit).get(); }
async function assertProject(companyId: string, projectId: string) { const ref = getAdminDb().collection('projects').doc(projectId); const snapshot = await ref.get(); if (!snapshot.exists || snapshot.data()?.companyId !== companyId) throw new Error('PROJECT_NOT_FOUND'); return { ref, data: snapshot.data() as Record<string, unknown> }; }

const WORKSPACE_COLLECTION = 'module_workspaces';
export async function listWorkspaces() { const identity = await requireIdentity(); const [workspaces, projects] = await Promise.all([companyQuery(WORKSPACE_COLLECTION, identity.companyId), companyQuery('projects', identity.companyId)]); return records(workspaces).map((workspace) => ({ ...workspace, projects: records(projects).filter((project) => project.workspaceId === workspace.id) })); }

export async function createWorkspace(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = WorkspaceSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_WORKSPACE'); const db = getAdminDb(); const ref = db.collection(WORKSPACE_COLLECTION).doc(); const now = FieldValue.serverTimestamp(); await db.runTransaction(async (transaction) => { transaction.create(ref, { id: ref.id, companyId: identity.companyId, ...parsed.data, createdBy: identity.uid, updatedBy: identity.uid, createdAt: now, updatedAt: now, status: 'active', version: 1 }); await queueDomainEventTransaction(transaction, { eventName: 'workspace.created', entityType: 'workspace', entityId: ref.id, payload: { name: parsed.data.name }, metadata: { source: 'project-os' } }, { companyId: identity.companyId, actorId: identity.uid }); }); await recordAuditMutation({ identity, entity: 'workspace', entityId: ref.id, action: 'create', after: parsed.data }); return { id: ref.id, ...(await ref.get()).data() }; }

export async function createProject(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = ProjectSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_PROJECT'); if (parsed.data.workspaceId) { const workspace = await getAdminDb().collection(WORKSPACE_COLLECTION).doc(parsed.data.workspaceId).get(); if (!workspace.exists || workspace.data()?.companyId !== identity.companyId) throw new Error('WORKSPACE_NOT_FOUND'); } const db = getAdminDb(); const ref = db.collection('projects').doc(); const now = FieldValue.serverTimestamp(); await db.runTransaction(async (transaction) => { transaction.create(ref, { id: ref.id, companyId: identity.companyId, ...parsed.data, createdBy: identity.uid, updatedBy: identity.uid, createdAt: now, updatedAt: now, status: 'active', version: 1, health: 'HEALTHY', healthScore: 100, healthReasons: [] }); await queueDomainEventTransaction(transaction, { eventName: 'project.created', entityType: 'project', entityId: ref.id, payload: { name: parsed.data.name, workspaceId: parsed.data.workspaceId, ownerId: parsed.data.ownerId }, metadata: { source: 'project-os' } }, { companyId: identity.companyId, actorId: identity.uid }); }); await recordAuditMutation({ identity, entity: 'project', entityId: ref.id, action: 'create', after: parsed.data }); return { id: ref.id, ...(await ref.get()).data() }; }

export async function getProjectOs(projectId: string) {
  const identity = await requireIdentity(); IdSchema.parse(projectId); const db = getAdminDb(); const { data: project } = await assertProject(identity.companyId, projectId);
  const [tasksSnap, subtaskSnap, milestonesSnap, depsOutSnap, depsInSnap, filesSnap, docsSnap, meetingsSnap, risksSnap, decisionsSnap, activitiesSnap, goalsSnap, allocationsSnap, timeSnap] = await Promise.all([
    companyQuery('module_tasks', identity.companyId, 500), companyQuery('task_subtasks', identity.companyId, 500), companyQuery('project_milestones', identity.companyId, 200),
    db.collection('entity_relationships').where('companyId', '==', identity.companyId).where('sourceType', '==', 'task').limit(500).get(), db.collection('entity_relationships').where('companyId', '==', identity.companyId).where('targetType', '==', 'task').limit(500).get(),
    companyQuery('module_cloud_files', identity.companyId, 200), companyQuery('documents', identity.companyId, 200), companyQuery('module_meetings', identity.companyId, 200), companyQuery('risks', identity.companyId, 200), companyQuery('decisions', identity.companyId, 200), companyQuery('activities', identity.companyId, 500), companyQuery('goals', identity.companyId, 200), companyQuery('capacity_allocations', identity.companyId, 500), companyQuery('time_entries', identity.companyId, 1000),
  ]);
  const tasks = records(tasksSnap).filter((task) => task.projectId === projectId); const taskIds = new Set(tasks.map((task) => String(task.id))); const subtasks = records(subtaskSnap).filter((item) => taskIds.has(String(item.parentTaskId)) || item.projectId === projectId); const milestones = records(milestonesSnap).filter((item) => item.projectId === projectId); const dependencies = [...records(depsOutSnap), ...records(depsInSnap)].filter((item) => taskIds.has(String(item.sourceId)) || taskIds.has(String(item.targetId))); const files = records(filesSnap).filter((item) => item.projectId === projectId); const docs = records(docsSnap).filter((item) => item.projectId === projectId); const meetings = records(meetingsSnap).filter((item) => item.projectId === projectId); const risks = records(risksSnap).filter((item) => item.projectId === projectId); const decisions = records(decisionsSnap).filter((item) => item.projectId === projectId); const activities = records(activitiesSnap).filter((item) => (item.entityType === 'project' && item.entityId === projectId) || (item.payload && JSON.stringify(item.payload).includes(projectId))).slice(0, 50); const goals = records(goalsSnap).filter((item) => item.projectId === projectId || item.linkedProjectId === projectId); const allocations = records(allocationsSnap).filter((item) => item.projectId === projectId); const timeEntries = records(timeSnap).filter((item) => item.projectId === projectId);
  const now = Date.now(); const overdueTasks = tasks.filter((task) => !['done', 'completed', 'cancelled'].includes(String(task.status)) && millis(task.dueDate) > 0 && millis(task.dueDate) < now).length; const blockedTasks = tasks.filter((task) => ['blocked', 'waiting'].includes(String(task.status ?? '').toLowerCase())).length; const criticalTasks = tasks.filter((task) => ['critical', 'urgent'].includes(String(task.priority ?? '').toLowerCase()) && !['done', 'completed', 'cancelled'].includes(String(task.status ?? '').toLowerCase())).length; const allocated = allocations.reduce((sum, item) => sum + Number(item.allocatedHours ?? 0), 0); const available = allocations.reduce((sum, item) => sum + Number(item.availableHours ?? 0), 0); const budgetSpent = Number(project.budgetSpent ?? project.spent ?? 0); const budget = Number(project.budget ?? 0); const budgetPercent = budget > 0 ? (budgetSpent / budget) * 100 : 0; const dueDate = millis(project.dueDate); const deadlineDays = dueDate ? Math.ceil((dueDate - now) / 86_400_000) : 999; const latestActivity = activities.reduce((latest, item) => Math.max(latest, millis(item.createdAt)), 0); const recentActivityDays = latestActivity ? Math.floor((now - latestActivity) / 86_400_000) : 999; const milestoneVarianceDays = milestones.reduce((max, item) => Math.max(max, Number(item.varianceDays ?? 0)), 0); const health = calculateProjectHealth({ overdueTasks, blockedTasks, criticalTasks, capacityUtilization: calculateCapacity(available, allocated).utilization, milestoneVarianceDays, deadlineDays, recentActivityDays, budgetPercent, unresolvedRisks: risks.filter((risk) => !['resolved', 'closed', 'completed'].includes(String(risk.status ?? '').toLowerCase())).length }); await db.collection('projects').doc(projectId).update({ health: health.health, healthScore: health.score, healthReasons: health.reasons, healthUpdatedAt: FieldValue.serverTimestamp() }); return { project: { id: projectId, ...project, health: health.health, healthScore: health.score, healthReasons: health.reasons }, overview: { overdueTasks, blockedTasks, criticalTasks, capacity: calculateCapacity(available, allocated), budgetPercent, deadlineDays, milestoneVarianceDays, recentActivityDays }, tasks, subtasks, milestones, dependencies, files, docs, meetings, risks, decisions, goals, allocations, timeEntries };
}

export async function createGoal(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = GoalSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_GOAL'); if (parsed.data.parentGoalId) { const parent = await getAdminDb().collection('goals').doc(parsed.data.parentGoalId).get(); if (!parent.exists || parent.data()?.companyId !== identity.companyId) throw new Error('PARENT_GOAL_NOT_FOUND'); } const db = getAdminDb(); const ref = db.collection('goals').doc(); const now = FieldValue.serverTimestamp(); await db.runTransaction(async (transaction) => { transaction.create(ref, { id: ref.id, companyId: identity.companyId, ...parsed.data, progress: calculateGoalProgress(parsed.data.current, parsed.data.target), createdBy: identity.uid, updatedBy: identity.uid, createdAt: now, updatedAt: now, status: 'active', version: 1 }); await queueDomainEventTransaction(transaction, { eventName: 'goal.created', entityType: 'goal', entityId: ref.id, payload: { title: parsed.data.title, level: parsed.data.level, parentGoalId: parsed.data.parentGoalId }, metadata: { source: 'project-os' } }, { companyId: identity.companyId, actorId: identity.uid }); }); return { id: ref.id, ...(await ref.get()).data() }; }
export async function createKeyResult(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = KeyResultSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_KEY_RESULT'); const goal = await getAdminDb().collection('goals').doc(parsed.data.goalId).get(); if (!goal.exists || goal.data()?.companyId !== identity.companyId) throw new Error('GOAL_NOT_FOUND'); const db = getAdminDb(); const ref = db.collection('key_results').doc(); await ref.create({ id: ref.id, companyId: identity.companyId, ...parsed.data, progress: calculateGoalProgress(parsed.data.current, parsed.data.target), createdBy: identity.uid, updatedBy: identity.uid, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), status: 'active', version: 1 }); await recordAuditMutation({ identity, entity: 'key_result', entityId: ref.id, action: 'create', after: parsed.data }); return { id: ref.id, ...(await ref.get()).data() }; }
export async function updateGoalProgress(goalId: string, current: number) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); IdSchema.parse(goalId); const ref = getAdminDb().collection('goals').doc(goalId); const snapshot = await ref.get(); if (!snapshot.exists || snapshot.data()?.companyId !== identity.companyId) throw new Error('GOAL_NOT_FOUND'); const target = Number(snapshot.data()?.target ?? 0); const progress = calculateGoalProgress(current, target); await ref.update({ current, progress, updatedBy: identity.uid, updatedAt: FieldValue.serverTimestamp(), version: FieldValue.increment(1) }); await recordAuditMutation({ identity, entity: 'goal', entityId: goalId, action: 'update', before: snapshot.data(), after: { current, progress } }); return { id: goalId, current, target, progress }; }
export async function createAllocation(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = AllocationSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_ALLOCATION'); const member = await getAdminDb().collection('companies').doc(identity.companyId).collection('members').doc(parsed.data.userId).get(); if (!member.exists || member.data()?.status !== 'active') throw new Error('MEMBER_NOT_FOUND'); await assertProject(identity.companyId, parsed.data.projectId); const ref = getAdminDb().collection('capacity_allocations').doc(`${parsed.data.userId}_${parsed.data.projectId}_${parsed.data.weekStart}`); const capacity = calculateCapacity(parsed.data.availableHours, parsed.data.allocatedHours); await ref.set({ id: ref.id, companyId: identity.companyId, ...parsed.data, ...capacity, updatedBy: identity.uid, updatedAt: FieldValue.serverTimestamp(), createdBy: identity.uid, createdAt: FieldValue.serverTimestamp() }, { merge: true }); return { id: ref.id, ...parsed.data, ...capacity }; }
export async function getCapacity(weekStart?: string) { const identity = await requireIdentity(); const snapshot = await companyQuery('capacity_allocations', identity.companyId, 1000); const rows = records(snapshot).filter((item) => !weekStart || item.weekStart === weekStart); const byUser = new Map<string, { availableHours: number; allocatedHours: number }>(); for (const row of rows) { const current = byUser.get(String(row.userId)) ?? { availableHours: 0, allocatedHours: 0 }; current.availableHours += Number(row.availableHours ?? 0); current.allocatedHours += Number(row.allocatedHours ?? 0); byUser.set(String(row.userId), current); } return Array.from(byUser.entries()).map(([userId, value]) => ({ userId, ...calculateCapacity(value.availableHours, value.allocatedHours) })); }
export async function createTimeEntry(input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = TimeEntrySchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_TIME_ENTRY'); await assertProject(identity.companyId, parsed.data.projectId); let minutes = parsed.data.minutes; if (minutes === undefined && parsed.data.endedAt) minutes = Math.max(0, Math.round((Date.parse(parsed.data.endedAt) - Date.parse(parsed.data.startedAt)) / 60000)); if (minutes === undefined) throw new Error('TIME_ENTRY_DURATION_REQUIRED'); const ref = getAdminDb().collection('time_entries').doc(); await ref.create({ id: ref.id, companyId: identity.companyId, userId: identity.uid, ...parsed.data, minutes, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); await recordAuditMutation({ identity, entity: 'report', entityId: ref.id, action: 'create', after: { ...parsed.data, minutes } }); return { id: ref.id, ...parsed.data, minutes }; }
export async function startTimer(projectId: string, taskId?: string) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); await assertProject(identity.companyId, projectId); const existing = await getAdminDb().collection('active_timers').doc(identity.uid).get(); if (existing.exists) throw new Error('TIMER_ALREADY_RUNNING'); const ref = getAdminDb().collection('active_timers').doc(identity.uid); await ref.create({ id: identity.uid, companyId: identity.companyId, userId: identity.uid, projectId, taskId: taskId ?? null, startedAt: FieldValue.serverTimestamp(), status: 'running' }); return { projectId, taskId: taskId ?? null, started: true }; }
export async function stopTimer(note = '') { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const ref = getAdminDb().collection('active_timers').doc(identity.uid); const timer = await ref.get(); if (!timer.exists || timer.data()?.companyId !== identity.companyId) throw new Error('TIMER_NOT_RUNNING'); const data = timer.data() as Record<string, unknown>; const startedMs = millis(data.startedAt); const ended = Date.now(); const minutes = Math.max(1, Math.round((ended - startedMs) / 60000)); await ref.delete(); const entryRef = getAdminDb().collection('time_entries').doc(); await entryRef.create({ id: entryRef.id, companyId: identity.companyId, userId: identity.uid, projectId: data.projectId, taskId: data.taskId ?? null, startedAt: data.startedAt ?? Timestamp.fromMillis(startedMs), endedAt: Timestamp.fromMillis(ended), minutes, note, source: 'timer', createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); return { id: entryRef.id, minutes, projectId: data.projectId, taskId: data.taskId ?? null }; }
export async function updateProjectBudget(projectId: string, input: unknown) { const identity = await requirePermission(PERMISSIONS.OPERATIONS_MANAGE); const parsed = BudgetSchema.safeParse(input); if (!parsed.success) throw new Error('INVALID_BUDGET'); const { ref, data } = await assertProject(identity.companyId, projectId); const before = await ref.get(); await ref.update({ budgetSpent: parsed.data.spent, budgetCommitted: parsed.data.committed, updatedBy: identity.uid, updatedAt: FieldValue.serverTimestamp(), version: FieldValue.increment(1) }); await recordAuditMutation({ identity, entity: 'project', entityId: projectId, action: 'update', before: before.data(), after: parsed.data }); return { id: projectId, ...data, ...parsed.data }; }
