import 'server-only';
import { FieldValue } from 'firebase-admin/firestore';
import { z } from 'zod';
import { requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { getAdminDb } from '@/server/firebase/admin';
import { writeAuditEvent } from '@/server/repositories/audit';
import { createAutomation, createWorkflow, updateAutomation, updateWorkflow } from '@/server/services/automation-control';

export const WORKFLOW_NODE_TYPES=['trigger.record.created','trigger.record.updated','trigger.record.deleted','trigger.status.changed','trigger.form.submitted','trigger.approval.requested','trigger.approval.completed','trigger.schedule','trigger.cron','trigger.webhook','trigger.api','trigger.meeting.ended','trigger.document.changed','trigger.campaign.approved','action.create.record','action.update.record','action.delete.record','action.notify','action.email','action.assign.user','action.assign.team','action.request.approval','action.wait','action.condition','action.branch','action.join','action.webhook','action.integration','action.create.task','action.create.project','action.create.meeting','action.generate.document','action.ai','action.run.workflow','action.escalate'] as const;
const NodeSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,80}$/),type:z.enum(WORKFLOW_NODE_TYPES),label:z.string().min(1).max(180),x:z.number().min(-100000).max(100000).default(0),y:z.number().min(-100000).max(100000).default(0),config:z.record(z.unknown()).default({})});
const EdgeSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),source:z.string(),target:z.string(),label:z.string().max(180).optional()});
export const WorkflowGraphSchema=z.object({nodes:z.array(NodeSchema).max(100),edges:z.array(EdgeSchema).max(200),viewport:z.object({x:z.number(),y:z.number(),zoom:z.number().min(.1).max(3)}).optional()});
const VisualSchema=z.object({name:z.string().min(1).max(180),description:z.string().max(5000).default(''),graph:WorkflowGraphSchema,active:z.boolean().default(true)});
function graphIssues(graph:z.infer<typeof WorkflowGraphSchema>){const ids=new Set<string>();const issues:string[]=[];for(const n of graph.nodes){if(ids.has(n.id))issues.push(`Node duplicado: ${n.id}`);ids.add(n.id);}const seen=new Set<string>();const indegree=new Map<string,number>();const outgoing=new Map<string,string[]>();for(const n of graph.nodes){indegree.set(n.id,0);outgoing.set(n.id,[]);}for(const e of graph.edges){if(!ids.has(e.source)||!ids.has(e.target))issues.push(`Edge inválida: ${e.id}`);const k=`${e.source}>${e.target}>${e.label??''}`;if(seen.has(k))issues.push(`Edge duplicada: ${e.id}`);seen.add(k);if(ids.has(e.source)&&ids.has(e.target)){outgoing.get(e.source)!.push(e.target);indegree.set(e.target,(indegree.get(e.target)??0)+1);}}const q=graph.nodes.filter(n=>(indegree.get(n.id)??0)===0).map(n=>n.id);let visited=0;while(q.length){const id=q.shift()!;visited++;for(const t of outgoing.get(id)??[]){const d=(indegree.get(t)??1)-1;indegree.set(t,d);if(d===0)q.push(t);}}if(graph.nodes.length&&visited!==graph.nodes.length)issues.push('O workflow contém um ciclo.');if(graph.nodes.length&&!graph.nodes.some(n=>n.type.startsWith('trigger.')))issues.push('O workflow precisa de pelo menos um trigger.');return issues;}
function toStep(node:z.infer<typeof NodeSchema>,index:number){const base={id:`node_${index}_${node.id}`.slice(0,80),name:node.label,config:node.config};if(node.type.startsWith('trigger.'))return{...base,type:'log' as const,config:{message:`Trigger: ${node.type}`,...node.config}};if(['action.condition','action.branch'].includes(node.type))return{...base,type:'condition' as const,config:node.config};if(node.type==='action.webhook')return{...base,type:'http' as const,config:{method:'POST',...node.config}};if(node.type==='action.update.record')return{...base,type:'module.update' as const,config:node.config};if(node.type==='action.delete.record')return{...base,type:'module.delete' as const,config:node.config};const operations:Record<string,string>={'action.create.record':'create.record','action.create.task':'create.task','action.create.project':'create.project','action.create.meeting':'create.meeting','action.generate.document':'generate.document','action.notify':'notify','action.email':'email','action.ai':'ai','action.integration':'integration','action.request.approval':'request.approval','action.assign.user':'assign.user','action.assign.team':'assign.team','action.escalate':'escalate','action.run.workflow':'run.workflow','action.wait':'wait'};if(node.type==='action.join')return{...base,type:'action' as const,config:{operation:'join',...node.config}};if(operations[node.type])return{...base,type:'action' as const,config:{operation:operations[node.type],...node.config}};return{...base,type:'log' as const,config:node.config};}
function firstTrigger(nodes:z.infer<typeof NodeSchema>[]){return nodes.find(n=>n.type.startsWith('trigger.'));}
function triggerFromNode(node:z.infer<typeof NodeSchema>){const c=node.config;const t=node.type;if(t==='trigger.cron'||t==='trigger.schedule')return{type:'cron' as const,cron:String(c.cron??'0 9 * * 1-5'),timezone:String(c.timezone??'Africa/Maputo')};const map:Record<string,string>={'trigger.record.created':'record.created','trigger.record.updated':'record.updated','trigger.record.deleted':'record.deleted','trigger.status.changed':'record.status.changed','trigger.form.submitted':'form.submitted','trigger.approval.requested':'approval.requested','trigger.approval.completed':'approval.completed','trigger.meeting.ended':'meeting.ended','trigger.document.changed':'document.changed','trigger.campaign.approved':'campaign.approved','trigger.webhook':'webhook.received','trigger.api':'api.called'};return{type:'event' as const,eventName:String(c.eventName??map[t]??t),...(c.filter&&typeof c.filter==='object'?{filter:c.filter as Record<string,unknown>}: {})};}
export async function listVisualWorkflows(){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const s=await getAdminDb().collection('workflow_visuals').where('companyId','==',identity.companyId).limit(100).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function getVisualWorkflow(id:string):Promise<Record<string,unknown>>{const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const s=await getAdminDb().collection('workflow_visuals').doc(id).get();if(!s.exists||s.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');return{id:s.id,...(s.data() as Record<string,unknown>)};}
export async function saveVisualWorkflow(input:unknown,id?:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const parsed=VisualSchema.safeParse(input);if(!parsed.success)throw new Error('INVALID_VISUAL_WORKFLOW');const issues=graphIssues(parsed.data.graph);if(issues.length)throw new Error(`INVALID_GRAPH:${issues.join('|')}`);const db=getAdminDb();const ref=id?db.collection('workflow_visuals').doc(id):db.collection('workflow_visuals').doc();const current=id?await ref.get():null;if(id&&(!current?.exists||current.data()?.companyId!==identity.companyId))throw new Error('NOT_FOUND');const version=Number(current?.data()?.version??0)+1;await ref.set({id:ref.id,...parsed.data,companyId:identity.companyId,version,updatedBy:identity.uid,updatedAt:FieldValue.serverTimestamp(),createdBy:current?.data()?.createdBy??identity.uid,createdAt:current?.data()?.createdAt??FieldValue.serverTimestamp(),publishedVersion:current?.data()?.publishedVersion??null,publishedAt:current?.data()?.publishedAt??null,workflowId:current?.data()?.workflowId??null,automationId:current?.data()?.automationId??null},{merge:true});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'workflow.visual.save',resourceType:'workflow_visual',resourceId:ref.id,metadata:{version}});return{id:ref.id,version};}
export async function publishVisualWorkflow(id:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const visual=await getVisualWorkflow(id);const parsed=VisualSchema.safeParse(visual);if(!parsed.success)throw new Error('INVALID_VISUAL_WORKFLOW');const issues=graphIssues(parsed.data.graph);if(issues.length)throw new Error(`INVALID_GRAPH:${issues.join('|')}`);const steps=parsed.data.graph.nodes.filter(n=>!n.type.startsWith('trigger.')).map(toStep);if(!steps.length)steps.push({id:'visual-noop',type:'log' as const,name:'Visual workflow',config:{message:'Visual workflow sem ações executáveis.'}});let workflowId=typeof visual.workflowId==='string'?visual.workflowId:'';const result=workflowId?await updateWorkflow(workflowId,{name:parsed.data.name,description:parsed.data.description,active:parsed.data.active,graph:parsed.data.graph,steps}):await createWorkflow({name:parsed.data.name,description:parsed.data.description,active:parsed.data.active,graph:parsed.data.graph,steps});workflowId=String(result.id??workflowId);const triggerNode=firstTrigger(parsed.data.graph.nodes);let automationId:string|null=null;if(triggerNode){const existing=(await getAdminDb().collection('module_automations').where('companyId','==',identity.companyId).where('workflowId','==',workflowId).limit(1).get()).docs[0];const automationInput={name:`${parsed.data.name} automation`,description:`Trigger visual de ${parsed.data.name}`,active:parsed.data.active,workflowId,trigger:triggerFromNode(triggerNode),concurrencyLimit:5,rateLimitPerMinute:100};automationId=existing?existing.id:String((existing?await updateAutomation(existing.id,automationInput):await createAutomation(automationInput)).id);}
await getAdminDb().collection('workflow_visuals').doc(id).update({workflowId,automationId,publishedVersion:Number(visual.version??1),publishedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'workflow.visual.publish',resourceType:'workflow_visual',resourceId:id,metadata:{workflowId,automationId,version:visual.version}});return{visualId:id,workflowId,automationId,workflowVersion:result.version};}
export async function listExecutionObservability(limit=100){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const db=getAdminDb();const[runs,dead,queued,running,succeeded]=await Promise.all([db.collection('automation_runs').where('companyId','==',identity.companyId).limit(Math.min(limit,100)).get(),db.collection('automation_dead_letters').where('companyId','==',identity.companyId).limit(Math.min(limit,100)).get(),db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','pending').limit(100).get(),db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','running').limit(100).get(),db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','succeeded').limit(100).get()]);const list:Record<string,unknown>[]=runs.docs.map(d=>({id:d.id,...d.data()}));const durations=list.map(r=>{const a=r.startedAt;const b=r.finishedAt;if(a&&b&&typeof(a as {toMillis?:unknown}).toMillis==='function'&&typeof(b as {toMillis?:unknown}).toMillis==='function')return(b as {toMillis:()=>number}).toMillis()-(a as {toMillis:()=>number}).toMillis();return 0;}).filter(n=>n>0);const failed=list.filter(r=>['failed','dead'].includes(String(r.status))).length;return{runs:list,deadLetters:dead.docs.map(d=>({id:d.id,...d.data()})),metrics:{queued:queued.size,running:running.size,succeeded:succeeded.size,failed,averageExecutionMs:durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0,failureRate:list.length?Number((failed/list.length*100).toFixed(1)):0}};}
export async function cancelExecution(jobId:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const ref=getAdminDb().collection('automation_jobs').doc(jobId);await getAdminDb().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists||s.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');if(!['pending','running'].includes(String(s.data()?.status)))throw new Error('JOB_NOT_CANCELLABLE');tx.update(ref,{status:'cancelled',cancelledAt:FieldValue.serverTimestamp(),cancelledBy:identity.uid,updatedAt:FieldValue.serverTimestamp()})});return{ok:true};}
