import 'server-only';
import { FieldValue } from 'firebase-admin/firestore';
import { z } from 'zod';
import { requirePermission } from '@/server/authorization';
import { PERMISSIONS } from '@/server/authorization/permissions';
import { getAdminDb } from '@/server/firebase/admin';
import { writeAuditEvent } from '@/server/repositories/audit';
import { createWorkflow, updateWorkflow } from '@/server/services/automation-control';

export const WORKFLOW_NODE_TYPES=['trigger.record.created','trigger.record.updated','trigger.record.deleted','trigger.status.changed','trigger.form.submitted','trigger.approval.requested','trigger.approval.completed','trigger.schedule','trigger.cron','trigger.webhook','trigger.api','trigger.meeting.ended','trigger.document.changed','trigger.campaign.approved','action.create.record','action.update.record','action.delete.record','action.notify','action.email','action.assign.user','action.assign.team','action.request.approval','action.wait','action.condition','action.branch','action.webhook','action.integration','action.create.task','action.create.project','action.create.meeting','action.generate.document','action.ai','action.run.workflow','action.escalate'] as const;
export type WorkflowNodeType=typeof WORKFLOW_NODE_TYPES[number];
const NodeSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,80}$/),type:z.enum(WORKFLOW_NODE_TYPES),label:z.string().min(1).max(180),x:z.number().min(-100000).max(100000).default(0),y:z.number().min(-100000).max(100000).default(0),config:z.record(z.unknown()).default({})});
const EdgeSchema=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,100}$/),source:z.string(),target:z.string(),label:z.string().max(180).optional()});
export const WorkflowGraphSchema=z.object({nodes:z.array(NodeSchema).max(100),edges:z.array(EdgeSchema).max(200),viewport:z.object({x:z.number(),y:z.number(),zoom:z.number().min(.1).max(3)}).optional()});
const VisualSchema=z.object({name:z.string().min(1).max(180),description:z.string().max(5000).default(''),graph:WorkflowGraphSchema,active:z.boolean().default(true)});

function toStep(node:z.infer<typeof NodeSchema>,index:number){
 const base={id:`node_${index}_${node.id}`.slice(0,80),name:node.label,config:node.config};
 if(node.type.startsWith('trigger.')) return { ...base, type:'log' as const, config:{message:`Trigger: ${node.type}`,...node.config} };
 if(node.type==='action.condition'||node.type==='action.branch') return { ...base,type:'condition' as const,config:node.config };
 if(node.type==='action.webhook'||node.type==='action.email'||node.type==='action.http') return { ...base,type:'http' as const,config:{method:'POST',...node.config} };
 if(node.type==='action.create.record'||node.type==='action.create.task'||node.type==='action.create.project'||node.type==='action.create.meeting'||node.type==='action.generate.document'||node.type==='action.notify'||node.type==='action.ai'||node.type==='action.integration'||node.type==='action.request.approval'||node.type==='action.assign.user'||node.type==='action.assign.team'||node.type==='action.escalate'||node.type==='action.run.workflow'||node.type==='action.wait') return { ...base,type:'log' as const,config:{message:`Action: ${node.type}`,...node.config} };
 if(node.type==='action.update.record') return {...base,type:'module.update' as const,config:node.config};
 if(node.type==='action.delete.record') return {...base,type:'module.delete' as const,config:node.config};
 return {...base,type:'log' as const};
}
function graphIssues(graph:z.infer<typeof WorkflowGraphSchema>){const ids=new Set<string>();const issues:string[]=[];for(const n of graph.nodes){if(ids.has(n.id))issues.push(`Node duplicado: ${n.id}`);ids.add(n.id)};for(const e of graph.edges)if(!ids.has(e.source)||!ids.has(e.target))issues.push(`Edge inválida: ${e.id}`);if(graph.nodes.length&&!graph.nodes.some(n=>n.type.startsWith('trigger.')))issues.push('O workflow precisa de pelo menos um trigger.');return issues;}

export async function listVisualWorkflows(){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const s=await getAdminDb().collection('workflow_visuals').where('companyId','==',identity.companyId).limit(100).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function getVisualWorkflow(id:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const s=await getAdminDb().collection('workflow_visuals').doc(id).get();if(!s.exists||s.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');return{id:s.id,...s.data()};}
export async function saveVisualWorkflow(input:unknown,id?:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const parsed=VisualSchema.safeParse(input);if(!parsed.success)throw new Error('INVALID_VISUAL_WORKFLOW');const issues=graphIssues(parsed.data.graph);if(issues.length)throw new Error(`INVALID_GRAPH:${issues.join('|')}`);const db=getAdminDb();const ref=id?db.collection('workflow_visuals').doc(id):db.collection('workflow_visuals').doc();const current=id?await ref.get():null;if(id&&(!current?.exists||current.data()?.companyId!==identity.companyId))throw new Error('NOT_FOUND');const version=Number(current?.data()?.version??0)+1;await ref.set({id:ref.id,...parsed.data,companyId:identity.companyId,version,updatedBy:identity.uid,updatedAt:FieldValue.serverTimestamp(),createdBy:current?.data()?.createdBy??identity.uid,createdAt:current?.data()?.createdAt??FieldValue.serverTimestamp(),publishedVersion:current?.data()?.publishedVersion??null,publishedAt:current?.data()?.publishedAt??null},{merge:true});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'workflow.visual.save',resourceType:'workflow_visual',resourceId:ref.id,metadata:{version}});return{id:ref.id,version};}
export async function publishVisualWorkflow(id:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const visual=await getVisualWorkflow(id);const parsed=VisualSchema.safeParse(visual);if(!parsed.success)throw new Error('INVALID_VISUAL_WORKFLOW');const issues=graphIssues(parsed.data.graph);if(issues.length)throw new Error(`INVALID_GRAPH:${issues.join('|')}`);const steps=parsed.data.graph.nodes.filter(n=>!n.type.startsWith('trigger.')).map(toStep);if(!steps.length)steps.push({id:'visual-noop',type:'log' as const,name:'Visual workflow',config:{message:'Visual workflow sem ações executáveis.'}});let workflowId=typeof visual.workflowId==='string'?visual.workflowId:'';const workflowInput={name:parsed.data.name,description:parsed.data.description,active:parsed.data.active,steps};let result;if(workflowId)result=await updateWorkflow(workflowId,workflowInput);else{result=await createWorkflow(workflowInput);workflowId=String(result.id);}const db=getAdminDb();await db.collection('workflow_visuals').doc(id).update({workflowId,publishedVersion:Number(visual.version??1),publishedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});await writeAuditEvent({companyId:identity.companyId,actorId:identity.uid,action:'workflow.visual.publish',resourceType:'workflow_visual',resourceId:id,metadata:{workflowId,version:visual.version}});return{visualId:id,workflowId,workflowVersion:result.version};}

export async function listExecutionObservability(limit=100){const identity=await requirePermission(PERMISSIONS.AUTOMATION_READ);const db=getAdminDb();const [runs,dead,queued,running,succeeded]=await Promise.all([
 db.collection('automation_runs').where('companyId','==',identity.companyId).limit(Math.min(limit,100)).get(),
 db.collection('automation_dead_letters').where('companyId','==',identity.companyId).limit(Math.min(limit,100)).get(),
 db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','pending').limit(100).get(),
 db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','running').limit(100).get(),
 db.collection('automation_jobs').where('companyId','==',identity.companyId).where('status','==','succeeded').limit(100).get()
 ]);const list=runs.docs.map(d=>({id:d.id,...d.data()}));const durations=list.map(r=>{const a=r.startedAt;const b=r.finishedAt;if(a&&b&&typeof a.toMillis==='function'&&typeof b.toMillis==='function')return b.toMillis()-a.toMillis();return 0}).filter(n=>n>0);const failed=list.filter(r=>['failed','dead'].includes(String((r as Record<string,unknown>).status))).length;return{runs:list,deadLetters:dead.docs.map(d=>({id:d.id,...d.data()})),metrics:{queued:queued.size,running:running.size,succeeded:succeeded.size,failed,averageExecutionMs:durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0,failureRate:list.length?Number((failed/list.length*100).toFixed(1)):0}};}
export async function cancelExecution(jobId:string){const identity=await requirePermission(PERMISSIONS.AUTOMATION_MANAGE);const ref=getAdminDb().collection('automation_jobs').doc(jobId);await getAdminDb().runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists||s.data()?.companyId!==identity.companyId)throw new Error('NOT_FOUND');if(!['pending','running'].includes(String(s.data()?.status)))throw new Error('JOB_NOT_CANCELLABLE');tx.update(ref,{status:'cancelled',cancelledAt:FieldValue.serverTimestamp(),cancelledBy:identity.uid,updatedAt:FieldValue.serverTimestamp()})});return{ok:true};}
