'use client';
import { useEffect, useRef, useState } from 'react';
import { Camera, CircleStop, Link2, Plus, Save, Square, StickyNote, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';

type Obj={id:string;type:'note'|'shape'|'task'|'project'|'workflow'|'person';x:number;y:number;w:number;h:number;text?:string;refType?:string;refId?:string};type Board={id:string;name:string;objects:Obj[];edges:Array<{id:string;source:string;target:string;label?:string}>};
export default function WhiteboardClipsView(){const{toast}=useToast();const[boards,setBoards]=useState<Board[]>([]);const[selected,setSelected]=useState<Board|null>(null);const[name,setName]=useState('Oryon Whiteboard');const[recording,setRecording]=useState(false);const[clipTitle,setClipTitle]=useState('Oryon Clip');const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
 useEffect(()=>{fetch('/api/collaboration?resource=whiteboards',{cache:'no-store'}).then(r=>r.json()).then(p=>{if(Array.isArray(p.data))setBoards(p.data)}).catch(()=>undefined)},[]);
 const add=(type:Obj['type'])=>{setSelected(b=>({...b!,objects:[...(b?.objects??[]),{id:`o_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,type,x:120+(b?.objects.length??0)*25,y:120+(b?.objects.length??0)*25,w:180,h:80,text:type==='note'?'Nova nota':type.toUpperCase(),refType:type==='task'?'task':type==='project'?'project':type==='workflow'?'workflow':undefined,refId:undefined}],edges:b?.edges??[],id:b?.id??'',name:b?.name??name} as Board)))};
 const save=async()=>{if(!selected)return;const r=await fetch('/api/collaboration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'whiteboard',input:{id:selected.id||undefined,name:selected.name||name,objects:selected.objects,edges:selected.edges}})});const p=await r.json();if(!r.ok)throw new Error(p.error);setSelected(p.data);setBoards(v=>[p.data,...v.filter(x=>x.id!==p.data.id)]);toast({title:'Whiteboard guardado'})};
 const start=async()=>{try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const mr=new MediaRecorder(stream,{mimeType:'video/webm'});chunks.current=[];mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};mr.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const file=new File([new Blob(chunks.current,{type:'video/webm'})],`${clipTitle.replace(/[^a-z0-9-_]/gi,'_')}.webm`,{type:'video/webm'});const form=new FormData();form.append('file',file);const up=await fetch('/api/modules/cloud/upload',{method:'POST',body:form});const u=await up.json();if(!up.ok)throw new Error(u.error);const cr=await fetch('/api/collaboration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'clip',input:{title:clipTitle,cloudFileId:u.data.id,storagePath:u.data.storagePath,durationMs:0,sourceType:'screen'}})});const c=await cr.json();if(!cr.ok)throw new Error(c.error);toast({title:'Clip criado',description:c.data.id})};mr.start();recorder.current=mr;setRecording(true)}catch(e){toast({variant:'destructive',title:'Gravação falhou',description:e instanceof Error?e.message:'Erro'})}};
 const stop=()=>{recorder.current?.stop();recorder.current=null;setRecording(false)};
 const newBoard=()=>setSelected({id:'',name:'Oryon Whiteboard',objects:[],edges:[]});
 return <div className="p-4 md:p-6 space-y-5"><div><div className="text-sm text-muted-foreground">Collaboration</div><h1 className="text-3xl font-bold mt-1">Whiteboard + Clips</h1><p className="text-muted-foreground">Quadro visual ligado a objetos reais e gravação de ecrã com upload seguro.</p></div><div className="grid xl:grid-cols-[260px_1fr] gap-4"><Card><CardHeader><CardTitle className="text-sm">Boards</CardTitle></CardHeader><CardContent className="space-y-2"><Button className="w-full" onClick={newBoard}><Plus className="h-4 w-4 mr-2"/>Novo whiteboard</Button>{boards.map(b=><Button key={b.id} variant={selected?.id===b.id?'secondary':'outline'} className="w-full justify-start" onClick={()=>setSelected(b)}>{b.name}</Button>)}</CardContent></Card><div className="space-y-4">{selected?<Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{selected.name||name}</CardTitle><div className="flex gap-2"><Button variant="outline" onClick={()=>add('note')}><StickyNote className="h-4 w-4 mr-2"/>Post-it</Button><Button variant="outline" onClick={()=>add('task')}>Task</Button><Button variant="outline" onClick={()=>add('project')}>Project</Button><Button variant="outline" onClick={()=>add('workflow')}><Link2 className="h-4 w-4 mr-2"/>Workflow</Button><Button onClick={()=>void save()}><Save className="h-4 w-4 mr-2"/>Guardar</Button></div></CardHeader><CardContent><Input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})} className="mb-3"/><div className="relative h-[620px] overflow-hidden rounded-xl border bg-[radial-gradient(circle,_hsl(var(--muted-foreground)/.15)_1px,_transparent_1px)] [background-size:24px_24px]">{selected.objects.map((o,i)=><div key={o.id} className="absolute rounded-lg border bg-background shadow-sm p-3" style={{left:o.x,top:o.y,width:o.w,height:o.h}}><Badge variant="secondary">{o.type}</Badge><div className="text-sm font-medium mt-2">{o.text}</div><div className="text-[10px] text-muted-foreground mt-1">{o.refId?'Linked object':'Object livre'}</div></div>)}</div></CardContent></Card>:<Card><CardContent className="py-16 text-center text-muted-foreground"><Square className="h-8 w-8 mx-auto mb-2"/>Crie ou selecione um whiteboard.</CardContent></Card>}<Card><CardHeader><CardTitle className="flex items-center gap-2"><Video className="h-4 w-4"/>Clips</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><Input className="max-w-sm" value={clipTitle} onChange={e=>setClipTitle(e.target.value)}/><Button variant={recording?'destructive':'default'} onClick={recording?stop:()=>void start()}>{recording?<CircleStop className="h-4 w-4 mr-2"/>:<Camera className="h-4 w-4 mr-2"/>}{recording?'Parar gravação':'Gravar ecrã'}</Button><span className="text-xs text-muted-foreground">O browser pede autorização para capturar o ecrã.</span></CardContent></Card></div></div></div>}
