'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { GitBranch, Minus, Plus, Save, Send, Trash2, Undo2, Redo2, MousePointer2, Link2, Play, Maximize2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';

type Node={id:string;type:string;label:string;x:number;y:number;config:Record<string,unknown>};
type Edge={id:string;source:string;target:string;label?:string};
type Visual={id:string;name:string;description?:string;version?:number;workflowId?:string;automationId?:string;graph:{nodes:Node[];edges:Edge[];viewport?:{x:number;y:number;zoom:number}}};

const PALETTE=[['trigger.form.submitted','Form submitted'],['trigger.record.created','Record created'],['trigger.record.updated','Record updated'],['trigger.status.changed','Status changed'],['trigger.schedule','Schedule'],['trigger.webhook','Webhook'],['trigger.api','API'],['action.create.task','Create task'],['action.create.project','Create project'],['action.request.approval','Request approval'],['action.notify','Send notification'],['action.email','Send email'],['action.assign.user','Assign user'],['action.assign.team','Assign team'],['action.condition','Condition'],['action.branch','Branch'],['action.join','Join'],['action.update.record','Update record'],['action.delete.record','Delete record'],['action.webhook','Call webhook'],['action.integration','Integration'],['action.ai','Invoke AI'],['action.wait','Wait'],['action.run.workflow','Run workflow'],['action.escalate','Escalate']];
const GRID=24;
function labelFor(type:string){return PALETTE.find(x=>x[0]===type)?.[1]??type;}
function isTrigger(type:string){return type.startsWith('trigger.');}
function isJoin(type:string){return type==='action.join';}
function nodeColor(type:string){if(type.startsWith('trigger.'))return 'border-primary/60 bg-primary/5';if(type==='action.condition'||type==='action.branch')return 'border-amber-500/50 bg-amber-500/5';if(type==='action.join')return 'border-violet-500/50 bg-violet-500/5';return 'border-border bg-background';}

export default function VisualWorkflowBuilder(){
  const {toast}=useToast();
  const canvasRef=useRef<HTMLDivElement>(null);
  const dragRef=useRef<{id:string;dx:number;dy:number}|null>(null);
  const panRef=useRef<{sx:number;sy:number;vx:number;vy:number}|null>(null);
  const [items,setItems]=useState<Visual[]>([]);const[selected,setSelected]=useState<Visual|null>(null);const[name,setName]=useState('Novo workflow visual');const[desc,setDesc]=useState('');const[nodes,setNodes]=useState<Node[]>([]);const[edges,setEdges]=useState<Edge[]>([]);const[nodeId,setNodeId]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[tool,setTool]=useState<'select'|'connect'>('select');const[connectFrom,setConnectFrom]=useState<string|null>(null);const[viewport,setViewport]=useState({x:60,y:40,zoom:1});
  const historyRef=useRef<{nodes:Node[];edges:Edge[];viewport:typeof viewport}[]>([]);const futureRef=useRef<typeof historyRef.current>([]);const[historyTick,setHistoryTick]=useState(0);
  const snapshot=useCallback(()=>({nodes:structuredClone(nodes),edges:structuredClone(edges),viewport:{...viewport}}),[nodes,edges,viewport]);
  const pushHistory=useCallback(()=>{historyRef.current=[...historyRef.current.slice(-39),snapshot()];futureRef.current=[];setHistoryTick(v=>v+1);},[snapshot]);
  const load=async()=>{setLoading(true);try{const r=await fetch('/api/workflow-platform?resource=visual-workflows',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error);setItems(Array.isArray(p.data)?p.data:[])}catch(e){toast({variant:'destructive',title:'Erro',description:e instanceof Error?e.message:'Falha'})}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
  const add=(type:string)=>{pushHistory();const id=`n_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;const next={id,type,label:labelFor(type),x:Math.round(((-viewport.x)+180)/viewport.zoom/GRID)*GRID,y:Math.round(((-viewport.y)+140)/viewport.zoom/GRID)*GRID,config:{}};setNodes(n=>[...n,next]);setNodeId(id);};
  const remove=()=>{if(!nodeId)return;pushHistory();setNodes(n=>n.filter(x=>x.id!==nodeId));setEdges(e=>e.filter(x=>x.source!==nodeId&&x.target!==nodeId));setNodeId('');setConnectFrom(null)};
  const updateCurrent=(patch:Partial<Node>)=>{pushHistory();setNodes(n=>n.map(x=>x.id===nodeId?{...x,...patch}:x));};
  const reset=()=>{pushHistory();setSelected(null);setName('Novo workflow visual');setDesc('');setNodes([]);setEdges([]);setNodeId('');setConnectFrom(null);setViewport({x:60,y:40,zoom:1});};
  const undo=()=>{const prev=historyRef.current.pop();if(!prev)return;futureRef.current=[snapshot(),...futureRef.current];setNodes(prev.nodes);setEdges(prev.edges);setViewport(prev.viewport);setHistoryTick(v=>v+1);};
  const redo=()=>{const next=futureRef.current.shift();if(!next)return;historyRef.current=[...historyRef.current,snapshot()];setNodes(next.nodes);setEdges(next.edges);setViewport(next.viewport);setHistoryTick(v=>v+1);};
  const screenToWorld=(clientX:number,clientY:number)=>{const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return{x:0,y:0};return{x:(clientX-rect.left-viewport.x)/viewport.zoom,y:(clientY-rect.top-viewport.y)/viewport.zoom};};
  const onPointerDownNode=(e:React.PointerEvent,id:string)=>{e.stopPropagation();const n=nodes.find(x=>x.id===id);if(!n)return;if(tool==='connect'){if(connectFrom&&connectFrom!==id){pushHistory();setEdges(es=>es.some(x=>x.source===connectFrom&&x.target===id)?es:[...es,{id:`e_${connectFrom}_${id}_${Date.now()}`,source:connectFrom,target:id}]);setConnectFrom(null);}else setConnectFrom(id);setNodeId(id);return;}setNodeId(id);const w=screenToWorld(e.clientX,e.clientY);dragRef.current={id,dx:w.x-n.x,dy:w.y-n.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);};
  const onPointerMove=(e:React.PointerEvent)=>{if(dragRef.current){const w=screenToWorld(e.clientX,e.clientY);const d=dragRef.current;setNodes(ns=>ns.map(n=>n.id===d.id?{...n,x:Math.round((w.x-d.dx)/GRID)*GRID,y:Math.round((w.y-d.dy)/GRID)*GRID}:n));}else if(panRef.current){const p=panRef.current;setViewport(v=>({...v,x:p.vx+(e.clientX-p.sx),y:p.vy+(e.clientY-p.sy)}));}};
  const endPointer=(e:React.PointerEvent)=>{if(dragRef.current){pushHistory();dragRef.current=null;(e.currentTarget as HTMLElement).releasePointerCapture?.(e.pointerId);}if(panRef.current)panRef.current=null;};
  const onCanvasDown=(e:React.PointerEvent)=>{if(e.button===1||e.shiftKey){panRef.current={sx:e.clientX,sy:e.clientY,vx:viewport.x,vy:viewport.y};return;}if(tool==='connect')setConnectFrom(null);};
  const onWheel=(e:React.WheelEvent)=>{e.preventDefault();const delta=e.deltaY<0?1.08:.92;setViewport(v=>({...v,zoom:Math.max(.4,Math.min(2,v.zoom*delta))}))};
  const connectEdge=(id:string)=>{setEdges(es=>es.filter(e=>e.id!==id));};
  const save=async()=>{setSaving(true);try{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'visual.save',id:selected?.id,input:{name,description:desc,active:true,graph:{nodes,edges,viewport}}})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Falha');toast({title:'Guardado',description:`Versão ${p.data.version}`});await load()}catch(e){toast({variant:'destructive',title:'Erro',description:e instanceof Error?e.message:'Falha'})}finally{setSaving(false)}};
  const publish=async(id:string)=>{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'visual.publish',id})});const p=await r.json();if(!r.ok)toast({variant:'destructive',title:'Publicação falhou',description:p.error});else toast({title:'Workflow publicado',description:`Workflow ${p.data.workflowId} · automation ${p.data.automationId??'n/a'}`});await load()};
  const testRun=async(v:Visual)=>{if(!v.automationId){toast({variant:'destructive',title:'Test run indisponível',description:'Publique o workflow primeiro.'});return;}try{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'execution.run',automationId:v.automationId,payload:{testRun:true,source:'visual-workflow-builder',visualId:v.id}})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Falha');toast({title:'Test run enqueued',description:`Job ${p.data.jobId}`});}catch(e){toast({variant:'destructive',title:'Test run falhou',description:e instanceof Error?e.message:'Falha'})}};
  const edit=(v:Visual)=>{setSelected(v);setName(v.name);setDesc(v.description??'');setNodes(v.graph?.nodes??[]);setEdges(v.graph?.edges??[]);setNodeId(v.graph?.nodes?.[0]?.id??'');setViewport(v.graph?.viewport??{x:60,y:40,zoom:1});historyRef.current=[];futureRef.current=[];setHistoryTick(v=>v+1)};
  const nodeMap=useMemo(()=>new Map(nodes.map(n=>[n.id,n])),[nodes]);
  const pathForEdge=(e:Edge)=>{const s=nodeMap.get(e.source);const t=nodeMap.get(e.target);if(!s||!t)return'';const sx=s.x+270,sy=s.y+48,tx=t.x,ty=t.y+48;const dx=Math.max(70,Math.abs(tx-sx)*.45);return`M ${sx} ${sy} C ${sx+dx} ${sy}, ${tx-dx} ${ty}, ${tx} ${ty}`;};
  return <div className="p-4 md:p-6 space-y-5 select-none"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-sm text-muted-foreground">Automation Platform</div><h1 className="text-3xl font-bold mt-1">Visual Workflow Builder</h1><p className="text-muted-foreground">Canvas profissional com posicionamento livre, conexões SVG, branches, joins, zoom, pan, versionamento e test run.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={reset}><Maximize2 className="h-4 w-4 mr-2"/>Novo</Button><Button variant={tool==='select'?'default':'outline'} onClick={()=>setTool('select')}><MousePointer2 className="h-4 w-4 mr-2"/>Select</Button><Button variant={tool==='connect'?'default':'outline'} onClick={()=>setTool('connect')}><Link2 className="h-4 w-4 mr-2"/>Connect</Button><Button variant="outline" onClick={undo} disabled={!historyRef.current.length}><Undo2 className="h-4 w-4"/></Button><Button variant="outline" onClick={redo} disabled={!futureRef.current.length}><Redo2 className="h-4 w-4"/></Button><Button onClick={()=>void save()} disabled={saving}><Save className="h-4 w-4 mr-2"/>Guardar</Button></div></div>
    <div className="grid xl:grid-cols-[250px_1fr_320px] gap-4">
      <Card className="h-[760px] overflow-hidden"><CardHeader><CardTitle className="text-sm">Node palette</CardTitle></CardHeader><CardContent className="space-y-2 overflow-y-auto max-h-[680px]">{PALETTE.map(([t,l])=><Button key={t} variant="outline" className="w-full justify-start text-xs" onClick={()=>add(t)}><Plus className="h-3 w-3 mr-2"/>{l}</Button>)}</CardContent></Card>
      <Card className="h-[760px] overflow-hidden"><CardHeader className="py-3 flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><GitBranch className="h-4 w-4"/>Canvas <Badge variant="secondary">{nodes.length} nodes · {edges.length} edges · {Math.round(viewport.zoom*100)}%</Badge></CardTitle><div className="flex gap-1"><Button size="icon" variant="outline" onClick={()=>setViewport(v=>({...v,zoom:Math.max(.4,v.zoom*.9)}))}><Minus className="h-4 w-4"/></Button><Button size="icon" variant="outline" onClick={()=>setViewport(v=>({...v,zoom:Math.min(2,v.zoom*1.1)}))}><Plus className="h-4 w-4"/></Button></div></CardHeader><CardContent className="p-0 h-[700px]"><div ref={canvasRef} className="relative h-full overflow-hidden bg-[radial-gradient(circle,_hsl(var(--muted-foreground)/.16)_1px,_transparent_1px)] [background-size:24px_24px] cursor-crosshair" onPointerDown={onCanvasDown} onPointerMove={onPointerMove} onPointerUp={endPointer} onPointerCancel={endPointer} onWheel={onWheel}>
        <svg className="absolute inset-0 h-full w-full pointer-events-none"><g transform={`translate(${viewport.x} ${viewport.y}) scale(${viewport.zoom})`}>{edges.map(e=><g key={e.id}><path d={pathForEdge(e)} fill="none" stroke="hsl(var(--primary))" strokeWidth={2.2} markerEnd="url(#arrow)"/><text x={(nodeMap.get(e.source)?.x??0)+285} y={(nodeMap.get(e.source)?.y??0)+28} className="fill-muted-foreground" fontSize="11">{e.label??''}</text></g>)}<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="hsl(var(--primary))"/></marker></defs></g></svg>
        <div className="absolute inset-0" style={{transform:`translate(${viewport.x}px,${viewport.y}px) scale(${viewport.zoom})`,transformOrigin:'0 0'}}>{nodes.map(n=><div key={n.id} onPointerDown={e=>onPointerDownNode(e,n.id)} className={`absolute w-[270px] rounded-xl border shadow-sm ${nodeColor(n.type)} ${nodeId===n.id?'ring-2 ring-primary/40':''} ${connectFrom===n.id?'ring-2 ring-amber-400':''}`} style={{left:n.x,top:n.y}}><div className="flex items-center gap-2 p-3 border-b bg-background/60 rounded-t-xl"><Badge variant="secondary" className="text-[10px]">{isTrigger(n.type)?'TRIGGER':isJoin(n.type)?'JOIN':'ACTION'}</Badge><span className="font-medium text-sm truncate">{n.label}</span><span className="ml-auto text-[9px] text-muted-foreground">{n.id}</span></div><div className="relative p-3 text-[11px] text-muted-foreground min-h-[54px]"><div>{n.type}</div>{isJoin(n.type)&&<div>joinExpected: {String(n.config.joinExpected??'auto')}</div>}{(n.type==='action.condition'||n.type==='action.branch')&&<div>route: {String(n.config.field??'field')} {String(n.config.operator??'equals')} {String(n.config.value??'')}</div>}<button aria-label="input" className="absolute -left-2 top-1/2 -translate-y-1/2 h-4 w-4 rounded-full border bg-background" onPointerDown={e=>{e.stopPropagation();if(tool==='connect'&&connectFrom&&connectFrom!==n.id){pushHistory();setEdges(es=>es.some(x=>x.source===connectFrom&&x.target===n.id)?es:[...es,{id:`e_${connectFrom}_${n.id}_${Date.now()}`,source:connectFrom,target:n.id}]);setConnectFrom(null);}}}/><button aria-label="output" className="absolute -right-2 top-1/2 -translate-y-1/2 h-4 w-4 rounded-full border bg-primary" onPointerDown={e=>{e.stopPropagation();setTool('connect');setConnectFrom(n.id);setNodeId(n.id);}}/></div></div>)}</div>
        {!nodes.length&&<div className="absolute inset-0 flex items-center justify-center text-sm text-muted-foreground pointer-events-none">Adicione um trigger, arraste os nodes livremente e ligue os handles. Shift + drag move o canvas.</div>}
        <div className="absolute bottom-3 left-3 rounded-lg border bg-background/90 px-3 py-2 text-[11px] text-muted-foreground">Select: mover · Connect: handle direito → handle esquerdo · Shift/middle: pan · Wheel: zoom</div>
      </div></CardContent></Card>
      <Card className="h-[760px] overflow-hidden"><CardHeader><CardTitle>Properties</CardTitle></CardHeader><CardContent className="space-y-3 overflow-y-auto max-h-[680px]">{nodes.find(n=>n.id===nodeId)?<><Input value={nodes.find(n=>n.id===nodeId)!.label} onChange={e=>updateCurrent({label:e.target.value})}/><Textarea value={JSON.stringify(nodes.find(n=>n.id===nodeId)!.config,null,2)} onChange={e=>{try{updateCurrent({config:JSON.parse(e.target.value)})}catch{}}} className="font-mono text-xs min-h-[220px]"/><div className="text-xs text-muted-foreground">Node type: {nodes.find(n=>n.id===nodeId)!.type}</div><Button variant="destructive" onClick={remove}><Trash2 className="h-4 w-4 mr-2"/>Remover node</Button></>:<div className="text-sm text-muted-foreground">Seleccione um node no canvas.</div>}<div className="pt-3 border-t"><div className="text-xs font-semibold mb-2">Connections</div>{edges.filter(e=>e.source===nodeId||e.target===nodeId).map(e=><div key={e.id} className="flex items-center gap-2 text-xs py-1"><span className="truncate flex-1">{e.source} → {e.target}</span><Input className="w-20 h-7 text-[10px]" value={e.label??''} onChange={ev=>setEdges(es=>es.map(x=>x.id===e.id?{...x,label:ev.target.value||undefined}:x))}/><Button size="icon" variant="ghost" onClick={()=>connectEdge(e.id)}><Trash2 className="h-3 w-3"/></Button></div>)}</div></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Workflow versions</CardTitle></CardHeader><CardContent>{loading?<div>A carregar...</div>:items.length===0?<div className="text-sm text-muted-foreground">Nenhum workflow visual.</div>:<div className="space-y-2">{items.map(v=><div key={v.id} className="rounded-lg border p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="font-medium">{v.name}</div><div className="text-xs text-muted-foreground">v{v.version??1} · {v.graph?.nodes?.length??0} nodes · {v.workflowId?'publicado':'rascunho'} · {v.automationId?'automation activa':'sem automation'}</div></div><div className="flex gap-2"><Button variant="outline" onClick={()=>edit(v)}>Editar</Button><Button onClick={()=>void publish(v.id)}><Send className="h-4 w-4 mr-2"/>Publicar</Button><Button variant="secondary" onClick={()=>void testRun(v)}><Play className="h-4 w-4 mr-2"/>Testar</Button></div></div>)}</div>}</CardContent></Card>
  </div>;
}
