'use client';
import { useEffect, useMemo, useState } from 'react';
import { GitBranch, Play, Plus, Save, Send, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
type Node={id:string;type:string;label:string;x:number;y:number;config:Record<string,unknown>};type Edge={id:string;source:string;target:string;label?:string};type Visual={id:string;name:string;description?:string;version?:number;workflowId?:string;automationId?:string;graph:{nodes:Node[];edges:Edge[]}};
const PALETTE=[['trigger.form.submitted','Form submitted'],['trigger.record.created','Record created'],['trigger.status.changed','Status changed'],['trigger.schedule','Schedule'],['trigger.webhook','Webhook'],['action.create.task','Create task'],['action.request.approval','Request approval'],['action.notify','Send notification'],['action.assign.user','Assign user'],['action.condition','Condition'],['action.branch','Branch'],['action.update.record','Update record'],['action.delete.record','Delete record'],['action.webhook','Call webhook'],['action.ai','Invoke AI'],['action.wait','Wait'],['action.run.workflow','Run workflow'],['action.escalate','Escalate']];
export default function VisualWorkflowBuilder(){const{toast}=useToast();const[items,setItems]=useState<Visual[]>([]);const[selected,setSelected]=useState<Visual|null>(null);const[name,setName]=useState('Novo workflow visual');const[desc,setDesc]=useState('');const[nodes,setNodes]=useState<Node[]>([]);const[edges,setEdges]=useState<Edge[]>([]);const[nodeId,setNodeId]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/workflow-platform?resource=visual-workflows',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error);setItems(Array.isArray(p.data)?p.data:[])}catch(e){toast({variant:'destructive',title:'Erro',description:e instanceof Error?e.message:'Falha'})}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const add=(type:string)=>{const id=`n_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;const next={id,type,label:PALETTE.find(x=>x[0]===type)?.[1]??type,x:30+(nodes.length%3)*250,y:50+Math.floor(nodes.length/3)*130,config:{}};setNodes(n=>[...n,next]);if(nodes.length){const prev=nodes[nodes.length-1];setEdges(e=>[...e,{id:`e_${prev.id}_${id}`,source:prev.id,target:id}])}setNodeId(id)};
 const remove=()=>{if(!nodeId)return;setNodes(n=>n.filter(x=>x.id!==nodeId));setEdges(e=>e.filter(x=>x.source!==nodeId&&x.target!==nodeId));setNodeId('')};const current=nodes.find(n=>n.id===nodeId);const updateCurrent=(p:Partial<Node>)=>setNodes(n=>n.map(x=>x.id===nodeId?{...x,...p}:x));const reset=()=>{setSelected(null);setName('Novo workflow visual');setDesc('');setNodes([]);setEdges([]);setNodeId('')};
 const save=async()=>{setSaving(true);try{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'visual.save',id:selected?.id,input:{name,description:desc,active:true,graph:{nodes,edges,viewport:{x:0,y:0,zoom:1}}}})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Falha');toast({title:'Guardado',description:`Versão ${p.data.version}`});await load()}catch(e){toast({variant:'destructive',title:'Erro',description:e instanceof Error?e.message:'Falha'})}finally{setSaving(false)}};
 const publish=async(id:string)=>{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'visual.publish',id})});const p=await r.json();if(!r.ok)toast({variant:'destructive',title:'Publicação falhou',description:p.error});else toast({title:'Workflow publicado',description:`Workflow ${p.data.workflowId} · automation ${p.data.automationId??'n/a'}`});await load()};
 const testRun=async(v:Visual)=>{if(!v.automationId){toast({variant:'destructive',title:'Test run indisponível',description:'Publique o workflow primeiro para criar a automação executável.'});return;}try{const r=await fetch('/api/workflow-platform',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'execution.run',automationId:v.automationId,payload:{testRun:true,source:'visual-workflow-builder'}})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Falha');toast({title:'Test run enqueued',description:`Job ${p.data.jobId} foi colocado na fila.`});}catch(e){toast({variant:'destructive',title:'Test run falhou',description:e instanceof Error?e.message:'Falha'})}};
 const edit=(v:Visual)=>{setSelected(v);setName(v.name);setDesc(v.description??'');setNodes(v.graph?.nodes??[]);setEdges(v.graph?.edges??[]);setNodeId(v.graph?.nodes?.[0]?.id??'')};const ordered=useMemo(()=>nodes.slice().sort((a,b)=>(a.y-b.y)||(a.x-b.x)),[nodes]);
 return <div className="p-6 space-y-6"><div className="flex flex-col gap-3 md:flex-row md:justify-between md:items-center"><div><div className="text-sm text-muted-foreground">Automation Platform</div><h1 className="text-3xl font-bold mt-1">Visual Workflow Builder</h1><p className="text-muted-foreground">Canvas, nodes, edges, properties, validation, versioning, publish e test run.</p></div><div className="flex gap-2"><Button variant="outline" onClick={reset}><Plus className="h-4 w-4 mr-2"/>Novo</Button><Button onClick={()=>void save()} disabled={saving}><Save className="h-4 w-4 mr-2"/>Guardar</Button></div></div>
 <div className="grid xl:grid-cols-[250px_1fr_300px] gap-5"><Card><CardHeader><CardTitle className="text-sm">Node palette</CardTitle></CardHeader><CardContent className="space-y-2">{PALETTE.map(([t,l])=><Button key={t} variant="outline" className="w-full justify-start text-xs" onClick={()=>add(t)}><Plus className="h-3 w-3 mr-2"/>{l}</Button>)}</CardContent></Card><Card className="min-h-[620px]"><CardHeader><CardTitle className="flex items-center gap-2"><GitBranch className="h-4 w-4"/>Canvas <Badge variant="secondary">{nodes.length} nodes · {edges.length} edges</Badge></CardTitle></CardHeader><CardContent><div className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/><Textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Descrição"/><div className="rounded-xl border border-dashed p-5 min-h-[450px] space-y-2">{ordered.map(n=><button key={n.id} onClick={()=>setNodeId(n.id)} className={`w-full rounded-lg border p-3 text-left ${nodeId===n.id?'border-primary bg-primary/5':''}`}><div className="flex items-center gap-2"><Badge>{n.type.startsWith('trigger')?'Trigger':'Action'}</Badge><span className="font-medium">{n.label}</span><span className="text-xs text-muted-foreground ml-auto">{n.id}</span></div></button>)}{!nodes.length&&<div className="h-64 flex items-center justify-center text-sm text-muted-foreground">Adicione um trigger e depois actions. As edges são criadas entre nodes em sequência.</div>}</div></div></CardContent></Card><Card><CardHeader><CardTitle>Properties</CardTitle></CardHeader><CardContent className="space-y-3">{current?<><Input value={current.label} onChange={e=>updateCurrent({label:e.target.value})}/><Textarea value={JSON.stringify(current.config,null,2)} onChange={e=>{try{updateCurrent({config:JSON.parse(e.target.value)})}catch{}}} className="font-mono text-xs min-h-[180px]"/><div className="text-xs text-muted-foreground">Node type: {current.type}</div><Button variant="destructive" onClick={remove}><Trash2 className="h-4 w-4 mr-2"/>Remover node</Button></>:<div className="text-sm text-muted-foreground">Seleccione um node no canvas.</div>}</CardContent></Card></div>
 <Card><CardHeader><CardTitle>Workflow versions</CardTitle></CardHeader><CardContent>{loading?<div>A carregar...</div>:items.length===0?<div className="text-sm text-muted-foreground">Nenhum workflow visual.</div>:<div className="space-y-2">{items.map(v=><div key={v.id} className="rounded-lg border p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="font-medium">{v.name}</div><div className="text-xs text-muted-foreground">v{v.version??1} · {v.graph?.nodes?.length??0} nodes · {v.workflowId?'publicado':'rascunho'} · {v.automationId?'automation activa':'sem automation'}</div></div><div className="flex gap-2"><Button variant="outline" onClick={()=>edit(v)}>Editar</Button><Button onClick={()=>void publish(v.id)}><Send className="h-4 w-4 mr-2"/>Publicar</Button><Button variant="secondary" onClick={()=>void testRun(v)}><Play className="h-4 w-4 mr-2"/>Testar</Button></div></div>)}</div>}</CardContent></Card></div>}
