'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Activity, CalendarDays, Clock3, DollarSign, GanttChartSquare, LayoutDashboard, Plus, RefreshCw, Target, Users, XCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

interface Row { id: string; [key: string]: unknown }
interface ProjectPayload { project: Row; overview: { overdueTasks: number; blockedTasks: number; criticalTasks: number; capacity: { availableHours: number; allocatedHours: number; utilization: number; overloadHours: number; underloadHours: number }; budgetPercent: number; deadlineDays: number; milestoneVarianceDays: number; recentActivityDays: number }; tasks: Row[]; subtasks: Row[]; milestones: Row[]; dependencies: Row[]; files: Row[]; docs: Row[]; meetings: Row[]; risks: Row[]; decisions: Row[]; goals: Row[]; allocations: Row[]; timeEntries: Row[] }
const tabs = [['overview','Overview',LayoutDashboard],['kanban','Kanban',LayoutDashboard],['timeline','Timeline',GanttChartSquare],['calendar','Calendar',CalendarDays],['resources','Resources',Users],['goals','Goals',Target],['risks','Risks',XCircle],['activity','Activity',Activity],['time','Time',Clock3],['budget','Budget',DollarSign]] as const;
function healthVariant(health: string) { return health === 'HEALTHY' ? 'secondary' : health === 'AT_RISK' ? 'outline' : 'destructive'; }
function dateLabel(value: unknown) { const date = typeof value === 'string' ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('pt-PT') : 'Sem data'; }
function statusLabel(value: unknown) { return String(value ?? 'active').replace(/_/g, ' ').replace(/-/g, ' '); }

export default function ProjectOsView() {
  const [workspaces,setWorkspaces] = useState<Row[]>([]); const [projectId,setProjectId] = useState(''); const [payload,setPayload] = useState<ProjectPayload|null>(null); const [tab,setTab] = useState('overview'); const [loading,setLoading] = useState(true); const [error,setError] = useState<string|null>(null);
  const [newWorkspace,setNewWorkspace]=useState(''); const [newProject,setNewProject]=useState(''); const [newGoal,setNewGoal]=useState(''); const [capacityUser,setCapacityUser]=useState(''); const [available,setAvailable]=useState('40'); const [allocated,setAllocated]=useState('20'); const [weekStart,setWeekStart]=useState(''); const [manualMinutes,setManualMinutes]=useState('60'); const [manualNote,setManualNote]=useState(''); const [timerRunning,setTimerRunning]=useState(false);
  async function api(resource:string, options?:RequestInit) { const response = await fetch(resource,{cache:'no-store',credentials:'include',...options}); if(!response.ok){const result=await response.json().catch(()=>({})); throw new Error(String(result.error??'REQUEST_FAILED'));} return response.json(); }
  async function loadWorkspaces(){const result=await api('/api/project-os?resource=workspaces');setWorkspaces(result.data);if(!projectId){const first=result.data.flatMap((w:Row)=>Array.isArray(w.projects)?w.projects as Row[]:[])[0];if(first?.id)setProjectId(String(first.id));}}
  async function loadProject(id=projectId){if(!id)return;const result=await api(`/api/project-os?resource=project&projectId=${encodeURIComponent(id)}`);setPayload(result.data);}
  async function refresh(){setLoading(true);setError(null);try{await loadWorkspaces();if(projectId)await loadProject();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[]); useEffect(()=>{if(projectId)void loadProject().catch(e=>setError(e instanceof Error?e.message:'Erro inesperado.'));},[projectId]);
  const selectedWorkspace=workspaces.find((w)=>Array.isArray(w.projects)&&(w.projects as Row[]).some((p)=>String(p.id)===projectId));
  const tasksByStatus=useMemo(()=>{const groups:Record<string,Row[]>={todo:[],in_progress:[],blocked:[],done:[]};for(const task of payload?.tasks??[]){const s=String(task.status??'').toLowerCase().replace(/-/g,'_');const b=s.includes('done')||s.includes('complete')?'done':s.includes('block')||s.includes('wait')?'blocked':s.includes('progress')||s.includes('active')?'in_progress':'todo';groups[b].push(task);}return groups;},[payload?.tasks]);
  const totalGoalProgress=useMemo(()=>{const goals=payload?.goals??[];return goals.length?goals.reduce((sum,g)=>sum+Number(g.progress??0),0)/goals.length:0;},[payload?.goals]);
  async function post(action:string, body:Record<string,unknown>){return api('/api/project-os',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});}
  async function createWorkspace(){if(!newWorkspace.trim())return;try{await post('workspace.create',{input:{name:newWorkspace.trim()}});setNewWorkspace('');await loadWorkspaces();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}
  async function createProject(){if(!newProject.trim())return;try{await post('project.create',{input:{name:newProject.trim(),workspaceId:selectedWorkspace?.id?String(selectedWorkspace.id):undefined}});setNewProject('');await loadWorkspaces();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}
  async function createGoal(){if(!newGoal.trim())return;try{await post('goal.create',{input:{title:newGoal.trim(),level:'company',target:100,current:0,unit:'%'}});setNewGoal('');await loadProject();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}
  async function saveAllocation(){if(!capacityUser.trim()||!weekStart)return;try{await post('capacity.allocate',{input:{userId:capacityUser.trim(),projectId,weekStart,availableHours:Number(available),allocatedHours:Number(allocated)}});await loadProject();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}
  async function saveTime(){try{await post('time.create',{input:{projectId,startedAt:new Date(Date.now()-Number(manualMinutes)*60000).toISOString(),endedAt:new Date().toISOString(),minutes:Number(manualMinutes),note:manualNote}});setManualNote('');await loadProject();}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}
  async function toggleTimer(){try{if(timerRunning){await post('timer.stop',{note:'Sessão de trabalho'});setTimerRunning(false);}else{await post('timer.start',{projectId});setTimerRunning(true);}}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.');}}

  if(loading&&!payload)return <div className="p-6 text-sm text-muted-foreground">A carregar Work OS...</div>;
  return <div className="p-6 space-y-6"><div className="flex flex-col xl:flex-row gap-4 xl:items-end xl:justify-between"><div><div className="flex gap-2 text-sm text-muted-foreground"><Link href="/dashboard">Command Center</Link><span>/</span><span>Work OS</span></div><h1 className="text-3xl font-bold mt-2">Workspaces + Project OS</h1><p className="text-muted-foreground mt-1">Work management integrado para projetos, objetivos, capacidade, risco e reporting.</p></div><Button variant="outline" onClick={()=>void refresh()}><RefreshCw className="h-4 w-4 mr-2"/>Atualizar</Button></div>{error&&<div className="rounded-lg border border-destructive/40 p-3 text-sm text-destructive">{error}</div>}
  <div className="grid xl:grid-cols-[300px_1fr] gap-6"><Card className="h-fit"><CardHeader><CardTitle className="text-base">Workspaces inteligentes</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={newWorkspace} onChange={e=>setNewWorkspace(e.target.value)} placeholder="Novo workspace"/><Button size="icon" onClick={()=>void createWorkspace()}><Plus className="h-4 w-4"/></Button></div><div className="space-y-2">{workspaces.map(w=><div key={w.id} className="rounded-lg border p-3"><div className="font-medium">{String(w.name??'Workspace')}</div><div className="text-xs text-muted-foreground">{Array.isArray(w.projects)?w.projects.length:0} projetos</div>{Array.isArray(w.projects)&&<div className="mt-2 space-y-1">{(w.projects as Row[]).map(p=><button key={p.id} onClick={()=>setProjectId(String(p.id))} className={`block w-full text-left rounded-md px-2 py-1.5 text-sm ${String(p.id)===projectId?'bg-primary/10 font-medium':'hover:bg-muted'}`}>{String(p.name??'Project')}</button>)}</div>}</div>)}</div></CardContent></Card>
  <div className="space-y-6"><Card><CardContent className="p-5"><div className="grid md:grid-cols-[1fr_auto] gap-4"><div><div className="text-sm text-muted-foreground">Project OS</div><div className="text-2xl font-semibold mt-1">{String(payload?.project.name??'Selecione um projeto')}</div><div className="text-sm text-muted-foreground mt-1">{String(payload?.project.objective??'Sem objetivo definido')}</div></div><div className="flex gap-2">{payload?.project.health&&<Badge variant={healthVariant(String(payload.project.health))}>{String(payload.project.health)}</Badge>}</div></div></CardContent></Card><div className="flex gap-2"><Input value={newProject} onChange={e=>setNewProject(e.target.value)} placeholder="Novo projeto no workspace selecionado"/><Button onClick={()=>void createProject()}><Plus className="h-4 w-4 mr-2"/>Projeto</Button></div>
  {payload&&<Tabs value={tab} onValueChange={setTab}><TabsList className="w-full overflow-x-auto justify-start">{tabs.map(([v,l,I])=><TabsTrigger key={v} value={v} className="gap-1"><I className="h-3.5 w-3.5"/>{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview" className="space-y-4 mt-4"><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{[['Tasks',payload.tasks.length],['Overdue',payload.overview.overdueTasks],['Blocked',payload.overview.blockedTasks],['Critical',payload.overview.criticalTasks]].map(([l,v])=><Card key={String(l)}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{String(l)}</CardTitle></CardHeader><CardContent><div className="text-2xl font-semibold">{String(v)}</div></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Project Health Engine</CardTitle></CardHeader><CardContent><div className="flex gap-3 items-center"><Badge variant={healthVariant(String(payload.project.health??'HEALTHY'))}>{String(payload.project.health??'HEALTHY')}</Badge><span className="text-sm text-muted-foreground">{Math.round(Number(payload.project.healthScore??0))}/100</span></div><Progress className="mt-3" value={Number(payload.project.healthScore??0)}/><div className="grid md:grid-cols-2 gap-3 mt-4">{(Array.isArray(payload.project.healthReasons)?payload.project.healthReasons:[]).map(r=><div key={String(r)} className="rounded-md border p-3 text-sm">{String(r)}</div>)}</div></CardContent></Card></TabsContent>
  <TabsContent value="kanban" className="mt-4"><div className="grid xl:grid-cols-4 md:grid-cols-2 gap-4">{Object.entries(tasksByStatus).map(([k,rows])=><Card key={k}><CardHeader><CardTitle className="text-sm capitalize">{k.replace('_',' ')} <Badge variant="secondary">{rows.length}</Badge></CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(t=><div key={t.id} className="rounded-lg border p-3"><div className="font-medium text-sm">{String(t.title??'Task')}</div><div className="text-xs text-muted-foreground mt-1">{String(t.priority??'medium')} · {dateLabel(t.dueDate)}</div></div>)}</CardContent></Card>)}</div></TabsContent>
  <TabsContent value="timeline" className="mt-4"><Card><CardHeader><CardTitle>Timeline / Gantt</CardTitle></CardHeader><CardContent className="space-y-3">{payload.tasks.map(t=><div key={t.id} className="grid md:grid-cols-[260px_1fr_100px] gap-3 items-center"><div className="text-sm truncate">{String(t.title??'Task')}</div><div className="h-3 rounded bg-muted overflow-hidden"><div className="h-full rounded bg-primary" style={{width:`${Math.max(4,Math.min(100,Number(t.progress??(['done','completed'].includes(String(t.status))?100:30))))}%`}}/></div><div className="text-xs text-muted-foreground text-right">{dateLabel(t.dueDate)}</div></div>)}</CardContent></Card></TabsContent>
  <TabsContent value="calendar" className="mt-4"><div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Calendar / deadlines</CardTitle></CardHeader><CardContent className="space-y-2">{payload.tasks.filter(t=>t.dueDate).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).slice(0,30).map(t=><div key={t.id} className="flex justify-between rounded-md border p-3 text-sm"><span>{String(t.title??'Task')}</span><span>{dateLabel(t.dueDate)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Milestones</CardTitle></CardHeader><CardContent className="space-y-2">{payload.milestones.map(m=><div key={m.id} className="rounded-md border p-3"><div className="font-medium">{String(m.name??m.title??'Milestone')}</div><div className="text-xs text-muted-foreground">{dateLabel(m.dueDate)} · variance {String(m.varianceDays??0)}d</div></div>)}</CardContent></Card></div></TabsContent>
  <TabsContent value="resources" className="mt-4"><Card><CardHeader><CardTitle>Capacity planning</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid md:grid-cols-5 gap-2"><Input value={capacityUser} onChange={e=>setCapacityUser(e.target.value)} placeholder="User ID"/><Input value={weekStart} onChange={e=>setWeekStart(e.target.value)} placeholder="2026-09-14"/><Input value={available} onChange={e=>setAvailable(e.target.value)} type="number" placeholder="Available h"/><Input value={allocated} onChange={e=>setAllocated(e.target.value)} type="number" placeholder="Allocated h"/><Button onClick={()=>void saveAllocation()}>Guardar</Button></div>{payload.allocations.map(a=><div key={a.id} className="grid md:grid-cols-[1fr_120px_120px_120px] gap-3 items-center border rounded-lg p-3"><div>{String(a.userId)}</div><div>{String(a.availableHours)}h</div><div>{String(a.allocatedHours)}h</div><Badge variant={Number(a.utilization??0)>100?'destructive':'secondary'}>{String(a.utilization??0)}%</Badge></div>)}<div className="pt-3 border-t text-sm">Total: {payload.overview.capacity.allocatedHours}h / {payload.overview.capacity.availableHours}h, utilização {payload.overview.capacity.utilization}%.</div></CardContent></Card></TabsContent>
  <TabsContent value="goals" className="mt-4"><Card><CardHeader><CardTitle>Goals / OKRs</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={newGoal} onChange={e=>setNewGoal(e.target.value)} placeholder="Novo goal"/><Button onClick={()=>void createGoal()}><Plus className="h-4 w-4 mr-2"/>Goal</Button></div><div className="text-sm text-muted-foreground">Progresso médio: {Math.round(totalGoalProgress)}%</div>{payload.goals.map(g=><div key={g.id} className="rounded-lg border p-4"><div className="flex justify-between"><div><div className="font-medium">{String(g.title??'Goal')}</div><div className="text-xs text-muted-foreground">{String(g.level??'company')} · {String(g.current??0)} / {String(g.target??0)} {String(g.unit??'%')}</div></div><Badge variant="outline">{Math.round(Number(g.progress??0))}%</Badge></div><Progress className="mt-3" value={Number(g.progress??0)}/></div>)}</CardContent></Card></TabsContent>
  <TabsContent value="risks" className="mt-4"><div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Risks</CardTitle></CardHeader><CardContent className="space-y-2">{payload.risks.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="font-medium">{String(r.title??r.name??'Risk')}</div><div className="text-xs text-muted-foreground">{statusLabel(r.status)} · {String(r.severity??'medium')}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Dependencies</CardTitle></CardHeader><CardContent className="space-y-2">{payload.dependencies.map(d=><div key={d.id} className="rounded-lg border p-3 text-sm">{String(d.sourceId)} → {String(d.targetId)}</div>)}</CardContent></Card></div></TabsContent>
  <TabsContent value="activity" className="mt-4"><Card><CardHeader><CardTitle>Activity</CardTitle></CardHeader><CardContent className="space-y-2">{payload.activities.map(a=><div key={a.id} className="rounded-lg border p-3 text-sm">{String(a.eventName??'activity')} · {dateLabel(a.createdAt)}</div>)}</CardContent></Card></TabsContent>
  <TabsContent value="time" className="mt-4"><Card><CardHeader><CardTitle>Time tracking</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button onClick={()=>void toggleTimer()} variant={timerRunning?'destructive':'default'}>{timerRunning?'Parar timer':'Iniciar timer'}</Button><Input className="max-w-[120px]" type="number" value={manualMinutes} onChange={e=>setManualMinutes(e.target.value)}/><Input className="min-w-[220px]" value={manualNote} onChange={e=>setManualNote(e.target.value)} placeholder="Nota da sessão"/><Button variant="outline" onClick={()=>void saveTime()}>Registar manualmente</Button></div><div className="text-sm text-muted-foreground">Total registado: {payload.timeEntries.reduce((s,e)=>s+Number(e.minutes??0),0)} minutos.</div>{payload.timeEntries.map(e=><div key={e.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{String(e.note??'Time entry')}</span><span>{Number(e.minutes??0)} min</span></div>)}</CardContent></Card></TabsContent>
  <TabsContent value="budget" className="mt-4"><Card><CardHeader><CardTitle>Budget</CardTitle></CardHeader><CardContent><div className="flex justify-between text-sm"><span>Consumido</span><span>{Math.round(Number(payload.overview.budgetPercent))}%</span></div><Progress className="mt-2" value={Math.min(100,Number(payload.overview.budgetPercent))}/><div className="grid md:grid-cols-3 gap-3 mt-5"><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Budget</div><div className="text-xl font-semibold">{Number(payload.project.budget??0).toLocaleString('pt-PT')}</div></div><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Spent</div><div className="text-xl font-semibold">{Number(payload.project.budgetSpent??0).toLocaleString('pt-PT')}</div></div><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Deadline</div><div className="text-xl font-semibold">{payload.overview.deadlineDays===999?'Sem prazo':`${payload.overview.deadlineDays}d`}</div></div></div></CardContent></Card></TabsContent>
  </Tabs>}</div></div></div>;
}
