'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Activity, CalendarDays, CheckCircle2, Clock3, DollarSign, Flag, GanttChartSquare, LayoutDashboard, Plus, RefreshCw, Target, Users, XCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

interface Row { id: string; [key: string]: unknown }
interface ProjectPayload { project: Row; overview: { overdueTasks: number; blockedTasks: number; criticalTasks: number; capacity: { availableHours: number; allocatedHours: number; utilization: number; overloadHours: number; underloadHours: number }; budgetPercent: number; deadlineDays: number; milestoneVarianceDays: number; recentActivityDays: number }; tasks: Row[]; subtasks: Row[]; milestones: Row[]; dependencies: Row[]; files: Row[]; docs: Row[]; meetings: Row[]; risks: Row[]; decisions: Row[]; goals: Row[]; allocations: Row[]; timeEntries: Row[]; }

const tabs = [
  ['overview', 'Overview', LayoutDashboard], ['kanban', 'Kanban', LayoutDashboard], ['timeline', 'Timeline', GanttChartSquare], ['calendar', 'Calendar', CalendarDays], ['resources', 'Resources', Users], ['goals', 'Goals', Target], ['risks', 'Risks', XCircle], ['activity', 'Activity', Activity], ['time', 'Time', Clock3], ['budget', 'Budget', DollarSign],
] as const;

function healthVariant(health: string) { return health === 'HEALTHY' ? 'secondary' : health === 'AT_RISK' ? 'outline' : 'destructive'; }
function statusLabel(value: unknown) { return String(value ?? 'active').replace(/_/g, ' ').replace(/-/g, ' '); }
function dateLabel(value: unknown) { const date = typeof value === 'string' ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('pt-PT') : 'Sem data'; }

export default function ProjectOsView() {
  const [workspaces, setWorkspaces] = useState<Row[]>([]);
  const [projectId, setProjectId] = useState('');
  const [payload, setPayload] = useState<ProjectPayload | null>(null);
  const [tab, setTab] = useState('overview');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newWorkspace, setNewWorkspace] = useState('');
  const [newProject, setNewProject] = useState('');
  const [newGoal, setNewGoal] = useState('');

  async function loadWorkspaces() { const response = await fetch('/api/project-os?resource=workspaces', { cache: 'no-store', credentials: 'include' }); if (!response.ok) throw new Error('Não foi possível carregar Workspaces.'); const result = await response.json() as { data: Row[] }; setWorkspaces(result.data); const firstProject = result.data.flatMap((workspace) => Array.isArray(workspace.projects) ? workspace.projects as Row[] : [])[0]; if (!projectId && firstProject?.id) setProjectId(String(firstProject.id)); }
  async function loadProject(id = projectId) { if (!id) return; const response = await fetch(`/api/project-os?resource=project&projectId=${encodeURIComponent(id)}`, { cache: 'no-store', credentials: 'include' }); if (!response.ok) throw new Error('Não foi possível carregar o Project OS.'); const result = await response.json() as { data: ProjectPayload }; setPayload(result.data); }
  async function refresh() { setLoading(true); setError(null); try { await loadWorkspaces(); if (projectId) await loadProject(); } catch (err) { setError(err instanceof Error ? err.message : 'Erro inesperado.'); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (projectId) void loadProject(projectId).catch((err) => setError(err instanceof Error ? err.message : 'Erro inesperado.')); }, [projectId]);

  const selectedWorkspace = workspaces.find((workspace) => Array.isArray(workspace.projects) && (workspace.projects as Row[]).some((project) => String(project.id) === projectId));
  const tasksByStatus = useMemo(() => { const groups: Record<string, Row[]> = { todo: [], in_progress: [], blocked: [], done: [] }; for (const task of payload?.tasks ?? []) { const key = String(task.status ?? '').toLowerCase().replace(/-/g, '_'); const bucket = key.includes('done') || key.includes('complete') ? 'done' : key.includes('block') || key.includes('wait') ? 'blocked' : key.includes('progress') || key.includes('active') ? 'in_progress' : 'todo'; groups[bucket].push(task); } return groups; }, [payload?.tasks]);
  const totalGoalProgress = useMemo(() => { const goals = payload?.goals ?? []; return goals.length ? goals.reduce((sum, goal) => sum + Number(goal.progress ?? 0), 0) / goals.length : 0; }, [payload?.goals]);

  async function post(action: string, body: Record<string, unknown>) { const response = await fetch('/api/project-os', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ action, ...body }) }); if (!response.ok) { const result = await response.json().catch(() => ({})); throw new Error(String(result.error ?? 'REQUEST_FAILED')); } return response.json(); }
  async function createWorkspace() { if (!newWorkspace.trim()) return; try { await post('workspace.create', { input: { name: newWorkspace.trim() } }); setNewWorkspace(''); await loadWorkspaces(); } catch (err) { setError(err instanceof Error ? err.message : 'Erro inesperado.'); } }
  async function createProject() { if (!newProject.trim()) return; try { await post('project.create', { input: { name: newProject.trim(), workspaceId: selectedWorkspace?.id ? String(selectedWorkspace.id) : undefined } }); setNewProject(''); await loadWorkspaces(); } catch (err) { setError(err instanceof Error ? err.message : 'Erro inesperado.'); } }
  async function createGoal() { if (!newGoal.trim()) return; try { await post('goal.create', { input: { title: newGoal.trim(), level: 'company', target: 100, current: 0, unit: '%' } }); setNewGoal(''); await loadProject(); } catch (err) { setError(err instanceof Error ? err.message : 'Erro inesperado.'); } }

  if (loading && !payload) return <div className="p-6 text-sm text-muted-foreground">A carregar Work OS...</div>;
  return <div className="p-6 space-y-6">
    <div className="flex flex-col xl:flex-row gap-4 xl:items-end xl:justify-between">
      <div><div className="flex items-center gap-2 text-sm text-muted-foreground"><Link href="/dashboard">Command Center</Link><span>/</span><span>Work OS</span></div><h1 className="text-3xl font-bold mt-2">Workspaces + Project OS</h1><p className="text-muted-foreground mt-1">Projetos, tarefas, objetivos, capacidade, risco, tempo e reporting no mesmo contexto operacional.</p></div>
      <Button variant="outline" onClick={() => void refresh()}><RefreshCw className="h-4 w-4 mr-2" />Atualizar</Button>
    </div>
    {error && <div className="rounded-lg border border-destructive/40 p-3 text-sm text-destructive">{error}</div>}

    <div className="grid xl:grid-cols-[300px_1fr] gap-6">
      <Card className="h-fit"><CardHeader><CardTitle className="text-base">Workspaces inteligentes</CardTitle></CardHeader><CardContent className="space-y-4">
        <div className="flex gap-2"><Input value={newWorkspace} onChange={(e) => setNewWorkspace(e.target.value)} placeholder="Novo workspace"/><Button size="icon" onClick={() => void createWorkspace()}><Plus className="h-4 w-4"/></Button></div>
        <div className="space-y-2">{workspaces.map((workspace) => <div key={workspace.id} className="rounded-lg border p-3"><div className="font-medium">{String(workspace.name ?? 'Workspace')}</div><div className="text-xs text-muted-foreground mt-1">{Array.isArray(workspace.projects) ? workspace.projects.length : 0} projetos</div>{Array.isArray(workspace.projects) && <div className="mt-2 space-y-1">{(workspace.projects as Row[]).map((project) => <button key={project.id} onClick={() => setProjectId(String(project.id))} className={`block w-full text-left rounded-md px-2 py-1.5 text-sm ${String(project.id) === projectId ? 'bg-primary/10 font-medium' : 'hover:bg-muted'}`}>{String(project.name ?? 'Project')}</button>)}</div>}</div>)}</div>
      </CardContent></Card>

      <div className="space-y-6">
        <Card><CardContent className="p-5"><div className="grid md:grid-cols-[1fr_auto] gap-4"><div><div className="text-sm text-muted-foreground">Project OS</div><div className="text-2xl font-semibold mt-1">{String(payload?.project.name ?? 'Selecione um projeto')}</div><div className="text-sm text-muted-foreground mt-1">{String(payload?.project.objective ?? 'Sem objetivo definido')}</div></div><div className="flex flex-wrap gap-2 items-start">{payload?.project.health && <Badge variant={healthVariant(String(payload.project.health))}>{String(payload.project.health)}</Badge>} {payload?.project.healthScore !== undefined && <Badge variant="outline">Health {Math.round(Number(payload.project.healthScore))}</Badge>}</div></div></CardContent></Card>
        <div className="flex gap-2"><Input value={newProject} onChange={(e) => setNewProject(e.target.value)} placeholder="Novo projeto no workspace selecionado"/><Button onClick={() => void createProject()}><Plus className="h-4 w-4 mr-2"/>Projeto</Button></div>

        {payload && <Tabs value={tab} onValueChange={setTab}><TabsList className="w-full overflow-x-auto justify-start">{tabs.map(([value, label, Icon]) => <TabsTrigger key={value} value={value} className="gap-1"><Icon className="h-3.5 w-3.5"/>{label}</TabsTrigger>)}</TabsList>
          <TabsContent value="overview" className="space-y-4 mt-4"><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{[['Tasks', payload.tasks.length], ['Overdue', payload.overview.overdueTasks], ['Blocked', payload.overview.blockedTasks], ['Critical', payload.overview.criticalTasks]].map(([label, value]) => <Card key={String(label)}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{String(label)}</CardTitle></CardHeader><CardContent><div className="text-2xl font-semibold">{String(value)}</div></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Project Health Engine</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2 mb-4"><Badge variant={healthVariant(String(payload.project.health ?? 'HEALTHY'))}>{String(payload.project.health ?? 'HEALTHY')}</Badge><span className="text-sm text-muted-foreground">Score {Math.round(Number(payload.project.healthScore ?? 0))}/100</span></div><Progress value={Number(payload.project.healthScore ?? 0)}/><div className="grid md:grid-cols-2 gap-3 mt-4">{(Array.isArray(payload.project.healthReasons) ? payload.project.healthReasons : []).map((reason) => <div key={String(reason)} className="rounded-md border p-3 text-sm">{String(reason)}</div>)}</div></CardContent></Card></TabsContent>
          <TabsContent value="kanban" className="mt-4"><div className="grid xl:grid-cols-4 md:grid-cols-2 gap-4">{Object.entries(tasksByStatus).map(([key, rows]) => <Card key={key}><CardHeader><CardTitle className="text-sm capitalize">{statusLabel(key)} <Badge variant="secondary">{rows.length}</Badge></CardTitle></CardHeader><CardContent className="space-y-2">{rows.map((task) => <div key={task.id} className="rounded-lg border p-3"><div className="font-medium text-sm">{String(task.title ?? 'Task')}</div><div className="text-xs text-muted-foreground mt-1">{String(task.priority ?? 'medium')} · {dateLabel(task.dueDate)}</div></div>)}</CardContent></Card>)}</div></TabsContent>
          <TabsContent value="timeline" className="mt-4"><Card><CardHeader><CardTitle>Timeline / Gantt</CardTitle></CardHeader><CardContent className="space-y-3">{payload.tasks.map((task) => <div key={task.id} className="grid md:grid-cols-[260px_1fr_100px] gap-3 items-center"><div className="text-sm truncate">{String(task.title ?? 'Task')}</div><div className="h-3 rounded bg-muted overflow-hidden"><div className="h-full rounded bg-primary" style={{ width: `${Math.max(4, Math.min(100, Number(task.progress ?? (['done','completed'].includes(String(task.status)) ? 100 : 30))))}%` }}/></div><div className="text-xs text-muted-foreground text-right">{dateLabel(task.dueDate)}</div></div>)}</CardContent></Card></TabsContent>
          <TabsContent value="calendar" className="mt-4"><div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Deadlines</CardTitle></CardHeader><CardContent className="space-y-2">{payload.tasks.filter((task) => task.dueDate).sort((a,b) => String(a.dueDate).localeCompare(String(b.dueDate))).slice(0,30).map((task) => <div key={task.id} className="flex justify-between rounded-md border p-3 text-sm"><span>{String(task.title ?? 'Task')}</span><span className="text-muted-foreground">{dateLabel(task.dueDate)}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Milestones</CardTitle></CardHeader><CardContent className="space-y-2">{payload.milestones.map((milestone) => <div key={milestone.id} className="rounded-md border p-3"><div className="font-medium">{String(milestone.name ?? milestone.title ?? 'Milestone')}</div><div className="text-xs text-muted-foreground">{dateLabel(milestone.dueDate)} · variance {String(milestone.varianceDays ?? 0)}d</div></div>)}</CardContent></Card></div></TabsContent>
          <TabsContent value="resources" className="mt-4"><Card><CardHeader><CardTitle>Capacity planning</CardTitle></CardHeader><CardContent className="space-y-3">{payload.allocations.length ? payload.allocations.map((allocation) => <div key={allocation.id} className="grid md:grid-cols-[1fr_120px_120px_140px] gap-3 items-center border rounded-lg p-3"><div>{String(allocation.userId)}</div><div>{String(allocation.availableHours)}h</div><div>{String(allocation.allocatedHours)}h</div><Badge variant={Number(allocation.utilization ?? 0) > 100 ? 'destructive' : 'secondary'}>{String(allocation.utilization ?? 0)}%</Badge></div>) : <div className="text-sm text-muted-foreground">Ainda não existem alocações para este projeto.</div>}<div className="pt-3 border-t text-sm">Total: {payload.overview.capacity.allocatedHours}h alocadas de {payload.overview.capacity.availableHours}h disponíveis, utilização {payload.overview.capacity.utilization}%.</div></CardContent></Card></TabsContent>
          <TabsContent value="goals" className="mt-4"><Card><CardHeader><CardTitle className="flex items-center justify-between">Goals / OKRs <Button size="sm" onClick={() => void createGoal()}><Plus className="h-4 w-4 mr-2"/>Goal</Button></CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={newGoal} onChange={(e) => setNewGoal(e.target.value)} placeholder="Novo Company / Department / Team Goal"/></div><div className="text-sm text-muted-foreground">Progresso médio: {Math.round(totalGoalProgress)}%</div>{payload.goals.map((goal) => <div key={goal.id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><div><div className="font-medium">{String(goal.title ?? 'Goal')}</div><div className="text-xs text-muted-foreground">{String(goal.level ?? 'company')} · {String(goal.current ?? 0)} / {String(goal.target ?? 0)} {String(goal.unit ?? '%')}</div></div><Badge variant="outline">{Math.round(Number(goal.progress ?? 0))}%</Badge></div><Progress className="mt-3" value={Number(goal.progress ?? 0)}/></div>)}</CardContent></Card></TabsContent>
          <TabsContent value="risks" className="mt-4"><div className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Unresolved risks</CardTitle></CardHeader><CardContent className="space-y-2">{payload.risks.map((risk) => <div key={risk.id} className="rounded-lg border p-3"><div className="font-medium">{String(risk.title ?? risk.name ?? 'Risk')}</div><div className="text-xs text-muted-foreground mt-1">{statusLabel(risk.status)} · {String(risk.severity ?? 'medium')}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Dependencies</CardTitle></CardHeader><CardContent className="space-y-2">{payload.dependencies.map((dependency) => <div key={dependency.id} className="rounded-lg border p-3 text-sm">{String(dependency.sourceId)} → {String(dependency.targetId)}</div>)}</CardContent></Card></div></TabsContent>
          <TabsContent value="activity" className="mt-4"><Card><CardHeader><CardTitle>Activity</CardTitle></CardHeader><CardContent className="space-y-2">{payload.activities?.map((activity) => <div key={activity.id} className="rounded-lg border p-3 text-sm">{String(activity.eventName ?? 'activity')} · {dateLabel(activity.createdAt)}</div>)}</CardContent></Card></TabsContent>
          <TabsContent value="time" className="mt-4"><Card><CardHeader><CardTitle>Time tracking</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2 text-sm mb-4"><Clock3 className="h-4 w-4"/> {payload.timeEntries.reduce((sum, item) => sum + Number(item.minutes ?? 0), 0)} minutos registados no projeto.</div><div className="space-y-2">{payload.timeEntries.map((entry) => <div key={entry.id} className="rounded-lg border p-3 text-sm flex justify-between"><span>{String(entry.note ?? 'Time entry')}</span><span>{Number(entry.minutes ?? 0)} min</span></div>)}</div></CardContent></Card></TabsContent>
          <TabsContent value="budget" className="mt-4"><Card><CardHeader><CardTitle>Budget</CardTitle></CardHeader><CardContent><div className="flex justify-between text-sm"><span>Consumido</span><span>{Math.round(Number(payload.overview.budgetPercent))}%</span></div><Progress className="mt-2" value={Math.min(100, Number(payload.overview.budgetPercent))}/><div className="grid md:grid-cols-3 gap-3 mt-5"><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Budget</div><div className="text-xl font-semibold">{Number(payload.project.budget ?? 0).toLocaleString('pt-PT')}</div></div><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Spent</div><div className="text-xl font-semibold">{Number(payload.project.budgetSpent ?? 0).toLocaleString('pt-PT')}</div></div><div className="rounded-lg border p-4"><div className="text-xs text-muted-foreground">Deadline</div><div className="text-xl font-semibold">{payload.overview.deadlineDays === 999 ? 'Sem prazo' : `${payload.overview.deadlineDays}d`}</div></div></div></CardContent></Card></TabsContent>
        </Tabs>}
      </div>
    </div>
  </div>;
}
