'use client';

import { useEffect, useState } from 'react';
import { Download, Languages, Moon, Save, Sun, Bell, Accessibility, RefreshCw } from 'lucide-react';
import { useTheme } from 'next-themes';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';

type Settings = { language:string; timezone:string; theme:string; fontSize:string; emailNotifications:boolean; pushNotifications:boolean; mentionsNotifications:boolean; highContrast:boolean; reducedMotion:boolean; voiceOver:boolean };
const fallback: Settings = { language:'pt', timezone:'Africa/Maputo', theme:'dark', fontSize:'medium', emailNotifications:true, pushNotifications:true, mentionsNotifications:true, highContrast:false, reducedMotion:false, voiceOver:false };

export default function SettingsPage() {
  const { toast } = useToast(); const { setTheme } = useTheme(); const [settings,setSettings]=useState<Settings>(fallback); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);try{const response=await fetch('/api/settings',{credentials:'include',cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'SETTINGS_LOAD_FAILED');setSettings(payload.settings??fallback);if(payload.settings?.theme)setTheme(payload.settings.theme);}catch(error){toast({variant:'destructive',title:'Não foi possível carregar definições',description:error instanceof Error?error.message:'Erro inesperado.'});}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const patch=(key:keyof Settings,value:Settings[keyof Settings])=>setSettings((current)=>({...current,[key]:value}));
  const save=async()=>{setSaving(true);try{const response=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(settings)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'SETTINGS_UPDATE_FAILED');setTheme(settings.theme);toast({title:'Configurações guardadas',description:'As preferências foram persistidas no backend.'});}catch(error){toast({variant:'destructive',title:'Falha ao guardar',description:error instanceof Error?error.message:'Erro inesperado.'});}finally{setSaving(false);}};
  const exportData=async()=>{try{const response=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'export'})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'EXPORT_FAILED');const blob=new Blob([JSON.stringify(payload.export,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='oryon-my-data.json';anchor.click();URL.revokeObjectURL(url);toast({title:'Exportação concluída',description:'O ficheiro JSON foi gerado.'});}catch(error){toast({variant:'destructive',title:'Falha na exportação',description:error instanceof Error?error.message:'Erro inesperado.'});}};

  return <div className="grid gap-6"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.12em] text-primary">Enterprise Preferences</p><h1 className="text-3xl font-bold">Configurações</h1><p className="mt-1 text-sm text-muted-foreground">Preferências pessoais persistidas e sincronizadas com o backend Oryon.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?'mr-2 h-4 w-4 animate-spin':'mr-2 h-4 w-4'}/>Actualizar</Button><Button onClick={()=>void save()} disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?'A guardar…':'Guardar alterações'}</Button></div></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Languages className="h-5 w-5 text-primary"/>Geral</CardTitle><CardDescription>Idioma e fuso horário usados pela experiência operacional.</CardDescription></CardHeader><CardContent className="space-y-5"><div><Label>Idioma</Label><Select value={settings.language} onValueChange={(value)=>patch('language',value)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pt">Português</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></div><div><Label>Fuso horário</Label><Select value={settings.timezone} onValueChange={(value)=>patch('timezone',value)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Africa/Maputo">Africa/Maputo (UTC+2)</SelectItem><SelectItem value="UTC">UTC</SelectItem><SelectItem value="Europe/Lisbon">Europe/Lisbon</SelectItem></SelectContent></Select></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Moon className="h-5 w-5 text-primary"/>Aparência</CardTitle><CardDescription>O tema é aplicado imediatamente e guardado no perfil.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3"><Button variant="outline" className={settings.theme==='dark'?'ring-2 ring-primary':''} onClick={()=>patch('theme','dark')}><Moon className="mr-2 h-4 w-4"/>Escuro</Button><Button variant="outline" className={settings.theme==='light'?'ring-2 ring-primary':''} onClick={()=>patch('theme','light')}><Sun className="mr-2 h-4 w-4"/>Claro</Button><div className="col-span-2"><Label>Tamanho da fonte</Label><Select value={settings.fontSize} onValueChange={(value)=>patch('fontSize',value)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="small">Pequeno</SelectItem><SelectItem value="medium">Médio</SelectItem><SelectItem value="large">Grande</SelectItem></SelectContent></Select></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Bell className="h-5 w-5 text-primary"/>Notificações</CardTitle><CardDescription>Preferências persistidas por utilizador.</CardDescription></CardHeader><CardContent className="space-y-3">{[['emailNotifications','Email','Resumos e alertas importantes.'],['pushNotifications','Browser','Alertas em tempo real.'],['mentionsNotifications','Menções e tarefas','Só itens dirigidos a si.']].map(([key,label,description])=><div key={key} className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={Boolean(settings[key as keyof Settings])} onCheckedChange={(value)=>patch(key as keyof Settings,value)}/></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Accessibility className="h-5 w-5 text-primary"/>Acessibilidade</CardTitle><CardDescription>Preferências para leitura e movimento.</CardDescription></CardHeader><CardContent className="space-y-3">{[['highContrast','Alto contraste'],['reducedMotion','Reduzir movimento'],['voiceOver','Voice over / TTS']].map(([key,label])=><div key={key} className="flex items-center justify-between rounded-xl border p-3"><Label>{label}</Label><Switch checked={Boolean(settings[key as keyof Settings])} onCheckedChange={(value)=>patch(key as keyof Settings,value)}/></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Download className="h-5 w-5 text-primary"/>Dados e privacidade</CardTitle><CardDescription>Exportação dos dados associados à sua conta empresarial.</CardDescription></CardHeader><CardContent><Button variant="outline" onClick={()=>void exportData()}>Exportar os meus dados</Button></CardContent></Card>
  </div>;
}
