'use client';

import { useEffect, useState } from 'react';
import { Brain, CheckCircle2, ListChecks, Mic2, Play, Save, Video, Waves } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';

type Meeting={id:string;title?:string;agenda?:string;notes?:string;transcript?:string;aiSummary?:string;decisions?:string[];actionItems?:Array<{title:string;ownerId?:string;dueDate?:string}>;risks?:string[];topics?:string[];recordingUrl?:string;videoUrl?:string;audioUrl?:string;captionsUrl?:string};

export default function MeetingIntelligenceView(){
 const {toast}=useToast();const [meetings,setMeetings]=useState<Meeting[]>([]);const [selected,setSelected]=useState<Meeting|null>(null);const [transcript,setTranscript]=useState('');const [notes,setNotes]=useState('');const [agenda,setAgenda]=useState('');const [loading,setLoading]=useState(false);
 const load=async()=>{const r=await fetch('/api/modules/meetings',{cache:'no-store'});const p=await r.json();if(r.ok)setMeetings(Array.isArray(p.data)?p.data:[])};useEffect(()=>{void load()},[]);
 const pick=(m:Meeting)=>{setSelected(m);setTranscript(m.transcript??'');setNotes(m.notes??'');setAgenda(m.agenda??'')};
 const post=async(action:string,input?:Record<string,unknown>)=>{if(!selected)return;setLoading(true);try{const r=await fetch('/api/meetings/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:selected.id,input,transcript,source:'manual-ui'})});const p=await r.json();if(!r.ok)throw new Error(p.error);toast({title:'Meeting Intelligence',description:action==='analyze'?'Análise concluída':'Operação concluída'});await load();const fresh=(await (await fetch(`/api/modules/meetings?id=${selected.id}`,{cache:'no-store'})).json()).data as Meeting;pick(fresh)}catch(e){toast({variant:'destructive',title:'Operação falhou',description:e instanceof Error?e.message:'Erro'})}finally{setLoading(false)}};
 return <div className="p-4 md:p-6 space-y-5"><div><div className="text-sm text-muted-foreground">Meetings + Context</div><h1 className="text-3xl font-bold mt-1">Meeting Intelligence</h1><p className="text-muted-foreground">Transcript → Summary → Decisions → Action Items → Tasks/Approvals.</p></div><div className="grid xl:grid-cols-[300px_1fr] gap-4"><Card className="h-fit"><CardHeader><CardTitle className="text-sm">Meetings</CardTitle></CardHeader><CardContent className="space-y-2">{meetings.map(m=><Button key={m.id} variant={selected?.id===m.id?'secondary':'outline'} className="w-full justify-start" onClick={()=>pick(m)}>{m.title??'Sem título'}</Button>)}{!meetings.length&&<div className="text-sm text-muted-foreground">Ainda não existem reuniões.</div>}</CardContent></Card>
 <div className="space-y-4">{selected?<><Card><CardHeader><CardTitle className="flex items-center gap-2"><Video className="h-4 w-4"/>{selected.title??'Reunião'}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid md:grid-cols-3 gap-3"><div className="rounded-lg border p-3 text-sm"><div className="text-muted-foreground">Video</div><div className="font-medium mt-1">{selected.videoUrl||selected.recordingUrl?'Ligado':'Metadata pronta'}</div></div><div className="rounded-lg border p-3 text-sm"><div className="text-muted-foreground">Audio</div><div className="font-medium mt-1">{selected.audioUrl?'Ligado':'Metadata pronta'}</div></div><div className="rounded-lg border p-3 text-sm"><div className="text-muted-foreground">Captions</div><div className="font-medium mt-1">{selected.captionsUrl?'Disponíveis':'Pode ser ingerido'}</div></div></div><div className="grid md:grid-cols-2 gap-3"><div><label className="text-sm font-medium">Agenda</label><Textarea value={agenda} onChange={e=>setAgenda(e.target.value)} className="mt-1" rows={5}/></div><div><label className="text-sm font-medium">Notas</label><Textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1" rows={5}/></div></div><div><label className="text-sm font-medium">Transcript</label><Textarea value={transcript} onChange={e=>setTranscript(e.target.value)} className="mt-1" rows={12} placeholder="Cole ou envie o transcript aqui..."/></div><div className="flex flex-wrap gap-2"><Button onClick={()=>void post('update',{agenda,notes})} disabled={loading}><Save className="h-4 w-4 mr-2"/>Guardar contexto</Button><Button onClick={()=>void post('analyze')} disabled={loading||!transcript&&!notes}><Brain className="h-4 w-4 mr-2"/>Analisar com IA</Button><Button onClick={()=>void post('actions')} disabled={loading||!(selected.actionItems?.length||selected.decisions?.length)} variant="outline"><ListChecks className="h-4 w-4 mr-2"/>Criar Tasks / Approvals</Button></div></CardContent></Card>
 <div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Waves className="h-4 w-4"/>Summary</CardTitle></CardHeader><CardContent><p className="text-sm whitespace-pre-wrap">{selected.aiSummary||'Ainda não analisado.'}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4"/>Decisions & Action Items</CardTitle></CardHeader><CardContent className="space-y-3">{(selected.decisions??[]).map((d,i)=><div key={`d${i}`} className="rounded-lg border p-3 text-sm"><Badge variant="secondary">Decision</Badge><div className="mt-1">{d}</div></div>)}{(selected.actionItems??[]).map((a,i)=><div key={`a${i}`} className="rounded-lg border p-3 text-sm"><Badge>Task</Badge><div className="mt-1 font-medium">{a.title}</div>{a.ownerId&&<div className="text-xs text-muted-foreground">Owner: {a.ownerId}</div>}{a.dueDate&&<div className="text-xs text-muted-foreground">Deadline: {a.dueDate}</div>}</div>)}</CardContent></Card></div></>:<Card><CardContent className="py-16 text-center text-muted-foreground"><Mic2 className="h-8 w-8 mx-auto mb-2"/>Selecione uma reunião.</CardContent></Card>}</div></div></div>;
}
